### ISSUE TITLE
subctl show * fails without --kubecontext/--kubeconfig even after switching to a specific context

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1003]
**What happened**:
subctl show '*' fails when --kubecontext/--kubeconfig flags are not specified even after doing "kubectl config use-context cluster2"

```
[jchhatba@localhost submariner]$ kubectl config use-context cluster2
Switched to context "cluster2".

[jchhatba@localhost submariner]$ subctl show all
Error getting REST config for cluster: invalid configuration: context was not found for specified context: cluster2

subctl version: v0.8.0-rc1

[jchhatba@localhost submariner]$ subctl show all --kubecontext cluster2

Showing information for cluster "cluster2":
    Discovered network details:
        Network plugin:  weave-net
        Service CIDRs:   [100.2.0.0/16]
        Cluster CIDRs:   [10.2.0.0/16]

CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
cluster2                      172.17.0.10                     libreswan           local           
cluster1                      172.17.0.4                      libreswan           remote          
cluster3                      172.17.0.11                     libreswan           remote          

GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS          
cluster1-worker                 cluster1                172.17.0.4      libreswan           100.1.0.0/16, 10.1.0.0/16               connected       
cluster3-worker                 cluster3                172.17.0.11     libreswan           100.3.0.0/16, 10.3.0.0/16               connected       

NODE                            HA STATUS       SUMMARY                         
cluster2-worker                 active          All connections (2) are established

COMPONENT                       REPOSITORY                                            VERSION         
submariner                      localhost:5000                                        local           
submariner-operator             localhost:5000                                        local           
service-discovery               localhost:5000                                        local           
[jchhatba@localhost submariner]$ 
```

**What you expected to happen**:
subctl show * should work even without the flags

**How to reproduce it (as minimally and precisely as possible)**:
git clone latest submariner repo and run make deploy.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): v0.8.0-rc1
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nyechiel** [comment]
@maayanf24 I think this was discussed before?

**Comment by maayanf24** [comment]
> @maayanf24 I think this was discussed before?

this should be working. I'll try to reproduce

**Comment by maayanf24** [comment]
@Jaanki - can you run those cmds and paste the output?
echo $KUBECONFIG
kubectl config get-contexts

**Comment by Jaanki** [comment]
@maayanf24 here is the output
```
$ echo $KUBECONFIG
/home/jchhatba/go/src/github.com/submariner-io/submariner/output/kubeconfigs/kind-config-cluster1:/home/jchhatba/go/src/github.com/submariner-io/submariner/output/kubeconfigs/kind-config-cluster2:/home/jchhatba/go/src/github.com/submariner-io/submariner/output/kubeconfigs/kind-config-cluster3
$ kubectl config get-contexts
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
          cluster1   cluster1   cluster1   
          cluster2   cluster2   cluster2   
*         cluster3   cluster3   cluster3   
```

**Comment by Jaanki** [comment]
The issue can be reproduced by following below steps:

1. Deploy a KIND submariner env using `make deploy`
2. Set a context `kubectl config use-context cluster2`
3. Run `subctl show all` or any other subctl show command

**Comment by skitt** [comment]
I think the major problem here is how we build up the list of `restConfigs` in `getMultipleRestConfigs`. By overriding the `ExplicitPath` using only `Precedence` entries, we end up breaking an assumption in the config-loading code — namely, that the current context is always available in the loaded configuration. `kubectl config use-context ...` stores the current context in _all_ contexts, so with a split `kubeconfig`, each file involved stores the requested context _name_, even if it doesn’t store the context _definition_.

I think the way forward here is to rework `getMultipleRestConfigs` to avoid this situation. Once we have a valid default context (see _e.g._ the start of `getClientConfigAndClusterName`), we can retrieve the corresponding `RawConfig`, which will give us the list of all known contexts. The set of `restConfigs` should then be built using that: instead of iterating over the `Precedence` entries, iterate over the contexts, using the full configuration.
