### ISSUE TITLE
Automated unjoin/uninstall

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-operator#1039]
**What would you like to be added**:

The option to automatically "unjoin" previously connected clusters and delete/uninstall all the Submariner related components via `subctl` / Operator.

**Why is this needed**:

This is a common request from users; manual process is documented as part of https://github.com/submariner-io/submariner-website/pull/411.

Please note that some handlers will need to be triggered via: (or separate an Uninstall call), also that needs to be implemented on the handlers, and the gateways..., how to trigger that is TBD, may be passing an environment variable and reloading all images?

https://github.com/submariner-io/submariner/blob/devel/pkg/event/handler.go#L39

**Comment by mangelajo** [comment]
Please note that some handlers will need to be triggered via: (or separate an Uninstall call), also that needs to be implemented on the handlers, and the gateways..., how to trigger that is TBD, may be passing an environment variable and reloading all images?

https://github.com/submariner-io/submariner/blob/devel/pkg/event/handler.go#L39

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by therevoman** [comment]
Due to a miscommunication two clusters were joined with identical networks.  Having an `unjoin` would be amazing

**Comment by nyechiel** [comment]
@tpantelis this is the issue we currently have. I suggest to turn it into an Epic and scope the broader work (Operator, subctl, submariner-addon, tests, etc)

**Comment by tpantelis** [comment]
Superseded by https://github.com/submariner-io/enhancements/issues/50.
