### ISSUE TITLE
Support deployment within a custom namespace

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-operator#1040]
Some deployment model require installation of components within a specific Kubernetes namespace. For e.g, OpenShift Dedicated dictates that any add-on based offering needs to run on its own exclusive namespace, such as openshift-storage. 

Today, we use `submariner-operator` by default, and I don't think that we validated a deployment (as well as other life cycle management events, such as upgrade, and metrics) with a different custom namespace.

- [ ] Custom broker ns by adding `--namesapce `flag to `deploy-broker` cmd and in `BrokerSpec` Depends on https://github.com/submariner-io/submariner-operator/pull/1682
- [ ] Custom operator ns by adding `--namespace` flag to `join` cmd and not store it in broker
- [ ] Relevant changes in operator, helm, bundle and packagemanifests

**Comment by dfarrell07** [comment]
Here's a little test showing changing the broker NS in the operator doesn't break anything: https://github.com/dfarrell07/submariner-operator/pull/1

**Comment by SteveMattar** [comment]
The namespace `submariner-k8s-broker` is a constant
https://github.com/submariner-io/submariner-operator/blob/b52cf2d150b9a167d8a413a0bb5071d8359adda7/pkg/broker/namespace.go#L30-L38

**Comment by skitt** [comment]
This is required to support multiple clustersets in OCM.

**Comment by nyechiel** [comment]
@skitt @donaldh is this actually done now or do we have any other gaps to track?

**Comment by skitt** [comment]
> @skitt @donaldh is this actually done now or do we have any other gaps to track?

We still have hard-coded namespaces in various places, _e.g._ https://github.com/submariner-io/submariner-operator/blob/devel/internal/constants/constants.go#L24

**Comment by nyechiel** [comment]
Done.
