### ISSUE TITLE
Fix kubeinit integration to make sure verification passes

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1041]
**What happened**:

When check-okd-rke label is added to PRs a job starts where OKD + RKE are tested together, but something
seems to be failing on verification.

**What you expected to happen**:

Verify passes

**How to reproduce it (as minimally and precisely as possible)**:

Create a PR, and add the check-okd-rke label.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ccamacho** [comment]
Hi!
I added the label and rebased https://github.com/submariner-io/submariner-operator/pull/974 

When I get the CI results I'll post them here, in theory, there are a few tests passing, other skipped, and a few failing. The idea is to understand the environment requirements to make them pass and have the okd-rke integration working.

**Comment by ccamacho** [comment]
Here you have them, the results from #974 are uploaded to the CI log folder [1] where the deployment steps finished.

Then there is the subctl verify output [2] where the tasks failed fails like:

```
    "[discovery] Test Stateful Sets Discovery Across Clusters",
    "\u001b[90m/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:31\u001b[0m",
    "  when a pod tries to resolve a podname from stateful set in a remote cluster",
    "  \u001b[90m/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:34\u001b[0m",
    "    \u001b[91m\u001b[1mshould resolve the pod IP from the remote cluster [It]\u001b[0m",
    "    \u001b[90m/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:35\u001b[0m",
    "",
    "    \u001b[91mFailed to retrieve ServiceExport. No ServiceExportConditions",
    "    Unexpected error:",
    "        <*errors.errorString | 0xc0002b81b0>: {",
    "            s: \"timed out waiting for the condition\",",
    "        }",
    "        timed out waiting for the condition",
    "    occurred\u001b[0m",
    "",
```

[1]: https://kubeinit-bot.github.io/kubeinit-ci-results/908392-okd.rke-libvirt-1-2-submariner-2021.01.22.04.33.09-1/index.html
[2]: https://kubeinit-bot.github.io/kubeinit-ci-results/908392-okd.rke-libvirt-1-2-submariner-2021.01.22.04.33.09-1/results/707.html

**Comment by tpantelis** [comment]
bump
