### ISSUE TITLE
CoreDNS in AKS uses two configmaps.  the lighthouse forwarding domain needs added to coredns-custom

### ISSUE THREAD

**Issue by brandonwittwer** [submariner-io/submariner-operator#1046]
**Platform:** AKS (Azure Kubernetes Service) 

**Current Behavior:** Upon joining the clusterset, the configmap named "coredns" is modified. This file is soft-locked (allows the write, but immediately overwrites the file with infrastructure-layer-only data).

**Desired behavior:** when a configmap by the name of "coredns-custom" exists,  it should be the one written to. It also requires that the map be named `{anyWordHere}.server`  (lighthouse.server would serve nicely IMHO) instead of "coreFile".  See official documentation for formatting: https://docs.microsoft.com/en-us/azure/aks/coredns-custom#custom-forward-server

Additional notes: 
a little branch logic to UpdateDNSConfigMap should fix this up.

https://github.com/submariner-io/submariner-operator/blob/31f861cfc341f981998077d7ed88a67ca920c411/controllers/servicediscovery/servicediscovery_controller.go#L354

https://github.com/submariner-io/submariner-operator/blob/31f861cfc341f981998077d7ed88a67ca920c411/controllers/servicediscovery/servicediscovery_controller.go#L366

https://github.com/submariner-io/submariner-operator/blob/31f861cfc341f981998077d7ed88a67ca920c411/controllers/servicediscovery/servicediscovery_controller.go#L396

Related: 
   AKS fix slated for #0.8.1: https://github.com/submariner-io/submariner/issues/1106  (resolving these two issues equals AKS support, or at least a platform we can start testing on.)

**Comment by nyechiel** [comment]
Thanks for testing on AKS and reporting this issue, @brandonwittwer.

**Comment by vthapar** [comment]
@brandonwittwer 
Question: Can we assume that `coredns-custom` configmap will always be present in AKS?

**Comment by mangelajo** [comment]
> @brandonwittwer
> Question: Can we assume that `coredns-custom` configmap will always be present in AKS?

May  be we can use that map if found?, or if we fail to modify the main one? (not sure if it fails, or if it's just overwritten).

May be the simplest strategy is use coredns-custom if it does exist.

**Comment by mangelajo** [comment]
Well according to https://docs.microsoft.com/en-us/azure/aks/coredns-custom#custom-forward-server we need to create it. I wonder if that works for other coredns's or if it's just microsoft AKS specific.

**Comment by vthapar** [comment]
> > @brandonwittwer
> > Question: Can we assume that `coredns-custom` configmap will always be present in AKS?
> 
> May be we can use that map if found?, or if we fail to modify the main one? (not sure if it fails, or if it's just overwritten).
> 
> May be the simplest strategy is use coredns-custom if it does exist.

I was thinking of using `coredns-custom` as an indicator of AKS. If it is not present by default, then we need some other means to detect AKS deployment, kinda similar to what we do with Openshift.
