### ISSUE TITLE
subctl - version mismatch notification

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner-operator#1048]
**What would you like to be added**:
A notification to the user that tells if `subctl` version supports the managed `submariner` version.

**Why is this needed**:
There might be a mismatch between the cli and the submariner API.

**Comment by nyechiel** [comment]
@SteveMattar are you actively working on this? I wanted to move this to the next release, but if you have a working code/was planning to push a PR - perhaps we can still fix this for 0.9. Thanks!

**Comment by SteveMattar** [comment]
@nyechiel I did not test my PR yet I will do it today.
Meanwhile I keep it draft.
