### ISSUE TITLE
allow subctl join to deploy with only service discovery

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1052]
**What would you like to be added**:
Allow subctl to join clusters for service discovery, but don't install the dataplane.

**Why is this needed**:
Some deployments use routed networks, where pods in one cluster can talk to pods & services on another cluster, in this case the dataplane part of submariner is not necessary, but the service discovery is still relevant.

**Comment by brandonwittwer** [comment]
This opens up so many doors for Azure kubernetes services (AKS).  The gateway wouldn't work when using azure CNI (vnets) as a pod and node network layer.  This allows azure to just "do" azure networking, and still allows k8s to resolve pods from across multiple clusters.  Bravo.  Excited to try this out.

**Comment by nyechiel** [comment]
Docs PR: https://github.com/submariner-io/submariner-website/issues/448

**Comment by brandonwittwer** [comment]
@mangelajo I believe this is the best place to mention the issues we discussed last week.  Deletion of the gateway CRDs and restarting the lighthouse pods from all joined clusters, as well as scaling down the submariner-operator.  These steps were required to enable headless services to resolve to some podIP, without these changes the pod host records work, but only the clusterID prefixed headless services would resolve some IP.

link to the slack thread: https://kubernetes.slack.com/archives/C010RJV694M/p1613499279124800

Summary:
I've got an install using --components service-discovery in AKS.  I've exported a headless service and it is transmitted over to the lighthouse dns server in cluster2, but when I look at the DNS records, there are
pod records {podhostname}.{otherClusterID}.{serviceName}.{namespace}.svc.clusterset.local
but not the headless service itself: {serviceName}.{namespace}.svc.clusterset.local
however there IS a response for {otherClusterID}.{serviceName}.{namespace}.svc.clusterset.local
documentation says that I should be able to access {serviceName}.{namespace}.svc.clusterset.local.

**Comment by mangelajo** [comment]
> @mangelajo I believe this is the best place to mention the issues we discussed last week. Deletion of the gateway CRDs and restarting the lighthouse pods from all joined clusters, as well as scaling down the submariner-operator. These steps were required to enable headless services to resolve to some podIP, without these changes the pod host records work, but only the clusterID prefixed headless services would resolve some IP.
> 
> link to the slack thread: https://kubernetes.slack.com/archives/C010RJV694M/p1613499279124800
> 
> Summary:
> I've got an install using --components service-discovery in AKS. I've exported a headless service and it is transmitted over to the lighthouse dns server in cluster2, but when I look at the DNS records, there are
> pod records {podhostname}.{otherClusterID}.{serviceName}.{namespace}.svc.clusterset.local
> but not the headless service itself: {serviceName}.{namespace}.svc.clusterset.local
> however there IS a response for {otherClusterID}.{serviceName}.{namespace}.svc.clusterset.local
> documentation says that I should be able to access {serviceName}.{namespace}.svc.clusterset.local.

@vthapar  ^

**Comment by vthapar** [comment]
@mangelajo @brandonwittwer We need https://github.com/submariner-io/submariner-operator/pull/1109 for  {serviceName}.{namespace}.svc.clusterset.local to work. Without that patch it wrongly assumes that submariner is installed and checks for gateway. podhostname+clusterId and clusterId work coz those two ignore gateway status check.
