### ISSUE TITLE
joining the clusterset using the devel build fails due to image and image version issues

### ISSUE THREAD

**Issue by brandonwittwer** [submariner-io/submariner-operator#1090]
**What happened**: installed subctl using the install script setting VERSION=devel.  cluster join fails with broken image because no repository nor image version are defaulted

**What you expected to happen**:
Installing from any named tag will appropriately set the repo and image version for the associated build.

**How to reproduce it (as minimally and precisely as possible)**:
installed subctl using the install script setting VERSION=devel. 

Deploying the broker like this:

`subctl deploy-broker --components service-discovery`

then joined the same cluster to the clusterset like this:

`subctl join broker-info.subm --clusterid cl2`

This created deployments for lighthouse-coredns and lighthouse-agent with an incorrectly set image property like this:
`
image: '/lighthouse-coredns:' 
`
and 
`
image:'/lighthouse-agent'
`
respectively.

**Workaround**:

On advice received, I added `--repository quay.io/submariner` to the join command.  This did SOMEWHAT help the two lighthouse deployments (both now were pulling images but with no version tag)  Adding --version=devel finally got things working.

**Environment**:
- Submariner version (use `subctl version`): devel
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mangelajo** [comment]
Thanks for reporting Brandon, I'll check what's wrong. Now I remember I added this code here: https://github.com/submariner-io/submariner-operator/pull/1087/files#diff-14e5c87c8aac2431cbe8c3060f2de407ee8ace4d8aa92f634e91d8160784714cR85
to handle that.

And I have memories about trying it out manually, but there's obviously some loose end yet.
