### ISSUE TITLE
Skip SubmarinerCRs install for lighthouse only deployments

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1098]
Now we have the option to install Lighthouse only without any Submariner components for use cases where user only wants Service Discovery from Lighthouse but not cross cluster connectivity from Submariner. But it still installs gateways, clusters and endpoint CRDs. This breaks logic in lighthouse that looks for gateways CR to see if submariner is providing connectivity or not.

**Comment by skitt** [comment]
Would Lighthouse still work if connectivity was added later? _I.e._ a cluster is deployed with only service discovery, so the Gateway CRD isn’t installed, and then connectivity is also set up using Submariner — at this point the Gateway CRD would be created, but would the Lighthouse gateway controller be restarted?
