### ISSUE TITLE
Subctl/Operator support for vxlan cable driver

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-operator#1101]
**What would you like to be added**:
subctl/operator needs to support a new cable driver.
**Why is this needed**:
As a part of  https://github.com/submariner-io/submariner/issues/674 new vxlan cable-driver will be supported. It should be possible to create a deployment with this driver.

Subctl : should accept a new option vxlan for cable driver.

Operatror : Should ensure that this is passed to g/w pod.

**Comment by tpantelis** [comment]
bump
