### ISSUE TITLE
Misleading Version output in the Gateway object

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-operator#1113]
**What happened**:

While testing with 0.8.1, I noticed that the Gateway object reports Version v0.8.0-22-gcf1490f. 

**What you expected to happen**:

The Version to indicate v0.8.1.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Submariner with v0.8.1 (latest stable release) via `subctl`
2. Join clusters 
3. Once the setup is converged, run `kubectl -n submariner-operator describe Gateway`

**Anything else we need to know?**:

```
[nyechiel@nyechiel-workstation OpenShiftAWS]$ kubectl -n submariner-operator describe Gateway
Name:         ip-10-0-67-228
Namespace:    submariner-operator
Labels:       <none>
Annotations:  update-timestamp: 1614265396
API Version:  submariner.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2021-02-25T14:45:42Z
  Generation:          207
  Managed Fields:
    API Version:  submariner.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:update-timestamp:
      f:status:
        .:
        f:connections:
        f:haStatus:
        f:localEndpoint:
          .:
          f:backend:
          f:cable_name:
          f:cluster_id:
          f:healthCheckIP:
          f:hostname:
          f:nat_enabled:
          f:private_ip:
          f:public_ip:
          f:subnets:
        f:statusFailure:
        f:version:
    Manager:         submariner-engine
    Operation:       Update
    Time:            2021-02-25T14:45:42Z
  Resource Version:  41315
  Self Link:         /apis/submariner.io/v1/namespaces/submariner-operator/gateways/ip-10-0-67-228
  UID:               6330b980-70d6-422f-83ee-2c14f1e20eb0
Status:
  Connections:
    Endpoint:
      Backend:          libreswan
      cable_name:       submariner-cable-cluster-a-10-0-50-129
      cluster_id:       cluster-a
      Health Check IP:  10.130.2.1
      Hostname:         ip-10-0-50-129
      nat_enabled:      true
      private_ip:       10.0.50.129
      public_ip:        3.141.20.94
      Subnets:
        172.30.0.0/16
        10.128.0.0/14
    Latency RTT:
      Average:       466.313µs
      Last:          440.079µs
      Max:           5.737396ms
      Min:           388.955µs
      Std Dev:       38.977µs
    Status:          connected
    Status Message:  
  Ha Status:         active
  Local Endpoint:
    Backend:          libreswan
    cable_name:       submariner-cable-cluster-b-10-0-67-228
    cluster_id:       cluster-b
    Health Check IP:  10.134.2.1
    Hostname:         ip-10-0-67-228
    nat_enabled:      true
    private_ip:       10.0.67.228
    public_ip:        3.20.206.55
    Subnets:
      172.31.0.0/16
      10.132.0.0/14
  Status Failure:  
  Version:         v0.8.0-22-gcf1490f
Events:            <none>


[nyechiel@nyechiel-workstation OpenShiftAWS]$ kubectl -n submariner-operator describe pods submariner-gateway-6l4n7 | grep Image
    Image:         quay.io/submariner/submariner:0.8.1
    Image ID:      quay.io/submariner/submariner@sha256:4b514a83c704b6785234c1b2bf8e76afae81dead0203ef7baae0fe219f60dba9



[nyechiel@nyechiel-workstation OpenShiftAWS]$ subctl show versions
Showing information for cluster "nyechiel-4.7-b":
COMPONENT                       REPOSITORY                                            VERSION         
submariner                      quay.io/submariner                                    0.8.1           
submariner-operator             quay.io/submariner                                    0.8.1           
service-discovery               quay.io/submariner                                    0.8.1    
```

**Environment**: 
- Submariner version (use `subctl version`): v0.8.1
- Kubernetes version (use `kubectl version`): v1.20.0+bd9e442
- Cloud provider or hardware configuration: OpenShift 4.7 on top of AWS

**Comment by nyechiel** [comment]
@SteveMattar @skitt Do you know from where do we get this "Version" field?

**Comment by skitt** [comment]
Unfortunately it’s generated during the build, and at that point we don’t have the tag yet (that comes later, when we release). I can’t remember the full reasoning for why we do it this way round, perhaps we can rebuild the image when we release...

**Comment by nyechiel** [comment]
> Unfortunately it’s generated during the build, and at that point we don’t have the tag yet (that comes later, when we release). I can’t remember the full reasoning for why we do it this way round, perhaps we can rebuild the image when we release...

@mkolesnik @mangelajo I am curious to hear your opinion on this

**Comment by SteveMattar** [comment]
@nyechiel https://github.com/submariner-io/submariner/blob/5ce1bb380d449e2c16affede3230119fbde4ff80/Makefile#L14
its an environment vairable and the value is calculated by shipyard. I think it was fixed last week @mkolesnik can you confirm?

**Comment by nyechiel** [comment]
> @nyechiel https://github.com/submariner-io/submariner/blob/5ce1bb380d449e2c16affede3230119fbde4ff80/Makefile#L14
> its an environment vairable and the value is calculated by shipyard. I think it was fixed last week @mkolesnik can you confirm?

@mkolesnik can you take a look at this please?

**Comment by mkolesnik** [comment]
Probably we should calculate the version specifically here taking into account the `subctl-devel` tag.
This shouldn't be part of Shipyard IMHO as it's too specific to this project.
