### ISSUE TITLE
Create ClusterRoles for accessing Globalnet CRDs

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#1114]
**What would you like to be added**:
As part of [Globalnet Enhancement](https://github.com/submariner-io/enhancements/pull/22), GlobalnetEgressIP will enable users to create EgressIPs for inter-cluster communication.

This request is to track the necessary Cluster roles in submariner-operator.

**Comment by tpantelis** [comment]
bump
