### ISSUE TITLE
Globalnet 2.0: Configuration parameters

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#1116]
**What would you like to be added**:
As part of [Globalnet Enhancement](https://github.com/submariner-io/enhancements/pull/22),
by default a configurable number of globalIPs will be allocated to the Cluster.
This request is to provide configuration parameter either via ConfigMap or Env variable to
specify
1. The number of default GlobalIPs that have to be allocated at cluster level.

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
It was decided not to provide such configuration parameters at this time. Will revisit if users ask for it.
