### ISSUE TITLE
Unable to deploy 0.9.0-m1/devel on OpenShift

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-operator#1124]
**What happened**:

When trying to deploy 0.9.0-m1 with OpenShift 4.7 and join clusters, only two pods are being created under the `submariner-operator` namespeace:

```
$ oc get pods -n submariner-operator
NAME                                          READY   STATUS    RESTARTS   AGE
submariner-lighthouse-agent-9db5b68c6-5c4nw   1/1     Running   0          14m
submariner-operator-58fcf65dfd-6ckfs          1/1     Running   0          15m 
```
Attached are the logs from the Operator pod.

**What you expected to happen**:

All pods to be running, and deployment to be successful.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy 0.9.0-m1 with the latest OpenShift version on AWS via `subctl` by following https://submariner.io/getting-started/quickstart/openshift/aws/

**Anything else we need to know?**:

This is a non-Globalnet deployment with OpenShiftSDN.

**Environment**:
- Submariner version (use `subctl version`): 0.9.0-m1
- Kubernetes version (use `kubectl version`): v1.20.0+bd9e442
- Cloud provider or hardware configuration: OpenShift on AWS (IPI)

**Comment by nyechiel** [comment]
[log.txt](https://github.com/submariner-io/submariner-operator/files/6074230/log.txt)

**Comment by nyechiel** [comment]
> [log.txt](https://github.com/submariner-io/submariner-operator/files/6074230/log.txt)

I also noticed that L4 in this log says `2021-03-03T06:54:49.839Z	INFO	cmd	Submariner operator version: subctl-devel` while this is a 0.9.0-m1 deployment:
```

$ oc describe pods -n submariner-operator submariner-operator-58fcf65dfd-6ckfs | grep Image
    Image:         quay.io/submariner/submariner-operator:0.9.0-m1
    Image ID:      quay.io/submariner/submariner-operator@sha256:5ded2e8a225f641305be5dfb19612854411b7ad667205816c799d65648c2dc9a
```

**Comment by skitt** [comment]
This appears to be a permissions issue:

```
ERROR	controller-runtime.controller	Reconciler error	{"controller": "broker", "name": "submariner-broker", "namespace": "submariner-operator", "error": "configmaps is forbidden: User \"system:serviceaccount:submariner-operator:submariner-operator\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"submariner-k8s-broker\""}
```

**Comment by skitt** [comment]
Ahah! We’re missing “create” on the `ClusterRole` for `configmaps`.

**Comment by nyechiel** [comment]
@skitt  I tested this with OCP 4.7 using `devel` and I see the same problem and the same error in the log. IIUC, we also need https://github.com/submariner-io/submariner/pull/1009 to fully address this?

**Comment by nyechiel** [comment]
Note: I can confirm that Submariner v0.8 deploys successfully on OCP 4.7, so this is specific to `0.9.0-m1` or `devel`.

@skitt let's use this Issue to track all other related failures/errors.

**Comment by SteveMattar** [comment]
So it appears the SA account name is always null when trying to update the SCC privileged
```
$ oc describe scc/privilege
Users:					system:admin,system:serviceaccount:openshift-infra:build-controller,system:serviceaccount:submariner-operator:
```
`system:serviceaccount:submariner-operator:<EMPTY>` 
The problem is somewhere here `GetObjectName` when we try to parse the SA name from that embedded yaml file
