### ISSUE TITLE
Switch from pkg/client/fake to pkg/envtest

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1236]
The controller runtime’s fake client is deprecated and should be replaced by https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest

**Comment by tpantelis** [comment]
The fake client was subsequently [undeprecated](https://github.com/kubernetes-sigs/controller-runtime/issues/768) due to overwhelming feedback and it looks like it will remain long term.

**Comment by skitt** [comment]
Cool, less work for us!
