### ISSUE TITLE
Investigate privilege settings for the Globalnet agent

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1241]
The Globalnet pods are currently configured with all capabilities, privileged execution, as root with read-write root, on the host network. Some of these settings can probably be tightened; this needs to be investigated and the results at least documented (especially if they don’t lead to configuration changes).

**Comment by dfarrell07** [comment]
This was considered as a task for students but they didn't take it up, moving back to something we're working on.
