### ISSUE TITLE
Add log file to include additional info of note during the collection process

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1255]
Log details about the resources not gathered during `subctl gather` along with the reason

Subtask of https://github.com/submariner-io/submariner-operator/issues/1125

**Comment by mangelajo** [comment]
I think it would be cool to make something like an HTML report, which would be included as one file with the gather:

   * subctl show all equivalent
   * the results of validation...
   * other ideas...

**Comment by Jaanki** [comment]
subm gateway node name/id

**Comment by tpantelis** [comment]
Subctl version: 
Submariner version:
Kubernetes version: (if we can)
CNI plugin:

Endpoints in cluster X:

<table>
<th>NAME</th>   
<th>CREATION TIME</th>   
<th>CLUSTER ID</th>  
<th>CABLE DRIVER</th>
</table>

Gateways in cluster X:

<table>
<th>NODE</th>   
<th>HA STATUS</th>   
<th>SUMMARY</th>  
</table>

Gateway pods in cluster X:

<table>
<th>NAME</th>   
<th>PHASE</th>   
<th>...</th>  
</table>

Route Agent pods in cluster X:

<table>
<th>NAME</th>   
<th>PHASE</th>   
<th>...</th>  
</table>

...

**Comment by Jaanki** [comment]
Capture the kernel version (uname -a) from https://github.com/submariner-io/submariner-operator/issues/1322

**Comment by vthapar** [comment]
Have we settled on the report layout and format? A doc with mockup of what final report should look like would be a better way to review this.

**Comment by vthapar** [comment]
> Subctl version:
> Submariner version:
> Kubernetes version: (if we can)
> CNI plugin:
> 
> Endpoints in cluster X:
> 
> --snip--

Why not add option to `subctl show` to generate an html report instead of dumping output on screen? DEfault would be output to screen. We can write the code so that format of report generated is similar to one we'll use for `gather`.
