### ISSUE TITLE
make build-subctl doesn’t run the embedded generator

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#126]
rm pkg/subctl/operator/install/embeddedyamls/yamls.go
    make build-subctl

fails, it shouldn’t.

**Comment by skitt** [comment]
cc @Jaanki

**Comment by mangelajo** [comment]
@skitt I believe you fixed this in one of your last refactors/PRs, am I right?

**Comment by mangelajo** [comment]
please close if it was really fixed.

**Comment by skitt** [comment]
No, it’s not fixed yet. (The workaround is to run `make bin/subctl` which does the right thing.)

**Comment by mangelajo** [comment]
Ah, but I think, the right way should be make bin/subctl, which handles the dependency logic, may be we should remove build-subctl from the runnable scripts through make, I'd do that.

**Comment by manosnoam** [comment]
Also we should mention in Readme that it is required to get vendor modules before the build:
```
GO111MODULE="on" go mod vendor
make bin/subctl
```

**Comment by skitt** [comment]
> Also we should mention in Readme that it is required to get vendor modules before the build:
> 
> ```
> GO111MODULE="on" go mod vendor
> make bin/subctl
> ```

No need, that was fixed in #174.
