### ISSUE TITLE
After uninstalling the submariner-operator, the Submariner CRDs are still remained

### ISSUE THREAD

**Issue by skeeey** [submariner-io/submariner-operator#1270]
**What happened**:
I installed the submariner-operator from OperatorHub on OCP, after I uninstalled the submariner-operator, the submariner crds are still remained

```
kubectl get crds | grep submariner
clusters.submariner.io                                      2021-04-21T05:28:09Z
endpoints.submariner.io                                     2021-04-21T05:28:09Z
gateways.submariner.io                                      2021-04-21T05:28:09Z
servicediscoveries.submariner.io                            2021-04-21T05:28:09Z
serviceexports.lighthouse.submariner.io                     2021-04-21T05:28:09Z
serviceimports.lighthouse.submariner.io                     2021-04-21T05:28:09Z
submariners.submariner.io                                   2021-04-21T05:27:52Z
```

**What you expected to happen**:
The  submariner crds can be removed after I uninstalled the  submariner-operator

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the submariner-operator from OperatorHub on OCP
2. Uninstall the submariner-operator from OperatorHub
3. Check the submariner crds

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.8
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by itdove** [comment]
Please also add E2E tests to make sure that is verified.

**Comment by nyechiel** [comment]
Reopening. @skitt is this something you can look at?

**Comment by sridhargaddam** [comment]
Maybe we can handle this as part of unjoin/cleanup work - https://github.com/submariner-io/enhancements/issues/50 CC: @tpantelis
