### ISSUE TITLE
subctl benchmark throughput not working in Openhift 4.6 with globalnet

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-operator#1274]
**What happened**:
subctl benchmark throughput not working in Openhift 4.6 with globalnet

[asuryana@localhost testday]$ subctl benchmark throughput asuryana-cluster-a/auth/kubeconfig asuryana-cluster-b/auth/kubeconfig --verbose
Performing throughput tests
Creating kubernetes clients
Setting new cluster ID "cluster-a", previous cluster ID was "asuryana-cluster-a"
Setting new cluster ID "cluster-b", previous cluster ID was "asuryana-cluster-b"
Creating lighthouse clients
Creating submariner clients
Creating namespace objects with basename "throughput"
Generated namespace "e2e-tests-throughput-gbr2v" in cluster "cluster-a" to execute the tests in
Creating namespace "e2e-tests-throughput-gbr2v" in cluster "cluster-b"
Performing throughput tests from Gateway pod on cluster "cluster-a" to Gateway pod on cluster "cluster-b"
Creating a Nettest Server Pod on "cluster-b"
Nettest Server Pod "nettest-server-podcmknw" was created on node "ip-10-0-49-192.us-east-2.compute.internal"

Pointing a ClusterIP service to the listener pod in cluster "cluster-b"
Deleting namespace "e2e-tests-throughput-gbr2v" on cluster "cluster-a"
Deleting namespace "e2e-tests-throughput-gbr2v" on cluster "cluster-b"
panic: Failed to getsubmariner.io/globalIp annotation for service test-svc-nettest-server-pod. Service "test-svc-nettest-server-pod" does not have annotation "submariner.io/globalIp" yet
Unexpected error:
    <*errors.errorString | 0xc0003d21a0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/benchmark.StartThroughputTests.func1(0xc0001b06e0, 0x15a, 0xc0009103d0, 0x1, 0x1)
	github.com/submariner-io/submariner-operator/pkg/subctl/benchmark/throughput.go:38 +0x6b
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc00059f1c0, 0x19ba860, 0x242f700, 0x0, 0xc000712340, 0x1, 0x1, 0xc000712350)
	github.com/onsi/gomega@v1.11.0/internal/assertion/assertion.go:79 +0x216
github.com/onsi/gomega/internal/assertion.(*Assertion).NotTo(0xc00059f1c0, 0x19ba860, 0x242f700, 0xc000712340, 0x1, 0x1, 0xc000792000)
	github.com/onsi/gomega@v1.11.0/internal/assertion/assertion.go:48 +0xc7
github.com/submariner-io/shipyard/test/e2e/framework.AwaitUntil(0xc0008f6000, 0x4c, 0xc0005c5af0, 0xc0005c5ac8, 0x16, 0x17cf06d)
	github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/framework.go:488 +0x1c6
github.com/submariner-io/shipyard/test/e2e/framework.(*Framework).AwaitUntilAnnotationOnService(0xc000181450, 0x1, 0x17cd855, 0x16, 0xc000584c00, 0x1b, 0xc000584c20, 0x1a, 0x0)
	github.com/submariner-io/shipyard@v0.9.0-rc0/test/e2e/framework/services.go:111 +0x166
github.com/submariner-io/submariner-operator/pkg/subctl/benchmark.runThroughputTest(0xc000181450, 0x0, 0x1, 0x1, 0x1)
	github.com/submariner-io/submariner-operator/pkg/subctl/benchmark/throughput.go:129 +0x513
github.com/submariner-io/submariner-operator/pkg/subctl/benchmark.StartThroughputTests(0x1993000)
	github.com/submariner-io/submariner-operator/pkg/subctl/benchmark/throughput.go:56 +0x225
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.testThroughput(0x23d4320, 0xc000695aa0, 0x2, 0x3)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/benchmark.go:86 +0x5d
github.com/spf13/cobra.(*Command).execute(0x23d4320, 0xc000695a40, 0x3, 0x3, 0x23d4320, 0xc000695a40)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x23d52e0, 0x445bca, 0x22dc9a0, 0xc00006e778)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:56
main.main()
	command-line-arguments/main.go:27 +0x32

**What you expected to happen**:

The throughput should return the measurements.

**How to reproduce it (as minimally and precisely as possible)**:
Run  `subctl benchmark throughput asuryana-cluster-a/auth/kubeconfig asuryana-cluster-b/auth/kubeconfig --verbose` in Openshift 4.6 with globalnet enabled.

**Anything else we need to know?**:

**Environment**: Openshift 4.6 
- Submariner version (use `subctl version`): subctl 0.9.0.rc0
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Jaanki** [comment]
same in KIND setup for Globalnet+LIbreswan
