### ISSUE TITLE
 subctl validate firewall tunnel   does not work on an HA setup with globalnet enbled

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-operator#1277]
**What happened**:
When subctl validate  in HA setup with globalnet enabled , it fails
```
 subctl validate firewall tunnel  asuryana-cluster-a/auth/kubeconfig asuryana-cluster-b/auth/kubeconfig
 ⚠ Validating if tunnels can be setup on Gateway node of cluster "cluster-a". 
 ⚠ Gateway object on remote cluster does not have connection info to local cluster.
```
**What you expected to happen**:
Subctl validate should work

**How to reproduce it (as minimally and precisely as possible)**:
Run `subctl validate firewall tunnel  asuryana-cluster-a/auth/kubeconfig asuryana-cluster-b/auth/kubeconfig` in an HA setup.
**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): 0.9.0rc0
- Kubernetes version (use `kubectl version`): Openshift 4.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpantelis** [comment]
It looks like this code needs to find the active Gateway:

```
func getGatewayIP(remoteCfg *rest.Config, localClusterID string) string {
	gateways := getGatewaysResource(remoteCfg)
         ...
        for i, _ := range gateways.Items {
            gw := &gateways.Items[i]
            if gw.Status.HAStatus != subv1.HAStatusActive {
                continue
            }

	    for _, conn := range gw.Status.Connections {
	        if conn.Endpoint.ClusterID == localClusterID {
                     return conn.UsingIP
		}
	    }
        }
	return ""
}


```
