### ISSUE TITLE
weird error message when re-installing subm on a cluster

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#128]
When Subm is installed on a cluster where it is already installed, the error message is a bit weird and not descriptive.

* Deploying Submariner
panic: submariners.submariner.io "submariner" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/operator/deploy.Ensure(0xc0004ae000, 0x138f9ba, 0x13, 0x138e7b4, 0x12, 0x137f952, 0x5, 0xc0003b03d0, 0x7, 0xc0006aca10, ...)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/operator/deploy/ensure.go:97 +0xb96
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc0003e6be0)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:128 +0x3ae
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x2096560, 0xc0003cd650, 0x1, 0x3)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:60 +0x14a
github.com/spf13/cobra.(*Command).execute(0x2096560, 0xc0003cd5f0, 0x3, 0x3, 0x2096560, 0xc0003cd5f0)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x20967e0, 0x1118aba, 0xc000335f88, 0xc00004c118)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:35
main.main()
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:6 +0x2f

**Comment by mangelajo** [comment]
@Jaanki I think this was fixed on master, can you re-try with a freshly built subctl and tell me if it's still happening , and otherwise close it?

**Comment by Jaanki** [comment]
With the latest subctl release, I don't see this error. On redeploying subm via subctl join, the whole process repeats. However, I don't see any subm pods getting restarted. So that's also fine.

What would be nice to have is for join to first check if subm is deployed. If yes, say it is already deployed. If no, proceed with deployment.

**Comment by mangelajo** [comment]
Yeah, the non-restart is a different issue, @tpantelis is looking at that.
