### ISSUE TITLE
subctl gather failes on gathering connectivity resources

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner-operator#1286]
**What happened**:
 ✗ Error running "ip route show table 150" on pod "submariner-gateway-xzbg2": command terminated with exit code 2
 ✗ Error running "ipsec --trafficstatus" on pod "submariner-gateway-xzbg2": command terminated with exit code 33
 ✗ Error running "ipsec status" on pod "submariner-gateway-xzbg2": command terminated with exit code 33

**What you expected to happen**:
subctl gather should be able to successfully run ip and ipsec commands

**How to reproduce it (as minimally and precisely as possible)**:
subctl gather --modul connectivity

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): subctl 0.9.0.rc0
- Kubernetes version (use `kubectl version`): OCP 4.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vthapar** [comment]
Is this the HA Gateway setup? These commands will only run on active gateway and currently we're running them on all gateways. In case of non active, we should just ignore error and return.
