### ISSUE TITLE
Document when/how to use subctl verify vs. show

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#1301]
For users this might seems confusing, when to call `subctl verify ...`, `subctl validate ...` or `subctl show ...`.
The naming conventions of "validate" and "verify" are alike, and may cause confusion in the future, or be used for similar purpose.

In addition, `validate` and `show` does some similar actions - showing if Submariner installation/components are all set.
For example: `subctl show connections` and `subctl validate connections` display gateways status.

The [subctl documentation](https://submariner.io/operations/deployment/subctl/) describes each command in details.
However, when user is facing an issue, or want to check the status - what should we recommend to execute ?

**What would you like to be added**:

1) Rename any of the commands, for example:
validate --> diagnose
verify --> test

2) Merge the commands into one command, and add sub-commands, for example:
verify connectivity, verify configuration, verify all

3) Remove similar commands, for example:
"show connections" or "validate connections", do we need both ?

**Why is this needed**:
Less is more.

**Comment by nyechiel** [comment]
Note: `validate` was replaced with `diagnose` -- https://github.com/submariner-io/submariner-operator/pull/1309

There is still room for improvement; we should review all existing commands and see how we can improve the overall UX.

**Comment by nyechiel** [comment]
Other idea is to "link" between the commands, for e.g if a `show` command suggests something is wrong, instruct the user to use `diagnose`.
