### ISSUE TITLE
subctl diagnose to return relevant exit code on Submariner failures

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#1310]
`subctl diagnose` prints "Status.Error/Warnings" and exit normally, even if there's a connection failure.
This is a different response than already implemented by `subctl show` - that returns bad exit code on connection failures.

**What would you like to be added**:
Add relevant exit code for subctl diagnose.

**Why is this needed**:
common exit codes for subctl commands

**Comment by nyechiel** [comment]
(removing from the 0.9 board as this is already being tracked via the linked Issue)
