### ISSUE TITLE
Inter-cluster benchmark throughput fails with globalnet

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-operator#1315]
**What happened**:

https://github.com/submariner-io/submariner-operator/pull/1314/checks?check_run_id=2467139879

It succeeds for Gateway to Gateway but fails for Non-Gateway to Non-Gateway - the client pod doesn’t complete.

**Comment by sridhargaddam** [comment]
Fix is included as part of following PR - https://github.com/submariner-io/submariner-operator/pull/1314
