### ISSUE TITLE
Support joining multiple clusters with a single subctl join command

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#1332]
**What would you like to be added**:
Currently `subctl join` allows to join one cluster at a time. With `--kubecontexts` flag now available, it should support joining multiple clusters with a single `join` command.

**Why is this needed**:
This will improve user experience when trying to join multiple clusters.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
Talking about this on the Issue scrub, we're not sure users will actually want to join multiple clusters at once (where subctl-testing does make sense for all clusters). It will also be complex to take the different config for the various clusters, will make the flags more complex. Overall, it seems like the value is lower than the cost. The recommendation is to use a simple shell loop for the simple case here.
