### ISSUE TITLE
`--kubecontext` in any `subctl` command doesn't work

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1351]
`kubecontexts` was added in 0.9 but it broke `kubecontext` for any other command that uses it.

Specifically, these lines [1] can't work because at this pint in the code the flags are just being initialized and have no values yet.

On a grander scheme, I think `kubecontexts` is wrong and if users want to loop over several contexts, they can call the command several time with a different `kubecontext` each time.

For commands that require two contexts (or allow 1 or 2 contexts) an additional flag can be used which allows to specify the additional context explicitly and clearly.

Hence I propose:
1. Remove the `kubecontexts` flag
2. Fix back `kubecontext` to working
3. For command requiring another context (currently only `verify` AFAICT), add a flag `othercontext` to specify the other context. This flag can be verified to be set and proper, and the users can be warned appropriately if it's unset.
4. As per `kubectl` and other CLI tools, if no context is specified we should honor the `current-context` as set in the kubeconfig file.

[1] https://github.com/submariner-io/submariner-operator/pull/1223/files#diff-8a58275c37bca775e6338952d361c5a6f84bfc2956093290bb661ed575c7c9d0R64-R67

**Comment by tpantelis** [comment]
I think it's useful to have the various commands operate on multiple contexts.

**Comment by vthapar** [comment]
Why need to remove `--kubecontexts` for commands that benefit from it?
