### ISSUE TITLE
Update metrics setup to match current Operator SDK practice

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1415]
Since version 1.0.0 of the SDK, metrics are set up using kustomize and no longer with in-project code and the `pkg/metrics` package. We should follow suit: https://sdk.operatorframework.io/docs/building-operators/golang/migration/#export-metrics

**Comment by nyechiel** [comment]
@maayanf24 is this something you can look at?

**Comment by nyechiel** [comment]
@skitt is it still relevant?

**Comment by Jaanki** [comment]
No. It's done as part of operator-ask upgrade epic.

**Comment by Jaanki** [comment]
@skitt and I discussed this yesterday.
