### ISSUE TITLE
subctl verify show --kubeconfig as a flag

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#1448]
**What happened**:
```
./bin/subctl verify --kubeconfig output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster1
Error: two kubecontexts must be specified
Usage:
  subctl verify --kubecontexts <kubeContext1>,<kubeContext2> [flags]

Flags:
      --connection-attempts uint      maximum number of connection attempts (default 2)
      --connection-timeout uint       timeout in seconds per connection attempt (default 60)
      --disruptive-tests              enable disruptive verifications like gateway-failover
  -h, --help                          help for verify
      --kubeconfig string             absolute path(s) to the kubeconfig file(s)
      --kubecontexts strings          comma separated list of kubeconfig contexts to use, can be specified multiple times.
                                      If none specified, all contexts referenced by kubeconfig are used
      --only string                   comma separated verifications to be performed (default "connectivity,service-discovery,gateway-failover")
      --operation-timeout uint        operation timeout for K8s API calls (default 240)
      --report-dir string             XML report directory (default ".")
      --submariner-namespace string   namespace in which submariner is deployed (default "submariner-operator")
      --verbose                       produce verbose logs during connectivity verification

Error:  two kubecontexts must be specified
```

**What you expected to happen**:
1. Error message should be: `Error: unknown flag: --kubeconfig`
2. `--kubeconfig` should not be in command flags list

**How to reproduce it (as minimally and precisely as possible)**:
`./bin/subctl verify --kubeconfig output/kubeconfigs/kind-config-cluster2 output/kubeconfigs/kind-config-cluster1`

**Anything else we need to know?**:

**Environment**:
subctl version: devel

**Comment by maayanf24** [comment]
`subctl verify` older version was like this:
`subctl verify kubeconfig-a kubeconfig-b`
the help flag `--kubeconfig` is misleading here

**Comment by maayanf24** [comment]
another issue related to this - the current documentation for using OpenShift on AWS is not working
https://submariner.io/getting-started/quickstart/openshift/aws/

**Comment by skitt** [comment]
The idea here is that `--kubeconfig` can be used, instead of `KUBECONFIG`, to specify the configuration files to use. Then the contexts are specified in relation to that.

So `--kubeconfig` has its place IMO, and shouldn’t be removed.

Regarding the documentation for OCP on AWS, the configuration files need to be edited so that a merged configuration works.

**Comment by skitt** [comment]
I’ve filed https://github.com/submariner-io/submariner-website/issues/546 for the documentation.

**Comment by maayanf24** [comment]
> The idea here is that `--kubeconfig` can be used, instead of `KUBECONFIG`, to specify the configuration files to use. Then the contexts are specified in relation to that.
> 
> So `--kubeconfig` has its place IMO, and shouldn’t be removed.
> 
> Regarding the documentation for OCP on AWS, the configuration files need to be edited so that a merged configuration works.

I don't mind keeping `--kubeconfig` but currently it will accept only one file, which cause the command to failed on validation.
Maybe changing to `--kubeconfigs` will be more clear that two files are must

**Comment by skitt** [comment]
> > The idea here is that `--kubeconfig` can be used, instead of `KUBECONFIG`, to specify the configuration files to use. Then the contexts are specified in relation to that.
> > So `--kubeconfig` has its place IMO, and shouldn’t be removed.
> > Regarding the documentation for OCP on AWS, the configuration files need to be edited so that a merged configuration works.
> 
> I don't mind keeping `--kubeconfig` but currently it will accept only one file, which cause the command to failed on validation.
> Maybe changing to `--kubeconfigs` will be more clear that two files are must

How so? A single kubeconfig can contain multiple contexts...

**Comment by skitt** [comment]
And I think `--kubeconfig` can be given multiple files, exactly in the same way as `KUBECONFIG`.

**Comment by maayanf24** [comment]
I intended to write that currently the `verify` will not accept `--kubeconfig` as a flag unless `--kubecontexts` args are supplied,
But the help string suggested that `--kubecontexts` is optional.
`--kubecontexts strings          comma separated list of kubeconfig contexts to use, can be specified multiple times.
                                      If none specified, all contexts referenced by kubeconfig are used
`

**Comment by skitt** [comment]
Right, so the real bug is that the help text for `--kubecontexts` is incorrect for `verify`.
