### ISSUE TITLE
`subctl benchmark throughput` appears to be stuck

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1487]
When running `subctl benchmark throughput` it appears as if it's stuck when it's running the test.

```bash
[root@483221d9c954 submariner]# subctl benchmark throughput --kubecontexts cluster1,cluster2
Performing throughput tests from Gateway pod on cluster "cluster1" to Gateway pod on cluster "cluster2"
                                                ... TIME PASSES ...
its/sec  161   53.0 KBytes       
[ 17]   7.00-8.00   sec  12.2 MBytes   102 Mbits/sec  173   60.8 KBytes       
[ 19]   7.00-8.00   sec  12.1 MBytes   101 Mbits/sec  209   45.3 KBytes       
[ 21]   7.00-8.00   sec  11.9 MBytes   100 Mbits/sec  105   58.2 KBytes       

```

Form a UX perspective, it would be better to print out "spinner messages" indicating something is being done (and it would be in-
line with other subctl commands).
For example, describe pods being created, iperf running, etc.

Optionally, we can provide a `--quiet` flag to surpress this output (for better consumption in scripts and such).

**Comment by tpantelis** [comment]
> For example, describe pods being created, iperf running, etc.
> 
> Optionally, we can provide a `--quiet` flag to surpress this output (for better consumption in scripts and such).

It has a `--verbose` flag.

**Comment by mkolesnik** [comment]
> It has a `--verbose` flag.

Haven't tried it, but if it prints out info along the way then it would be a better UX and should be the default.

`subctl` is targeted at human users (and then scripts) so from a UX perspective we should focus on the human user, IMHO.

**Comment by Jaanki** [comment]
> Haven't tried it, but if it prints out info along the way then it would be a better UX and should be the default.

Yes it does  and like other commands, `--verbose` is not default. 
`Performing throughput tests from Gateway pod on cluster "cluster1" to Gateway pod on cluster "cluster2"` is enough indication IMO.

> 
> `subctl` is targeted at human users (and then scripts) so from a UX perspective we should focus on the human user, IMHO.
