### ISSUE TITLE
Upgrade 0.9.1 -> 0.10.0-rc0 not working well on wireguard+kind

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1491]
**What happened**:
Using a kind based environment, first having installed Submariner v0.9.1 and then upgraded to 0.10.0-rc0, verification is failing:
[verify.txt](https://github.com/submariner-io/submariner-operator/files/6823211/verify.txt)

**What you expected to happen**:
`subctl verify` should succeed

**How to reproduce it (as minimally and precisely as possible)**:
```bash
make clusters
curl -Ls https://get.submariner.io | VERSION=0.9.1 bash
subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1
subctl join --kubecontext cluster1 --cable-driver wireguard broker-info.subm
subctl join --kubecontext cluster2 --cable-driver wireguard broker-info.subm
curl -Ls https://get.submariner.io | VERSION=0.10.0-rc0 bash
subctl join --kubecontext cluster1 --cable-driver wireguard broker-info.subm
subctl join --kubecontext cluster2 --cable-driver wireguard broker-info.subm
subctl verify
```

**Anything else we need to know?**:
`subctl verify` on vanilla v0.10.0-rc0 with wireguard+kind works fine

**Environment**:
- Submariner version (use `subctl version`): v0.10.0-rc0
- Kubernetes version (use `kubectl version`): v1.20.7
- Diagnose information (use `subctl diagnose all`): Passed
- Gather information (use `subctl gather`) 
[gather.tar.gz](https://github.com/submariner-io/submariner-operator/files/6823252/gather.tar.gz)

- Cloud provider or hardware configuration: kind
- OS (e.g `cat /etc/os-release`): F34
- Kernel (e.g `uname -a`): Linux 483221d9c954 5.6.13-100.fc30.x86_64
- Install tools:
- Others:

**Comment by nyechiel** [comment]
Closing old bugs. Please reopen if this is still relevant.
