### ISSUE TITLE
service discovery configuration fails for microshift

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1502]
**What happened**:
The operator fails to configure CoreDNS in microshift [1].

This is because microshift uses the same namespaces & core config files as in openshift, but it doesn't enable the DNS operator, so no DNS crds to configure the forwarding to lighthouse. It needs to be manually done inside the CoreDNS config (at least for now) if the DNS crd isn't there.

[1] https://github.com/redhat-et/microshift

**What you expected to happen**:

Service discovery working on microshift, coredns properly configured.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

**Comment by nyechiel** [comment]
@mangelajo is this still relevant?

**Comment by nyechiel** [comment]
@mangelajo do you have any cycles to look into this?

**Comment by nyechiel** [comment]
@mangelajo Do you know if this one is still relevant? any chance you can look into it?

**Comment by dfarrell07** [comment]
We don't know if this is still an issue and we don't currently test with Microshift. If we start working with it, we can open a new issue with more details about the required changes on our end.
