### ISSUE TITLE
Not all metrics are exported

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1509]
**What happened**:
Not all metrics are exported in Submariner. Only metrics exported are
- submariner_gateways
- submariner_gateway_creation_timestamp
- submariner_requested_connections
as seen in the attached log.
[clusterb_metrics.log](https://github.com/submariner-io/submariner-operator/files/6868113/clusterb_metrics.log)

Same behavior is seen for cluster-a

**What you expected to happen**:
All metrics to be exported

**How to reproduce it (as minimally and precisely as possible)**:

- Create 2 AWS clusters and connect them using Submariner
- kubectl --context=cluster-b port-forward service/submariner-operator-metrics 9090:8383 --namespace=submariner-operator
- http://localhost:9090/metrics 

**Anything else we need to know?**:
However, on logging into the AWS clusters and then checking the metrics from the UI, all metrics (listed in Submariner website, except for Globalnet and service discovery) can be queried.

**Environment**:
- Diagnose information (use `subctl diagnose all`): 
[subctl_diagnose_both_clusters.log](https://github.com/submariner-io/submariner-operator/files/6868151/subctl_diagnose_both_clusters.log)

- Gather information (use `subctl gather`): 
[clustera_gather.zip](https://github.com/submariner-io/submariner-operator/files/6868534/clustera_gather.zip)
[clusterb_gather.zip](https://github.com/submariner-io/submariner-operator/files/6868535/clusterb_gather.zip)

- Cloud provider or hardware configuration: AWS
- Install tools:
- Others:

**Comment by maayanf24** [comment]
@Jaanki - 
In Submariner, the metrics are exposed from several services.
From your test, you only check for the metrics exposed by `submariner-operator-metrics`
In the same way, you can find more metrics exposed from: `submariner-gateway-metrics`  and `submariner-lighthouse-agent-metrics`

A better option to view all exported metrics will be:
`kubectl --context=cluster-b port-forward service/prometheus-operated 9090 &` and then access from:
http://localhost:9090/graph

**Comment by nyechiel** [comment]
Also, assuming this was tested with OpenShift, you don't actually need to use something like `port-forward`. You can simply use the Console which has a built-in integration with Prometheus
