### ISSUE TITLE
submariner-operator pod always restarts

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1510]
**What happened**:
submariner-operator pod is always restarted. I have observed this behavior in multiple AWS and KIND setups. This can also be observed in CI with so many of flaky tests failing with `cat: /tmp/subctl-gather-output/cluster1_submariner-operator-56f895dd55-slddv.log.prev: No such file or directory
make: *** [Makefile:94: e2e] Error 1` as captured in [v0.10.0-rc0 test-day spreadsheet](https://docs.google.com/spreadsheets/d/1sYoFPgb_z6JXixUUUb_la3Yh6RKLFj5923FzWvX4yjY/edit#gid=175812790)

**What you expected to happen**:
submariner-operator pod should not restart

**How to reproduce it (as minimally and precisely as possible)**:
Set up a cluster in AWS/KIND and run `subctl gather` after some time.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
[subctl_diagnose_both_clusters.log](https://github.com/submariner-io/submariner-operator/files/6868622/subctl_diagnose_both_clusters.log)

- Gather information (use `subctl gather`):
[clustera_gather.zip](https://github.com/submariner-io/submariner-operator/files/6868623/clustera_gather.zip)
[clusterb_gather.zip](https://github.com/submariner-io/submariner-operator/files/6868624/clusterb_gather.zip)

- Cloud provider or hardware configuration: AWS/KIND
- Install tools:
- Others:

**Comment by mangelajo** [comment]
```
E0723 10:12:53.071013       1 main.go:205] cmd "msg"="Manager exited non-zero" "error"="no matches for kind \"Gateway\" in version \"submariner.io/v1\""  
```
May be the Gateway CRD is still not ready? ^

**Comment by mangelajo** [comment]
Seems like a non severe issue, (not a blocker definitely) but something to look at. May be we should add retries to that, or have something that waits when the CRDs have been installed until they go ready?

**Comment by nyechiel** [comment]
Closing old issues. Please re-open if this is still relevant.
