### ISSUE TITLE
Include nodeName in the subctl gather summary page

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#1555]
**What would you like to be added**:
When subctl gather is used to collect debugging info from the cluster, it also generates a summary.html file that includes hyperlinks to the log files. As part of the Summary, it would be helpful if we include the NodeName where the Pods were running. This will help us in scenarios where we want to look at the logs of route-agent pod that is running on the Gateway node. 

Currently, it includes the following fields.
Pod name | Namespace | Pod state | Restart count | Log file(s)

**Comment by dfarrell07** [comment]
This was closed by https://github.com/submariner-io/submariner-operator/pull/1624.
