### ISSUE TITLE
The operator verify script forces using SA per connected cluster

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner-operator#1608]
**What happened**:

The bundle creates all the resources during deployment and before the joining the clusters, therefore the process cannot predict
the creation of a SA per connected cluster unlike the subctl join command which can create it during runtime.
Therefore the `lib_operator_verify_subm.sh` script fails.

**What you expected to happen**:
This operation should be handled by the operator.

**How to reproduce it (as minimally and precisely as possible)**:
* Uncomment [L201](https://github.com/submariner-io/submariner-operator/blob/d0d0ae38e1e68426442d266ad58828583e0a0263/scripts/kind-e2e/lib_operator_verify_subm.sh#L201).
* Run `make e2e using=olm,lighthouse REPO=localhost:5000 IMG=localhost:5000/submariner-operator:local`.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by sridhargaddam** [comment]
Marking it low priority after talking to @SteveMattar

**Comment by dfarrell07** [comment]
Wondering if newer versions of the Operator SDK can build bundles that use SA per connected cluster, as this seems like the behavior we actually want. - PR scrub

**Comment by maayanf24** [comment]
This has been discussed on the issue scrub meeting and decided to close for now.
If this will become a priority it can be reopened
https://github.com/submariner-io/enhancements/issues/81
