### ISSUE TITLE
subctl diagnose firewall intra-cluster - failed VXLAN checks

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#1614]
**What happened**:
Running "subctl diagnose firewall intra-cluster kubeconfig1 kubeconfig2" returns that all VXLAN checks have failed, while * all E2E did pass * on this environment, so there's seems to be wrong diagnose:

$ subctl diagnose firewall intra-cluster  /mnt/skynet-data/skynet-env-1/nmanos-aws-devcluster-a/auth/kubeconfig  /mnt/skynet-data/skynet-env-1/nmanos-aws-devcluster-c/auth/kubeconfig

Cluster "api-nmanos-aws-devcluster-c-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-c-devcluster-openshift-com:6443"

Cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"

Cluster "nmanos-aws-devcluster-c"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "nmanos-aws-devcluster-c"

Cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"

Cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"

Cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-a-devcluster-openshift-com:6443"

Cluster "api-nmanos-aws-devcluster-c-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-c-devcluster-openshift-com:6443"

Cluster "api-nmanos-aws-devcluster-c-devcluster-openshift-com:6443"
 ✗ Checking the firewall configuration to determine if VXLAN traffic is allowed
 ✗ Could not find the local Endpoint in cluster "api-nmanos-aws-devcluster-c-devcluster-openshift-com:6443"

**What you expected to happen**:
All subctl diagnose firewall intra-cluster checks should pass.

**How to reproduce it (as minimally and precisely as possible)**:
Install Submariner 0.11 on ACM 2.4 with two managed clusters, and run subctl.

**Anything else we need to know?**:

**Environment**:

Client Version: 4.8.13
Server Version: 4.8.13
Kubernetes Version: v1.21.1+a620f50

 Submariner components ###

subctl version: v0.11.0

- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by sridhargaddam** [comment]
@maayanf24 can you please attach subctl gather logs?

**Comment by sridhargaddam** [comment]
The following PR should fix it - https://github.com/submariner-io/submariner-operator/pull/1617
