### ISSUE TITLE
Metrics aren’t configured by default on OCP 4.9

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1621]
Metrics are supposed to be configured automatically on OpenShift; this doesn’t happen with 4.9, the metrics don’t show up in the default query interface.

**Comment by maayanf24** [comment]
@skitt - While testing on OCP 4.9 with subctl, metrics are available automatically. Could it be related to the addon?

**Comment by nyechiel** [comment]
@manosnoam can you please try to reproduce this issue on an OCP 4.9 cluster deployed via ACM? These are the relevant docs, but feel free to ping me once you have a setup running and I can take a look as well: https://submariner.io/operations/monitoring/#openshift-setup

Thanks!

**Comment by manosnoam** [comment]
sure, I have ocp 4.9 env.
Can you specify the steps to validate metrics ?

**Comment by nyechiel** [comment]
> sure, I have ocp 4.9 env. Can you specify the steps to validate metrics ?

@manosnoam you don't need to configure much, just navigate to the OCP Web Console, open the Prometheus UI, and try to filter one of the metrics Submariner exposes like for e.g "submariner_gateways". If you want, ping me on Slack and we can do it together. Thanks!

**Comment by manosnoam** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/9913945/145400975-70494c4d-16a9-442a-bbfc-8ce7c1ef83dd.png)

**Comment by nyechiel** [comment]
I just verified that metrics are being discovered automatically and work as expected (tested with OCP 4.9.10 and Submariner 0.11):

![Screenshot from 2021-12-09 13-05-04](https://user-images.githubusercontent.com/8082244/145385670-35928fdc-d2a2-47d9-bc79-d43664d547aa.png)
