### ISSUE TITLE
Keep getting "Reconciler error" in the log of submariner-operator

### ISSUE THREAD

**Issue by vincent-pli** [submariner-io/submariner-operator#1632]
**What happened**:
Keep getting error message in the log of `submariner-operator`, say this:
```
E1021 01:34:29.894134       1 controller.go:267] controller-runtime/manager/controller/broker "msg"="Reconciler error" "error"="invalid GlobalnetCidrRange: invalid CIDR address: " "name"="submariner-broker" "namespace"="submariner-operator" "reconciler group"="submariner.io" "reconciler kind"="Broker"
```

Just follow the quick start, the sample is works but still get the error message, seems not effect the functionality.

**Comment by sridhargaddam** [comment]
Thanks for reporting the issue @vincent-pli 

Are you seeing this on a Fresh Setup or in an existing setup (which already has a previous globalnet deployment)?

**Comment by vincent-pli** [comment]
A fresh setup @sridhargaddam

**Comment by luis5tb** [comment]
Hitting the same when triggering the deploy-broker in a fresh (OKD) setup

**Comment by sridhargaddam** [comment]
Fixed via - https://github.com/submariner-io/submariner-operator/commit/e40739bdda7a3b70f1d29b79f672689c2dbe781c
