### ISSUE TITLE
Check for any optimizations/improvements

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1647]
- K8s manifests yaml validations (not syntax related)
- https://learnk8s.io/validating-kubernetes-yaml 
- Decide b/w [polaris](https://github.com/FairwindsOps/polaris) or [config-lint](https://stelligent.github.io/config-lint/#/) or [conftest](https://www.conftest.dev/)
- Polaris does not allow skipping files/directories to test, can be added as a [GHA](https://github.com/Jaanki/submariner-operator/pull/3)
- Config-lint does not have any built-in checks
- Conftest needs a new language but can validate k8s, kustomize, Dockerfiles and allows for skipping of folders and has a GHA

**Comment by dfarrell07** [comment]
@Jaanki Maybe we can make more specific issues with reasoning about "why" and close this very general one?
