### ISSUE TITLE
Optimize packagaing logic

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1648]
improve the integration of automation to update the charts/bundle with the release logic. After we do that for Charts, we will have two examples and it will be more clear what is common and how to organize things.

**Comment by dfarrell07** [comment]
This is partly covered in https://github.com/submariner-io/releases/issues/87 and the bundle is broken, needs Operator SDK work before we can think about including that in the release process. Talking about this on the scrub, closing for more specific issues.
