### ISSUE TITLE
Submariner Operator installation failed.

### ISSUE THREAD

**Issue by kanrenibm** [submariner-io/submariner-operator#1683]
**What happened**:

I could not install the Submariner Operator  in Calico environment following the doc , https://www.tigera.io/blog/calico-and-submariner-integration-a-hands-on-walkthrough/ .

**What you expected to happen**:

Submariner Operator installation failed
```
# subctl deploy-broker --kubeconfig broker_config
 ✓ Setting up broker RBAC
 ✗ Deploying the Submariner operator 
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
~# subctl diagnose all
Cluster "kind-broker"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.21.1" is supported

 ⚠ Submariner is not installed
```
- Gather information (use `subctl gather`):

seems there is no data, anyways am attaching the zip file

[submariner-20211130173858.zip](https://github.com/submariner-io/submariner/files/7628321/submariner-20211130173858.zip)

- Cloud provider or hardware configuration:
- Install tools:
Was installing in local ubuntu 
```
~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```
- Others:

**Comment by dfarrell07** [comment]
Hello @kanrenibm, thanks for the question! It's good to see Tigera is blogging about Calico and Submariner!

Looking through that blog, I don't see where the broker is actually deployed? I see you quote `subctl deploy-broker` above, which is how it should be deployed, but I don't see that step in the docs.

This is covered in the upstream kind-based quickstart here:

```
subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1
```

https://submariner.io/getting-started/quickstart/kind/#use-cluster1-as-broker

You may want to try following that guide, in addition to the extra Calico steps:

https://submariner.io/operations/deployment/calico/

**Comment by kanrenibm** [comment]
Thanks @dfarrell07  for taking a look,  yeah I think its missed in the Tigera blog, but I added myself(btw I could deploy the submariner as mentioned in Submariner site through kind installation and all good) , I was following that blog to get the Calico CNI (I think the Kind deployment is using Weavenet). 

Anyways I shall give a try.

**Comment by nyechiel** [comment]
Closing old issues. Please re-open if this is still relevant.
