### ISSUE TITLE
is sonmeone help to explain what colorCode used for

### ISSUE THREAD

**Issue by jinglina** [submariner-io/submariner-operator#1719]
What is the color code parameter used for?

I check the code about the param, not found any idea about it. any one can help?

**Comment by tpantelis** [comment]
I believe it was intended to control which clusters can connect to one another but was never implemented.

BTW, there is a submariner mailing list and slack channel where such questions can be posted instead of creating an issue.

**Comment by jinglina** [comment]
thanks, got it
