### ISSUE TITLE
Add code in submariner-addon to use cloud-prepare to deploy submariner

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#1762]

**Comment by skitt** [comment]
The addon already uses `cloud-prepare` to deploy Submariner. Could you clarify what this issue covers?

**Comment by manosnoam** [comment]
My mistake, I meant to create relevant issue for Azure from the Epic submariner-io/enhancements#87 

Here's the relevant issue for Azure:
submariner-io/subctl#17
