### ISSUE TITLE
The operator should be reworked to use current versions of the Operator SDK

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1824]
The operator currently has code dependencies on version 0.19.0 of the Operator SDK, and uses version 1.0.1 for bundle deployments.

The former is blocking us from upgrading a number of projects and dependencies, including Lighthouse and its CoreDNS dependency, which blocks https://github.com/submariner-io/lighthouse/issues/576

Upgrading the SDK involves reworking the operator since the expected project structure and operator construction have changed significantly.

**Comment by nyechiel** [comment]
@skitt can we close this as a duplicate of https://github.com/submariner-io/enhancements/issues/81?

**Comment by skitt** [comment]
Yes, let’s track this in the enhancements repository.
