### ISSUE TITLE
Support subctl unexport

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-operator#1830]
**What would you like to be added**:

Per a [discussion on Slack](https://kubernetes.slack.com/archives/C010RJV694M/p1642789351043100) with newish-to-SubM devs, it seems like folks rightly-expect subctl to have commands to undo actions it takes. For example, `subctl unexport service`. This can be achieved with `kubectl delete serviceexport`, but that's not a very clear UX.

Another idea is to add a `dry run` mode.

**Why is this needed**:

For better UX.

**Comment by nyechiel** [comment]
De-scoping this to include only the `unexport` part for inclusion with 0.12.

**Comment by nyechiel** [comment]
@mkolesnik can you please raise a quick docs PR as well? AFAICT this should only be mentioned in https://submariner.io/operations/deployment/subctl/
