### ISSUE TITLE
[Doc] set GO111MODULE before running go mod vendor

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#186]
Please add to Readme to run:
`GO111MODULE="on" go mod vendor`
before `make bin/subctl`

Otherwise it can fail on:
```
go mod vendor
go: modules disabled inside GOPATH/src by GO111MODULE=auto; see 'go help modules'

```

**Comment by skitt** [comment]
The build was fixed in #174 to run `go mod vendor` automatically if necessary.
