### ISSUE TITLE
Mark `Linting / Embedded YAMLs up-to-date` as `required`

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#1865]
Now that the [embedded yaml file](https://github.com/submariner-io/submariner-operator/blob/devel/pkg/embeddedyamls/yamls.go) generated using `go generate` is made public and not ignored by Git, lets mark its GHA as required so that any PR which will affect this file won't get merged without its GHA passing.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tpantelis** [comment]
Changed in the branch settings.
