### ISSUE TITLE
subctl show output is messed up

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1893]
> Cluster "skitt-hub"
>  ✗ Showing Connections 
>  ✗ No connections found
> 
>  ✓ Showing Endpoints 
> CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE            
> skitt-hub                     10.0.137.226    18.223.91.218   libreswan           local           
> 
>  ✓ Showing Gateways 
> NODE                            HA STATUS       SUMMARY                         
> ip-10-0-137-226                 active          There are no connections        
> 
>     Discovered network details via Submariner:
>         Network plugin:  OpenShiftSDN
>         Service CIDRs:   [172.32.0.0/16]
>         Cluster CIDRs:   [10.136.0.0/14]
>  ✓ Showing Network details
> 
> ⠈⠑ Showing versions COMPONENT                       REPOSITORY                                            VERSION         
> submariner                      quay.io/submariner                                    0.12.0-rc0      
> submariner-operator             quay.io/submariner                                    0.12.0-rc0      
> service-discovery               quay.io/submariner                                    0.12.0-rc0      
>  ✓ Showing versions

“Showing Network details” appears after the network details, and “Showing versions” appears twice, once with the (abandoned) spinner.

**Comment by nyechiel** [comment]
This is easily reproducible on kind.

**Comment by Jaanki** [comment]
It is result of changes made to status logic. This depends on the when `status.End()` is executed. Proper order is https://github.com/submariner-io/submariner-operator/pull/1832/files#diff-6dc32c624d150007f5f46c2061497acfc21f8d213da89d477025076fe8413386R56-R62.
