### ISSUE TITLE
On OpenShift, the broker secret isn’t always available

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1895]
At least in the gateway pods, the broker secret is mounted but is sometimes empty, which prevents the syncer from connecting to the broker. The cluster eventually recovers, when a gateway restarts and grabs the secret.

**Comment by nyechiel** [comment]
@skitt my understanding is that https://github.com/submariner-io/admiral/pull/330 reduces the impact of this issue, but do you have an idea of what else should be done? should we track it separately or keep this issue open?

**Comment by skitt** [comment]
> @skitt my understanding is that [submariner-io/admiral#330](https://github.com/submariner-io/admiral/pull/330) reduces the impact of this issue, but do you have an idea of what else should be done? should we track it separately or keep this issue open?

I want to keep this open, because the Admiral fix reduces the impact but doesn’t fix everything. I’m investigating the token rotation which seems to be causing problems with OpenShift, at least in 4.9; I haven’t seen the issue in 4.10 so things might have changed there.
