### ISSUE TITLE
subctl leaks log messages

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1896]
This happens with `subctl gather`:

> Cluster "skitt-1"
> Gathering information from cluster "skitt-1"
>  ✓ Gathering service-discovery logs 
>  ✓ Found 3 pods matching label selector "component=submariner-lighthouse"
>  ✓ Found 6 pods matching label selector "dns.operator.openshift.io/daemonset-dns=default"
> ⠈⠱ Gathering service-discovery resources W0303 18:41:54.480010 1402561 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
>  ✓ Gathering service-discovery resources 
>  ✓ Found 0 serviceexports in namespace ""
>  ✓ Found 0 serviceimports in namespace ""
>  ✓ Found 0 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace ""
>  ✓ Found 1 configmaps by label selector "component=submariner-lighthouse" in namespace "submariner-operator"
>  ✓ Found 1 configmaps by field selector "metadata.name=dns-default" in namespace "openshift-dns"
>  ✓ Found 0 services by label selector "submariner.io/exportedServiceRef" in namespace ""
> ⢎⡱ Gathering broker logs W0303 18:41:55.927931 1402561 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
>  ✓ Gathering broker resources 
>  ✓ Found 2 endpoints in namespace "submariner-k8s-broker"
>  ✓ Found 2 clusters in namespace "submariner-k8s-broker"
>  ✓ Found 0 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace "submariner-k8s-broker"
>  ✓ Found 0 serviceimports in namespace "submariner-k8s-broker"
>  ✓ Gathering operator resources 
>  ✓ Found 1 submariners in namespace "submariner-operator"
>  ✓ Found 1 servicediscoveries in namespace "submariner-operator"
>  ✓ Found 1 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
>  ✓ Found 1 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
>  ✓ Found 1 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
>  ✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
>  ✓ Found 0 deployments by label selector "app=submariner-networkplugin-syncer" in namespace "submariner-operator"
>  ✓ Found 1 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
>  ✓ Found 1 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
>  ⚠ Gathering operator logs 
>  ✓ Found 1 pods matching label selector "name=submariner-operator"
>  ⚠ Found logs for previous instances of pod submariner-operator-686cfdd6c9-m9dgp
>  ⚠ Gathering connectivity logs 
>  ✓ Found 2 pods matching label selector "app=submariner-gateway"
>  ⚠ Found logs for previous instances of pod submariner-gateway-q6jjr
>  ⚠ Found logs for previous instances of pod submariner-gateway-rgctp
>  ✓ Found 7 pods matching label selector "app=submariner-routeagent"
>  ⚠ Found logs for previous instances of pod submariner-routeagent-spdqq
>  ✓ Found 0 pods matching label selector "app=submariner-globalnet"
>  ✓ Found 0 pods matching label selector "app=submariner-networkplugin-syncer"
>  ✓ Gathering connectivity resources 
>  ✓ Gathering CNI data from 7 pods matching label selector "app=submariner-routeagent"
>  ✓ Gathering CNI data from 2 pods matching label selector "app=submariner-gateway"
>  ✓ Gathering globalnet data from 0 pods matching label selector "app=submariner-globalnet"
>  ✓ Gathering cable driver data from 2 pods matching label selector "app=submariner-gateway"
>  ✓ Found 2 endpoints in namespace "submariner-operator"
>  ✓ Found 2 clusters in namespace "submariner-operator"
>  ✓ Found 2 gateways in namespace "submariner-operator"
>  ✓ Found 0 clusterglobalegressips in namespace ""
>  ✓ Found 0 globalegressips in namespace ""
>  ✓ Found 0 globalingressips in namespace ""
> ⢎⡠ Gathering broker logs Files are stored under directory "submariner-20220303174151"

Note “W0303 18:41:55.927931 1402561 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice” which shouldn’t appear (even if the problem remains).

It also happens with any failure to load a kubecontext:

> Mar  3 18:48:39.814: ERROR: Unable to load kubeconfig file kubeconfig for context admin2, this is a non-recoverable error
> Mar  3 18:48:39.815: ERROR: loadConfig err: context "admin2" does not exist
> Non-recoverable error: context "admin2" does not exist

**Comment by mkolesnik** [comment]
> It also happens with any failure to load a kubecontext:
> 
> > Mar  3 18:48:39.814: ERROR: Unable to load kubeconfig file kubeconfig for context admin2, this is a non-recoverable error
> > Mar  3 18:48:39.815: ERROR: loadConfig err: context "admin2" does not exist
> > Non-recoverable error: context "admin2" does not exist

I'm not seeing it, which command(s) did you run to get that?
```
[root@d1c8c4ed677b submariner-operator]# ./bin/subctl gather --kubecontexts bubu
Error getting REST Config for cluster: error creating client config: context "bubu" does not exist

subctl version: devel-90e342b5


[root@d1c8c4ed677b submariner-operator]# ./bin/subctl gather --kubecontexts bubu --kubeconfig dudu
Error getting REST Config for cluster: error creating client config: stat dudu: no such file or directory

subctl version: devel-90e342b5


[root@d1c8c4ed677b submariner-operator]# ./bin/subctl gather  --kubeconfig dudu
Error getting REST Config for cluster: error creating kube config: stat dudu: no such file or directory

subctl version: devel-90e342b5
```

**Comment by mkolesnik** [comment]
Generally it's problematic, since there's no good way to disable 3rd party libraries from logging from what I can tell.

We could capture the entire stdout during the call perhaps..?

Probably the best solution would be to use v1 API but AFAICT it's only available since K8s 1.21 and we aim to support 1.20 on 0.12

**Comment by mkolesnik** [comment]
OK after extensive digging around I found https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling and am sending a patch to use that, I'll also open an issue to change the API.

**Comment by mkolesnik** [comment]
Proposed solution output:
```
[root@0e8f396ef662 submariner-operator]# ./bin/subctl gather --kubecontexts cluster1
Cluster "cluster1"
Gathering information from cluster "cluster1"
 ✓ Gathering connectivity logs 
 ✓ Found 1 pods matching label selector "app=submariner-gateway"
 ✓ Found 3 pods matching label selector "app=submariner-routeagent"
 ✓ Found 0 pods matching label selector "app=submariner-globalnet"
 ✓ Found 0 pods matching label selector "app=submariner-networkplugin-syncer"
 ✓ Gathering connectivity resources 
 ✓ Gathering CNI data from 3 pods matching label selector "app=submariner-routeagent"
 ✓ Gathering CNI data from 1 pods matching label selector "app=submariner-gateway"
 ✓ Gathering globalnet data from 0 pods matching label selector "app=submariner-globalnet"
 ✓ Gathering cable driver data from 1 pods matching label selector "app=submariner-gateway"
 ✓ Found 2 endpoints in namespace "submariner-operator"
 ✓ Found 2 clusters in namespace "submariner-operator"
 ✓ Found 1 gateways in namespace "submariner-operator"
 ✓ Found 0 clusterglobalegressips in namespace ""
 ✓ Found 0 globalegressips in namespace ""
 ✓ Found 0 globalingressips in namespace ""
 ✓ Gathering service-discovery logs 
 ✓ Found 3 pods matching label selector "component=submariner-lighthouse"
 ✓ Found 2 pods matching label selector "k8s-app=kube-dns"
 ✓ Gathering service-discovery resources 
 ✓ Found 0 serviceexports in namespace ""
 ✓ Found 0 serviceimports in namespace ""
 ✓ Found 0 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace ""
 ✓ Found 1 configmaps by label selector "component=submariner-lighthouse" in namespace "submariner-operator"
 ✓ Found 1 configmaps by field selector "metadata.name=coredns" in namespace "kube-system"
 ✓ Found 0 services by label selector "submariner.io/exportedServiceRef" in namespace ""
 ✓ Gathering broker resources
 ✓ Found 2 endpoints in namespace "submariner-k8s-broker"
 ✓ Found 2 clusters in namespace "submariner-k8s-broker"
 ✓ Found 0 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace "submariner-k8s-broker"
 ✓ Found 0 serviceimports in namespace "submariner-k8s-broker"
 ⚠ Gathering operator logs 
 ✓ Found 1 pods matching label selector "name=submariner-operator"
 ⚠ Found logs for previous instances of pod submariner-operator-769c88dbfd-qqgtd
 ✓ Gathering operator resources
 ✓ Found 1 submariners in namespace "submariner-operator"
 ✓ Found 1 servicediscoveries in namespace "submariner-operator"
 ✓ Found 1 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
 ✓ Found 0 deployments by label selector "app=submariner-networkplugin-syncer" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
⢎⠁ Gathering broker logs Files are stored under directory "submariner-20220306154740"

Encountered following Kubernetes warnings while running:
Warning: discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
```

**Comment by mkolesnik** [comment]
Opened submariner-io/subctl#45 for switching the API
