### ISSUE TITLE
subctl uninstall should report which cluster it is uninstalling

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1897]
When given a kubeconfig with multiple clusters and contexts, `uninstall` uninstalls the current context as expected; but it never mentions which cluster it is processing:

> ? This will completely uninstall Submariner from the cluster. Are you sure you want to continue? Yes
>  ✓ Checking if the connectivity component is installed 
>  ✓ The connectivity component is installed
>  ✓ Deleting the Submariner resource - this may take some time 
>  ✓ Deleting the Submariner cluster roles and bindings 
>  ✓ Deleted the "submariner-diagnose" cluster role and binding
>  ✓ Deleted the "submariner-gateway" cluster role and binding
>  ✓ Deleted the "submariner-globalnet" cluster role and binding
>  ✓ Deleted the "submariner-lighthouse-agent" cluster role and binding
>  ✓ Deleted the "submariner-lighthouse-coredns" cluster role and binding
>  ✓ Deleted the "submariner-networkplugin-syncer" cluster role and binding
>  ✓ Deleted the "submariner-operator" cluster role and binding
>  ✓ Deleted the "submariner-routeagent" cluster role and binding
>  ✓ Deleting the Submariner namespace "submariner-operator" 
>  ✓ Deleting the Submariner custom resource definitions 
>  ✓ Deleted the "brokers.submariner.io" custom resource definition
>  ✓ Deleted the "clusterglobalegressips.submariner.io" custom resource definition
>  ✓ Deleted the "clusters.submariner.io" custom resource definition
>  ✓ Deleted the "endpoints.submariner.io" custom resource definition
>  ✓ Deleted the "gateways.submariner.io" custom resource definition
>  ✓ Deleted the "globalegressips.submariner.io" custom resource definition
>  ✓ Deleted the "globalingressips.submariner.io" custom resource definition
>  ✓ Deleted the "servicediscoveries.submariner.io" custom resource definition
>  ✓ Deleted the "submariners.submariner.io" custom resource definition
>  ✓ Unlabeling gateway nodes 

Before or in the confirmation prompt, we should mention which cluster we are uninstalling.

**Comment by mkolesnik** [comment]
FYI `deploy-broker` doesnt either, so maybe its a more general concern that should be added at a higher level to all the commands?

```shell
[root@d1c8c4ed677b submariner-operator]# ./bin/subctl deploy-broker
 ✓ Setting up broker RBAC
 ✓ Deploying the Submariner operator 
 ✓ Created operator CRDs
 ✓ Created operator namespace: submariner-operator
 ✓ Created operator service account and role
 ✓ Created lighthouse service account and role
 ✓ Created Lighthouse service accounts and roles
 ✓ Deployed the operator successfully
 ✓ Deploying the broker
 ✓ The broker has been deployed
 ✓ Creating broker-info.subm file
 ✓ A new IPsec PSK will be generated for broker-info.subm
```

**Comment by skitt** [comment]
> FYI `deploy-broker` doesnt either, so maybe its a more general concern that should be added at a higher level to all the commands?

Indeed, we should consider that.
