### ISSUE TITLE
subctl uninstall should produce friendlier output when Submariner isn’t installed

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1903]
On a cluster where Submariner isn’t present, `subctl uninstall` produces

> ? This will completely uninstall Submariner from the cluster. Are you sure you want to continue? Yes
>  ✗ Error retrieving the Submariner namespace "submariner-operator": namespaces "submariner-operator" not found
> 
> subctl version: v0.12.0-rc0

It’s clear to us that this means that Submariner isn’t installed, but it might not be obvious to many users. It would be better to clearly indicate that Submariner isn’t installed, as `diagnose` does:

> Cluster "skitt-1"
>  ✓ Checking Submariner support for the Kubernetes version 
>  ✓ Kubernetes version "v1.22.3+b93fd35" is supported
> 
>  ⚠ Submariner is not installed

**Comment by mkolesnik** [comment]
Proposing a PR to make uninstall re-entrant, now it'll look like this:

```shell
[root@d1c8c4ed677b submariner-operator]# ./bin/subctl uninstall -y
 ✓ Checking if the connectivity component is installed
 ✓ The connectivity component is not installed - skipping
 ✓ Checking if the service discovery component is installed
 ✓ The service discovery component is not installed - skipping
 ✓ Deleting the Submariner cluster roles and bindings
 ✓ Deleting the Submariner namespace "submariner-operator"
 ✓ Deleting the Submariner custom resource definitions
 ✓ Unlabeling gateway nodes
```
