### ISSUE TITLE
IP rule list/tables not deleted on GW node after submariner uninstall 

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner-operator#1913]
**What happened**:
IP rule list and tables (100 and 150) were not deleted on GW node after Submariner uninstall

**What you expected to happen**:
IP tables and rules (100,150) should be deleted 

**How to reproduce it (as minimally and precisely as possible)**:

$ bin/subctl uninstall  --kubeconfig output/kubeconfigs/kind-config-cluster2
? This will completely uninstall Submariner from the cluster. Are you sure you want to continue? Yes
 ✓ Checking if the connectivity component is installed
 ✓ The connectivity component is installed
 ✓ Deleting the Submariner resource - this may take some time 
 ✓ Deleting the Submariner cluster roles and bindings 
 ✓ Deleted the "submariner-diagnose" cluster role and binding
 ✓ Deleted the "submariner-gateway" cluster role and binding
 ✓ Deleted the "submariner-globalnet" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-agent" cluster role and binding
 ✓ Deleted the "submariner-lighthouse-coredns" cluster role and binding
 ✓ Deleted the "submariner-networkplugin-syncer" cluster role and binding
 ✓ Deleted the "submariner-operator" cluster role and binding
 ✓ Deleted the "submariner-routeagent" cluster role and binding
 ✓ Deleting the Submariner namespace "submariner-operator"
 ✓ Deleting the Submariner custom resource definitions
 ✓ Deleted the "brokers.submariner.io" custom resource definition
 ✓ Deleted the "clusterglobalegressips.submariner.io" custom resource definition
 ✓ Deleted the "clusters.submariner.io" custom resource definition
 ✓ Deleted the "endpoints.submariner.io" custom resource definition
 ✓ Deleted the "gateways.submariner.io" custom resource definition
 ✓ Deleted the "globalegressips.submariner.io" custom resource definition
 ✓ Deleted the "globalingressips.submariner.io" custom resource definition
 ✓ Deleted the "servicediscoveries.submariner.io" custom resource definition
 ✓ Deleted the "submariners.submariner.io" custom resource definition
 ✓ Unlabeling gateway nodes

// ssh GW nodes
$ ./../scripts/netshoot_node.sh cluster2-worker
If you don't see a command prompt, try pressing enter.
bash-5.1# ip rule list 
0:      from all lookup local
100:    from all lookup 100
150:    from all lookup 150
32766:  from all lookup main
32767:  from all lookup default

**Anything else we need to know?**:

**Environment**:
KIND (vxlan)

**Comment by sridhargaddam** [comment]
@yboaron Are there any entries in the above tables?
ip route show table 100 
ip route show table 150

**Comment by yboaron** [comment]
> @yboaron Are there any entries in the above tables? ip route show table 100 ip route show table 150

Nope, tables are empty

**Comment by yboaron** [comment]
Only the ip rules exist after uninstall, and yeah they are pointing to empty tables (150 and 100) so no effect on IP routing.


This is the relevant output from GW node (KIND reswan):

Before uninstall
==============

bash-5.1# ip rule list 
0:      from all lookup local
150:    from all lookup 150
32766:  from all lookup main
32767:  from all lookup default
bash-5.1# 
bash-5.1# ip route show table 150 
10.1.0.0/16 dev eth0 proto static scope link src 10.2.0.1 
100.1.0.0/16 dev eth0 proto static scope link src 10.2.0.1 
bash-5.1# 

After uninstall
==============


bash-5.1# ip route show table 150 
bash-5.1# ip rule list 
0:      from all lookup local
150:    from all lookup 150
32766:  from all lookup main
32767:  from all lookup default
bash-5.1#

**Comment by sridhargaddam** [comment]
> Only the ip rules exist after uninstall, and yeah they are pointing to empty tables (150 and 100) so no effect on IP routing.

Correct, they will not have an effect on the routing, as they are empty. But to avoid any confusion, we can remove the tables as well.
