### ISSUE TITLE
Cloud prepare: Switch the default dedicated mode to enabled for GCP Clusters

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#1915]
Currently, while preparing cloud infrastructure for GCP clusters, the default value of `--dedicated-gateway` is set as false. This should be changed to "true".

```
subctl cloud prepare gcp -h
This command prepares an OpenShift installer-provisioned infrastructure (IPI) on GCP cloud for Submariner installation.

Usage:
  subctl cloud prepare gcp [flags]

Flags:
      --credentials string        GCP credentials configuration file (default "/home/sgaddam/.gcp/osServiceAccount.json")
      --dedicated-gateway         Whether a dedicated gateway node has to be deployed (default false)
      --gateway-instance string   Type of gateway instance machine (default "n1-standard-4")
      --gateways int              Number of gateways to deploy (default 1)
  -h, --help                      help for gcp
      --infra-id string           GCP infra ID
      --ocp-metadata string       OCP metadata.json file (or the directory containing it) from which to read the GCP infra ID and region from (takes precedence over the specific flags)
      --project-id string         GCP project ID
      --region string             GCP region
```

**Comment by nyechiel** [comment]
@sridhargaddam it looks like we will also need to update our docs: https://submariner.io/operations/deployment/subctl/#prepare-gcp

**Comment by sridhargaddam** [comment]
> @sridhargaddam it looks like we will also need to update our docs: https://submariner.io/operations/deployment/subctl/#prepare-gcp

Done: https://github.com/submariner-io/submariner-website/pull/701

**Comment by sridhargaddam** [comment]
> @sridhargaddam it looks like we will also need to update our docs: https://submariner.io/operations/deployment/subctl/#prepare-gcp

@nyechiel do we have an issue to track documentation for "rhos cloud prepare"?

**Comment by nyechiel** [comment]
> > @sridhargaddam it looks like we will also need to update our docs: https://submariner.io/operations/deployment/subctl/#prepare-gcp
> 
> @nyechiel do we have an issue to track documentation for "rhos cloud prepare"?

It's mentioned in the epic (https://github.com/submariner-io/enhancements/issues/47) but I don't see an issue to track it. @aswinsuryan can you please handle this?
