### ISSUE TITLE
Subctl failed to use latest kubefedctl version

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#192]
I've installed latest kubfedctl:
https://github.com/kubernetes-sigs/kubefed/releases/tag/v0.1.0-rc6

But subctl requires an older version (v0.1.0-rc3):

```
./bin/subctl deploy-broker --service-discovery --clusterid subm-cluster-a
cat
Invalid configuration: invalid kubefedctl version v0.1.0-rc6, please use v0.1.0-rc3
subctl version: dev
built from git commit id: 8c619fe06f3213c456093e10e48b967863e4d5a2
```

**Comment by skitt** [comment]
What’s the bug?

**Comment by mangelajo** [comment]
I think this is only temporary, we will get rid of kubefed later, please use the specified version instead, we should not waste time in trying to support all versions of kubefedctl
