### ISSUE TITLE
Log flooded with `k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown`

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1921]
Fixing #1914 with #1920 unearthed these log messages "flooding" the log, every 30-40 secs.
We should probably address them.

```
E0308 10:51:01.933073       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:51:48.171557       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:52:26.532414       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:53:12.454226       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:53:53.316304       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:54:50.151394       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:55:48.143438       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
E0308 10:56:40.053902       1 reflector.go:127] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:156: Failed to watch *unstructured.Unstructured: unknown
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

Depends on: https://github.com/submariner-io/submariner-operator/pull/2126

**Comment by Jaanki** [comment]
With https://github.com/submariner-io/submariner-operator/pull/2126, we are moving away from `client-go`. This needs to be rechecked after the PR is merged.

**Comment by nyechiel** [comment]
@mkolesnik is this still valid?

**Comment by tpantelis** [comment]
This is still happening even after the K8s upgrade:

`[cluster1] E0830 16:14:52.314739       1 reflector.go:138] k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *unstructured.Unstructured: unknown`

We don't specifically watch the `Unstructured` type anywhere. I winder if this is somehow related to the `Secrets` resource syncer.

**Comment by skitt** [comment]
Let’s try removing that then: https://github.com/submariner-io/submariner-operator/pull/2253
