### ISSUE TITLE
Running `subctl gather` with no flags does absolutely nothing

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1944]
**What happened**:
Running `subctl gather` exists cleanly and does nothing.

```bash
$ subctl gather
$ echo $?
0
```

**What you expected to happen**:
If nothing was given (i.e. no cluster(s) to gather from), `subctl gather` should show a message which flags/arguments it expects.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This is when `KUBECONFIG` is not set.

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tpantelis** [comment]
`ExecuteMultiCluster` silently returns if no kube configs were provided. Same things happens with `diagnose` et al. We should output a message, eg "_No kube config was provided. Please use the --kubeconfig flag or set the KUBECONFIG environment variable_"
