### ISSUE TITLE
Help text incorrect for `subctl gather`

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#1945]
**What happened**:
Running `subctl gather` without `KUBECONFIG` set:

```bash
[mkolesni@mkolaptop openshift]$ subctl gather --help
This command gathers information from a submariner cluster for troubleshooting. The information gathered can be selected by component (broker,operator,connectivity,service-discovery) and type (logs,resources). Default is to capture all data.

Usage:
  subctl gather <kubeConfig> [flags]
...
```

Then:
```bash
$ subctl gather /home/mkolesni/Downloads/openshift-install-linux/mkolesni-0.12-testday2/auth/kubeconfig
$ 
```

So clearly sending kubeConfig is not working

We should fix the documentation

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tpantelis** [comment]
`subctl gather` does not accept a _kubeConfig_ arg so remove it from the help text.

**Comment by dfarrell07** [comment]
We should also update the docs:

https://submariner.io/operations/deployment/subctl/#gather-flags

```
operations/deployment/subctl/_index.en.md:317:via the `--kubeconfig` flag (or the `KUBECONFIG` environment variable). By default it will gather information from all the cluster contexts contained
operations/deployment/subctl/_index.en.md:318:in the kubeconfig. To gather information from specific clusters, contexts can be passed using `kubecontexts` flag.
operations/deployment/subctl/_index.en.md:349:`subctl gather --kubecontexts cluster-east`
operations/deployment/subctl/_index.en.md:353:`subctl gather --kubecontexts cluster-east,cluster-west --module operator,connectivity --type logs`
```

**Comment by tpantelis** [comment]
> We should also update the docs:
> 

Update which part specifically? The docs don't indicate the unused arg.

**Comment by dfarrell07** [comment]
Ah so it does accept a kubeconfig, just not in the way described here?

**Comment by tpantelis** [comment]
> Ah so it does accept a kubeconfig, just not in the way described here?

It's passed as a flag as described in the website docs. It is **not** passed as an arg so the code help text is incorrect.
