### ISSUE TITLE
subctl should return appropriate error instead of PANIC

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#195]
While running some commands without passing arguments, subctl is displaying a PANIC message instead of showing an error.

[sgaddam@localhost submariner-operator]$ ./bin/subctl verify-connectivity
Error: accepts 2 arg(s), received 0
Usage:
  subctl verify-connectivity [flags]

Flags:
      --connection-attempts uint   The maximum number of connection attempts (default 2)
      --connection-timeout uint    The timeout in seconds per connection attempt  (default 60)
  -h, --help                       help for verify-connectivity
      --operation-timeout uint     Operation timeout for K8s API calls (default 240)
      --report-dir string          XML report directory (default ".")
      --verbose                    Produce verbose logs during connectivity verification

**panic: accepts 2 arg(s), received 0**

goroutine 1 [running]:
main.main()
        **/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:24 +0x84**

**Comment by sridhargaddam** [comment]
Pr [https://github.com/submariner-io/submariner-operator/pull/196] displays the following message instead of PANIC.

[sgaddam@localhost submariner-operator]$ ./bin/subctl verify-connectivity
Error: Two kubeconfigs must be specified.
Usage:
  **subctl verify-connectivity \<kubeConfig1\> \<kubeConfig2\> [flags]**

Flags:
      --connection-attempts uint   The maximum number of connection attempts (default 2)
      --connection-timeout uint    The timeout in seconds per connection attempt  (default 60)
  -h, --help                       help for verify-connectivity
      --operation-timeout uint     Operation timeout for K8s API calls (default 240)
      --report-dir string          XML report directory (default ".")
      --verbose                    Produce verbose logs during connectivity verification

Error:  Two kubeconfigs must be specified.

**Comment by skitt** [comment]
This is fixed by #196.
