### ISSUE TITLE
Backport `subctl verify --junit-report` flag into release-0.12

### ISSUE THREAD

**Issue by MaxBab** [submariner-io/submariner-operator#1977]
Recent patches https://github.com/submariner-io/submariner-operator/pull/1961 https://github.com/submariner-io/shipyard/pull/755 added new flag - `--junit-report` to `subctl verify` command.

The flag helps to generate an xml report at the end of e2e tests execution.
The xml report is required for presenting the results of the testing within the qe pipeline.

The subctl version that is used within the testing pipeline, should be identical to the version of installed submariner.
That's why the backport of the flag is necessary for the qe testing.

**Comment by MaxBab** [comment]
@skitt @dfarrell07 

Guys, is it possible to make a backport to 0.12 z release?
Please, share your thoughts.

**Comment by skitt** [comment]
This is being used only for testing. Currently Maxim tests 0.12 with the `devel` `subctl`, only to run tests (deployment is handled by ACM). I think it’s worth backporting to ensure that 0.12.x is testing with the corresponding `subctl`; otherwise as 0.13 progresses and we potentially add 0.13-specific tests, we’re liable to break the 0.12 tests.

@dfarrell07 what do you think? I’ll add this to the PR scrub.

**Comment by dfarrell07** [comment]
Talked about this on the PR scrub today, we agree it's good to backport. :+1:

**Comment by dfarrell07** [comment]
@MaxBab Do you want to try the backport process? https://submariner.io/development/backports/

**Comment by MaxBab** [comment]
@dfarrell07 
Sure.
Will do it.

Thanks @skitt and @dfarrell07 for approval.

**Comment by skitt** [comment]
@MaxBab can you take care of this, or do you want someone else to do the backport?

**Comment by MaxBab** [comment]
@skitt @dfarrell07 

Guys, I will glad to do it.
But I don't understand the flow.

I read the guide on submariner website - https://submariner.io/development/backports/

And I'm not sure how should I do it.

Should I create a new PR for the "release-0.12" branch and label it with "backport"?
Or should I cherry-pick the existing (merged) PR?

Another question - I guess the go.mod file is not more relevant, or it is?

Will appreciate some tips regarding it.

**Comment by dfarrell07** [comment]
> But I don't understand the flow.

This is being discussed on Slack: https://app.slack.com/client/T09NY5SBT/C010RJV694M/thread/C010RJV694M-1651498210.822659

**Comment by dfarrell07** [comment]
This was done in https://github.com/submariner-io/shipyard/pull/799 and https://github.com/submariner-io/submariner-operator/pull/2038. Thanks @MaxBab! :heavy_check_mark:
