### ISSUE TITLE
`subctl uninstall` references a hard-coded image: `gcr.io/google_containers/pause`

### ISSUE THREAD

**Issue by cgruver** [submariner-io/submariner-operator#2001]
Executing `subctl uninstall` in a disconnected network generates image pull errors because of a hard-coded reference to `gcr.io/google_containers/pause`

The uninstall does appear to eventually succeed, but it takes an extended time due to the image pull failures, and may be subject to race conditions because the pause container is unavailable.

subctl version: `v0.12.0`

OKD 4.10

Relevant file: `./submariner-operator/internal/pods/schedule.go`

```go
func convertPodSpecContainersToUninstall(podSpec *corev1.PodSpec) {
	// We're going to use the PodSpec to run a one-time task by using an init container to run the task.
	// See http://blog.itaysk.com/2017/12/26/the-single-use-daemonset-pattern-and-prepulling-images-in-kubernetes
	// for more details.
	podSpec.InitContainers = podSpec.Containers
	podSpec.InitContainers[0].Env = append(podSpec.InitContainers[0].Env, corev1.EnvVar{Name: ContainerEnvVar, Value: "true"})

	podSpec.Containers = []corev1.Container{
		{
			Name:  "pause",
			Image: "gcr.io/google_containers/pause",
		},
	}
}
```

**Comment by skitt** [comment]
It seems like `image.GetPauseImageName()` from `k8s.io/kubernetes/test/utils/image` would give us the right name, but it’s not clear to me right now whether that’s intended for production use or just test use.

The canonical image name seems to be `k8s.gcr.io/pause`.
