### ISSUE TITLE
Lighthouse operator support

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#201]
Move all the lighthouse handling into the operator itself

https://github.com/submariner-io/submariner-operator/pull/5

**Comment by mangelajo** [comment]
@vthapar @aswinsuryan @skitt :-) let's not forget and let's handle it for 0.2, also opened another one for the broker bits too.

**Comment by aswinsuryan** [comment]
@mangelajo Most of this is done with 
https://github.com/submariner-io/submariner-operator/pull/300
https://github.com/submariner-io/submariner-operator/pull/324
https://github.com/submariner-io/submariner-operator/pull/392
https://github.com/submariner-io/submariner-operator/pull/427

The remaining will be done by 
https://github.com/submariner-io/submariner-operator/issues/396

Can we close this one?
