### ISSUE TITLE
Move broker handling to the operator (out of subctl)

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#203]
Currently the broker creation is managed from subctl, while it should go into the operator itself (for future coordinated upgrade handling, etc...)

**Comment by dfarrell07** [comment]
@skitt @mangelajo Maybe we can sync on this and I can help?

**Comment by skitt** [comment]
> @skitt @mangelajo Maybe we can sync on this and I can help?

We’re waiting for the migration to SDK 1 to be finished.

**Comment by nyechiel** [comment]
@dfarrell07 can you look at this now that SDK v1 is merged?

**Comment by skitt** [comment]
@dfarrell07 do you still plan on taking care of this, or would you like me to do it?

**Comment by dfarrell07** [comment]
> @dfarrell07 do you still plan on taking care of this, or would you like me to do it?

@skitt Yeah I got pulled away by various other TODOs, sorry. If you have cycles for it now you're very welcome to take it, I'm sure you'd get it done much better and faster than I could. I'd be happy to review and learn from your implementation.

**Comment by skitt** [comment]
> > @dfarrell07 do you still plan on taking care of this, or would you like me to do it?
> 
> @skitt Yeah I got pulled away by various other TODOs, sorry. If you have cycles for it now you're very welcome to take it, I'm sure you'd get it done much better and faster than I could. I'd be happy to review and learn from your implementation.

OK, I’ve assigned this to the two of us, I’ll look into it this week.
