### ISSUE TITLE
Delete the `subctl`-specific code.

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#2030]
Delete below directories:
- [x] /cmd
- [x] /internal
- [x] scripts/subctl
- [x] code from Makefile
- [x] /pkg except /pkg/embeddedyamls (and check for any more exceptions)

and below CI Jobs

- [x] subctl.yml
- [x] cross.yml
- [x] release_subctl_on_push.yml

Part of epic [Move subctl to its own repo](https://github.com/submariner-io/enhancements/issues/89)

**Comment by mkolesnik** [comment]
Why label this as bug? it's a task that's part of the epic

**Comment by skitt** [comment]
There’s still a bunch more code to delete.
