### ISSUE TITLE
Encapsulate SPDY bidirectional upgrades in client.Producer

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#2042]
`client.Producer` was designed to encapsulate all client access, from `rest.Config` or other sources. In #2007, this encapsulation was broken inside `cluster.Info`, because executing a pod and retrieving its streams requires upgrading a connection, and that involves passing a `rest.Config`. This has the unfortunate side-effect of producing `cluster.Info` instances which have different capabilities depending on how they were created, in non-obvious ways (a `nil` pointer to a `rest.Config`).

`client.Producer` should be improved to handle this itself, and the explicit passing of a `rest.Config` in `cluster.Info` should be removed.

**Comment by tpantelis** [comment]
I agree. I didn't like having to add `rest.Config` to `cluster.Info` but didn't see a simple/obvious way to avoid it.

**Comment by maayanf24** [comment]
Will not work on this soon
