### ISSUE TITLE
Integrating Lighthouse Plugin with Openshift CoreDNS.

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-operator#208]
The lighthouse coreDNS plugin is now not a part of the default Openshift CoreDNS image, we build a custom image and the coreDNS in the cluster is restarted after updating the image.

We need to make the Lighthouse Plugin a part of the default coreDNS image. The lighthouse shall be always enabled in the coremap, but it should just return a default status if SubMariner is not deployed so that the next plugin will take over the request.

**Comment by nyechiel** [comment]
As part of our effort to align with the proposal coming from sig-multicluster, we will go with a forward plugin instead.
