### ISSUE TITLE
Nodelocaldns configmap incorrect

### ISSUE THREAD

**Issue by pengbinbin1** [submariner-io/submariner-operator#2102]
**What happened**:
I have deployed submariner on my 2 k8s clusters. When I join the submariner, I have set the arg **--coredns-custom-configmap** to "**kube-system/nodelocaldns**",but i can not access the import svc via **svcname.namespace.svc.clusterset.local**,the error is "can't resolve the host ". I check the nodelocaldns configmap,like below
![image](https://user-images.githubusercontent.com/28950491/172336453-58f6897e-8d08-4428-b8bb-1f8f8bcfadcc.png)

I edit the nodelocaldns configmap into the below,it will work ok .

![image](https://user-images.githubusercontent.com/28950491/172338169-dfef250a-55dc-450e-bacd-62467c90cb9e.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
Thanks @pengbinbin1! @aswinsuryan volunteered to take a look.

**Comment by aswinsuryan** [comment]
@pengbinbin1 is it resolving the local service when you configure the 169.254.25.10 ? 

Are the lighthouse pods up and running?

**Comment by pengbinbin1** [comment]
Yes，the lighthouse pods is up and running. And when i configure the 169.254.25.10 like **_`bind 169.254.25.10`_** it will work ok.

**Comment by pengbinbin1** [comment]
@aswinsuryan

**Comment by dfarrell07** [comment]
@pengbinbin1 Are you still seeing this issue?

**Comment by dfarrell07** [comment]
@pengbinbin1 Closing due to lack of info, feel free to re-open if this is still an issue and you can discuss.
