### ISSUE TITLE
iptables SUBMARINER_GN_EGRESS is not right set in globalnet project, using images with arm64 arch and version release-0.13.0

### ISSUE THREAD

**Issue by jinglina** [submariner-io/submariner-operator#2131]
**What happened**:
when arm64 images is used in arm64 environment, subctl show connection is error.After research,  package(ping globalip process) that should send to iptables SUBMARINER_GN_EGRESS  is not reachable here, but received by other rules. 
 
as a result, subctl show connections is error. 

**What you expected to happen**:
package should be accepted by SUBMARINER_GN_EGRESS rules.

**How to reproduce it (as minimally and precisely as possible)**:
using arm64 images with version release-0.13

**Comment by jinglina** [comment]
![iptables](https://user-images.githubusercontent.com/30133396/177725429-6d3401fe-5ed8-47f5-801f-51816a39816a.jpeg)

**Comment by jinglina** [comment]
![iptables2](https://user-images.githubusercontent.com/30133396/177736223-406276fe-4b0e-42bb-9a58-73eed4e4b326.jpeg)

**Comment by jinglina** [comment]
in **amd64** environment, it shows like this:
![iptables3](https://user-images.githubusercontent.com/30133396/177736974-8ef857d4-0d79-47c1-99ac-a9201466c6da.jpeg)

**Comment by skitt** [comment]
Does the table show up if you use `iptables-legacy`?

**Comment by jinglina** [comment]
The system I uesd is Centos8, default iptables mode is nftables. The images should consider to make it compatible to this mode. A s far as I know , k8s kube-proxy does it.

**Comment by skitt** [comment]
Yes, and our container images are compatible with nftables, they automatically pick `iptables-legacy` or `iptables-nft` depending on what’s used on the host. In fact your `iptables` output shows that `iptables-nft` is being used. However, something has added rules to the legacy chains (“WARNING: iptables-legacy tables present, use iptables-legacy to see them”). That’s what I’d like to check.

**Comment by nyechiel** [comment]
> Does the table show up if you use `iptables-legacy`?

@jinglina can you comment on that?

**Comment by dfarrell07** [comment]
It seems like we need some more info. @jinglina feel free to re-open or open a new issue, but I think we should go ahead and close this one for now.

**Comment by dfarrell07** [comment]
@jinglina Closing due to lack of info, feel free to provide details an re-open.
