### ISSUE TITLE
Travis: Missing subctl command with --service-discovery

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#214]
Currently we only run in Travis:
`../bin/subctl --kubeconfig /go/src/github.com/submariner-io/submariner-operator/output/kind-config/dapper/kind-config-cluster1 --kubecontext cluster1 deploy-broker`

Without `--service-discovery`

For example:
https://travis-ci.com/submariner-io/submariner-operator/jobs/291693448

**Comment by skitt** [comment]
https://github.com/submariner-io/submariner-operator/pull/190 addresses this (but doesn’t work yet).

**Comment by skitt** [comment]
Fixed with #190.
