### ISSUE TITLE
OVN CI Jobs are running with weave instead of ovn-k

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#2145]
**What happened**:
The CI jobs like "[E2E (1.24, ovn)]" ideally should be running with OVN-Kubernetes CNI, but instead use weave giving a false impression that jobs are validated on OVNK. Looks like the "using=ovn" flag is broken.

**Comment by dfarrell07** [comment]
I documented the same thing here: https://github.com/submariner-io/submariner-operator/issues/2139
