### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by mongoliaredmountain** [submariner-io/submariner-operator#2171]
<img width="1092" alt="WX20220816-171222@2x" src="https://user-images.githubusercontent.com/22609864/184844306-bbbe9c50-9cc2-4097-83d9-fc89c60ce11c.png">
<img width="1096" alt="WX20220816-171332@2x" src="https://user-images.githubusercontent.com/22609864/184844320-20979637-bc79-46b9-accc-a56223ee3189.png">
<img width="842" alt="WX20220816-171445@2x" src="https://user-images.githubusercontent.com/22609864/184844328-5dde77b4-e3a0-4dea-9e42-796f0b0b61ed.png">

subctl join --kubeconfig /root/.kube/config broker-info.subm --clustercidr=10.10.0.0/16  --natt=false

Deploy submariner operator，other running ,only getway error.

**Comment by nyechiel** [comment]
@mongoliaredmountain can you please follow our bug template, and attach full info and logs?
