### ISSUE TITLE
Why the status about namespace submariner-operator is always terminating?

### ISSUE THREAD

**Issue by pengbinbin1** [submariner-io/submariner-operator#2223]
When i uninstall the submariner used the command "subctl uninstall -y",sometimes the status about  submariner-operator namespace is terminating ,and the status  will remain teriminating for all time ,but why?
**What would you like to be added**:

**Why is this needed**:

**Comment by tpantelis** [comment]
Perhaps there's still resources left in the namespace. This command should find the resources that weren't deleted:

`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n submariner-operator`

Also run `kubectl get namespace submariner-operator -o yaml` - hopefully a status condition will indicate why it's stuck terminating.

**Comment by pengbinbin1** [comment]
I have exec the command `kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n submariner-operator` and there are no response.

**Comment by pengbinbin1** [comment]
<img width="381" alt="微信截图_20220914095845" src="https://user-images.githubusercontent.com/28950491/190045666-01dae0e0-8dad-4dc9-a00c-e86395844457.png">
<img width="543" alt="微信截图_20220914095921" src="https://user-images.githubusercontent.com/28950491/190045672-1cd83899-a98b-4b6b-93d6-38a53a51ec7a.png">

**Comment by nyechiel** [comment]
@tpantelis this sounds like a bug?

**Comment by tpantelis** [comment]
> @tpantelis this sounds like a bug?

I don't know. There may be resources remaining in the namespace - if so we need to know what those resources are but he says the command to list them doesn't respond which seems strange.  Not sure how to proceed w/o more info to go on.

Looking at the namespace status conditions, one says "_Failed to delete all resource types, 4 remaining: the server was unable to return a response_". So apparently 4 resources failed to delete for some unknown reason. Perhaps we can narrow it down by trying to query specific common types, eg

`kubectl get  daemonsets -n submariner-operator`
`kubectl get  deployments -n submariner-operator`

**Comment by nyechiel** [comment]
> > @tpantelis this sounds like a bug?
> 
> I don't know. There may be resources remaining in the namespace - if so we need to know what those resources are but he says the command to list them doesn't respond which seems strange. Not sure how to proceed w/o more info to go on.
> 
> Looking at the namespace status conditions, one says "_Failed to delete all resource types, 4 remaining: the server was unable to return a response_". So apparently 4 resources failed to delete for some unknown reason. Perhaps we can narrow it down by trying to query specific common types, eg
> 
> `kubectl get daemonsets -n submariner-operator` `kubectl get deployments -n submariner-operator`

Is this reproducible with `kind`?

**Comment by pengbinbin1** [comment]
> It is a accidental event.,but I've had this problem several times. I have get all the resources in namespace submariner-operator,but  the response is empty.

**Comment by dfarrell07** [comment]
@pengbinbin1 I think we need you to run the diagnostic commands @tpantelis mentioned, maybe also `subctl diagnose`/`subctl gather`.

**Comment by dfarrell07** [comment]
@pengbinbin1 closing as needs-info, feel free to re-open!
