### ISSUE TITLE
Should be able to pull submariner images from private registry

### ISSUE THREAD

**Issue by dirajag1** [submariner-io/submariner-operator#2224]
**What would you like to be added**:
With the current subctl CLI , we can pull images from a custom registry using the --repository option .
However, this should be a public registry and we are unable to pull the images from a registry with credentials .
We should also be able to customize the image names with tags .

**Why is this needed**:

We have a requirement to do an offline installation of submariner  where we will pull the images from a local registry .
This requires us to specify different repo names and image names with SHA tags .
Also we need to use a secret to pull images from the private registry .

**Comment by skitt** [comment]
To be able to install images from a private registry, we need to support `imagePullSecrets` in pod templates; see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ for details.

**Comment by nyechiel** [comment]
@sridhargaddam we probably want to prioritize this for 0.14 as part of air-gapped support?

**Comment by dfarrell07** [comment]
I think @skitt has been working on this recently, he may have some updates.

> We should also be able to customize the image names with tags .

This should work.

> support imagePullSecrets

This is still TODO.
