### ISSUE TITLE
Flaky failures in E2E (wireguard/libreswan, globalnet, 1.25, lighthouse)

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-operator#2302]
**What happened**:

We've had two Flake Finder failures in the last week in the operator repo. We run the FF twice a night to know if a failure was due to infra or something consistent, or is actually a flake. In both cases, only one of the two jobs failed, which indicates a flake.

**What you expected to happen**:

Zero flakey failures.

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/submariner-io/submariner-operator/actions/runs/3309375177
https://github.com/submariner-io/submariner-operator/actions/runs/3269949081

**Comment by sridhargaddam** [comment]
Looks like the failure is in Service discovery test-case: 

Both the failures are pointing to the same test-case.

```
[Fail] [discovery] Test Headless Service Discovery Across Clusters when the number of active pods backing a service changes [It] should resolve the local pod IPs 
github.com/submariner-io/shipyard@v0.14.0-m2/test/e2e/framework/framework.go:522
```

**Comment by dfarrell07** [comment]
https://github.com/submariner-io/submariner-operator/actions/runs/3441460981/jobs/5741026073
https://github.com/submariner-io/submariner-operator/actions/runs/3424272185
https://github.com/submariner-io/submariner-operator/actions/runs/3402441616
https://github.com/submariner-io/submariner-operator/actions/runs/3398171015

Some more recent failures.

**Comment by dfarrell07** [comment]
I think this is more specifically tracked by https://github.com/submariner-io/lighthouse/issues/1022
