### ISSUE TITLE
subctl should log the commands it tries to run

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#231]
When `subctl` runs `kubectl` and `kubefedctl`, it should log the commands it’s running, on higher verbosity levels and when running the command fails. This would greatly help debugging...

**Comment by mangelajo** [comment]
:+1: to this I was thinking the same thinking

**Comment by mangelajo** [comment]
Logging is now printed, and we don't use kubectl or kubefedctl anymore so I'm clossing this issue.
