### ISSUE TITLE
Add nodeSelector and toleration scheduling support for submariner

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#2362]
**What would you like to be added**:
Add some option to deploy submariner pods on specific nodes using nodeSelectors and tolerations.

**Why is this needed**:
Some customers want to run infra services like submariner on specific infra nodes. Running all submariner services on specific nodes also makes it easier for customers to secure networking on most nodes.

**Comment by dfarrell07** [comment]
This was done in https://github.com/submariner-io/submariner-operator/pull/2545, see also https://github.com/submariner-io/enhancements/issues/149. I think this just needs release notes before it can be closed.

**Comment by skitt** [comment]
It’s a bit late for release notes, closing.
