### ISSUE TITLE
The operator still needs to restart if CRDs are missing

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#2404]
**What happened**:

If some CRDs are missing, they are reported in the logs:

```
2022-12-13T07:23:17.190Z ERR ..kg/source/source.go:127 ..ler-runtime/source if kind is a CRD, it should be installed before calling Start error="no matches for kind \"Gateway\" in version \"submariner.io/v1\"" kind={"Group":"submariner.io","Kind":"Gateway"}
```

The operator then installs the CRDs and restarts.

**What you expected to happen**:

The operator is supposed to install the CRDs during initial startup, before it tries to use them, and work without requiring a restart.

**How to reproduce it (as minimally and precisely as possible)**:

Install the operator using the Submariner addon.

To test this in CI, and avoid regressions, we might want to add a “minimal CRDs” mode to `subctl` where it only sets up the CRDs which are absolutely necessary for operator startup (matching the OLM setup, that’s `Broker`, `Submariner`, and `ServiceDiscovery`; it might be possible to skip CRD installation in `subctl` altogether but that wouldn’t be particularly useful).

**Comment by tpantelis** [comment]
In operator [main.go](https://github.com/submariner-io/submariner-operator/blob/35e8bc7818acb1d73d2b8f55b7b06f843a534943/main.go#L126), it creates the CRDs on L128 and L135. This is before it creates the controller `Manager` and starts it (L231). So I'm not seeing the scenario and code described above where "CRDs are missing and the operator then installs the CRDs and restarts"...

**Comment by skitt** [comment]
> In operator [main.go](https://github.com/submariner-io/submariner-operator/blob/35e8bc7818acb1d73d2b8f55b7b06f843a534943/main.go#L126), it creates the CRDs on L128 and L135. This is before it creates the controller `Manager` and starts it (L231). So I'm not seeing the scenario and code described above where "CRDs are missing and the operator then installs the CRDs and restarts"...

I know, it doesn’t make sense, but I was seeing it with ACM deployments. I haven’t check whether this still happens with 0.14.

**Comment by tpantelis** [comment]
> I know, it doesn’t make sense, but I was seeing it with ACM deployments. I haven’t check whether this still happens with 0.14.

There's been changes to that code in the last 6 months, eg https://github.com/submariner-io/submariner-operator/pull/2180.

**Comment by skitt** [comment]
> > I know, it doesn’t make sense, but I was seeing it with ACM deployments. I haven’t check whether this still happens with 0.14.
> 
> There's been changes to that code in the last 6 months, eg #2180.

Yes, and I opened this issue because in spite of such changes (which successfully removed restarts in Submariner deployed using `subctl`), I still saw restarts when setting up Submariner using ACM.

**Comment by tpantelis** [comment]
> Yes, and I opened this issue because in spite of such changes (which successfully removed restarts in Submariner deployed using `subctl`), I still saw restarts when setting up Submariner using ACM.

Is is possible the operator version you were testing with didn't have the latest changes?

**Comment by skitt** [comment]
> > Yes, and I opened this issue because in spite of such changes (which successfully removed restarts in Submariner deployed using `subctl`), I still saw restarts when setting up Submariner using ACM.
> 
> Is is possible the operator version you were testing with didn't have the latest changes?

Ah, you’re right, I was foiled by the delayed bundle catalog updates...
