### ISSUE TITLE
Release subctl binary in tgz archive

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#257]
Usually github releases for each platform, are saved within tgz archive, but subctl is saved as binary, for example:
https://github.com/submariner-io/submariner-operator/releases/download/v0.1.1/subctl-v0.1.1-linux-amd64 

In order to use subctl as is, user should rename the downloaded file:
```
mv subctl-v0.1.1-linux-amd64 subctl
chmod +x subctl 
./subctl ...
```

If it was in tgz archive, it was just required to extract subctl from the archive.

**Comment by skitt** [comment]
With our current setup, this gives you a working binary:

    curl -Lo subctl https://github.com/submariner-io/submariner-operator/releases/download/v0.1.1/subctl-v0.1.1-linux-amd64
    chmod 755 subctl

You’d rather have

    curl -LO https://github.com/submariner-io/submariner-operator/releases/download/v0.1.1/subctl-v0.1.1-linux-amd64.tar.gz | tar xf -
    rm subctl-v0.1.1-linux-amd64.tar.gz

Is that correct? I don’t see the benefit...

**Comment by manosnoam** [comment]
Yes, that is correct, since users might try to download it in browser directly (not via curl/wget), and than will have to rename.

Keeping the archive with the platform-version name, is also efficient, to later know what was the original downloaded file.

It's also following the common github release formats (tgz / zip):
https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#editing-a-release

**Comment by manosnoam** [comment]
SubCtl releases are available in xz archive now.
