### ISSUE TITLE
subctl should return appropriate error message for invalid globalnet-cluster-size

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#258]
Currently, when subctl is passed globalnet-cluster-size of 33000 with default globalnet-cidr-range (i.e., 169.254.0.0/16), the error message returned is pretty confusing to the user. 

For example:
"Cluster size 65536 should be <= 32768"

**Comment by vthapar** [comment]
Subnet sizes are always power of two. So if user gives something like 8000, should we let them know that we're actually going to use 8192?
