### ISSUE TITLE
Add labels parameter to globalnet.CreateConfigMap

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#2636]
`CreateConfigMap` api in `pkg/discovery/globalnet/config_map.go` doesn't allow user to set any custom labels when creating configmap. To add a label user needs to create configmap, get and then update. It will be lot simpler and efficient to allow user to add custom labels at time of create itself.

So, add a parameter for labels to CreateConfigMap.

**Comment by vthapar** [comment]
@skitt Added some code to handle upgrade scenario where configmap exists but label does not.

**Comment by skitt** [comment]
> @skitt Added some code to handle upgrade scenario where configmap exists but label does not.

In relation to this issue?

**Comment by skitt** [comment]
Instead of adding specific support for labels (which wouldn’t be used in Submariner itself), it might be better to have `CreateConfigMap` return the created `ConfigMap`, so that it can be easily updated for any use-case.

**Comment by vthapar** [comment]
> > @skitt Added some code to handle upgrade scenario where configmap exists but label does not.
> 
> In relation to this issue?

Posted in wrong tab, scratch that.

> Instead of adding specific support for labels (which wouldn’t be used in Submariner itself), it might be better to have `CreateConfigMap` return the created `ConfigMap`, so that it can be easily updated for any use-case.

Yeah, was planning to make create return configmap anyhow. It would still be two api calls when single one would be simpler and efficient.

**Comment by tpantelis** [comment]
> > Instead of adding specific support for labels (which wouldn’t be used in Submariner itself), it might be better to have `CreateConfigMap` return the created `ConfigMap`, so that it can be easily updated for any use-case.
> 
> Yeah, was planning to make create return configmap anyhow. It would still be two api calls when single one would be simpler and efficient.

There's already a `NewGlobalnetConfigMap` function that returns a `ConfigMap`. We can change `CreateConfigMap` to take a `ConfigMap`, ie:

`func CreateConfigMap(ctx context.Context, client controllerClient.Client, configMap *corev1.ConfigMap) error`

**Comment by skitt** [comment]
> There's already a `NewGlobalnetConfigMap` function that returns a `ConfigMap`. We can change `CreateConfigMap` to take a `ConfigMap`, ie:
> 
> `func CreateConfigMap(ctx context.Context, client controllerClient.Client, configMap *corev1.ConfigMap) error`

But that would just be a wrapper for `client.Create(ctx, configMap)` — I’m not sure there’s much point. For scenarios where callers want to add data to the config map, it might be best to use `NewGlobalnetConfigMap()` and handle calls to `client.Create()` directly.

**Comment by tpantelis** [comment]
https://github.com/submariner-io/submariner-operator/pull/2637

**Comment by tpantelis** [comment]
> > There's already a `NewGlobalnetConfigMap` function that returns a `ConfigMap`. We can change `CreateConfigMap` to take a `ConfigMap`, ie:
> > `func CreateConfigMap(ctx context.Context, client controllerClient.Client, configMap *corev1.ConfigMap) error`
> 
> But that would just be a wrapper for `client.Create(ctx, configMap)` — I’m not sure there’s much point. For scenarios where callers want to add data to the config map, it might be best to use `NewGlobalnetConfigMap()` and handle calls to `client.Create()` directly.

https://github.com/submariner-io/submariner-operator/pull/2637

**Comment by tpantelis** [comment]
> But that would just be a wrapper for `client.Create(ctx, configMap)` — I’m not sure there’s much point. For scenarios where callers want to add data to the config map, it might be best to use `NewGlobalnetConfigMap()` and handle calls to `client.Create()` directly.

yeah I thought that too. The additional thing `CreateConfigMap` would provide is `IsAlreadyExists` convenience check. But I'm fine either way.

**Comment by tpantelis** [comment]
So really, we can leave `CreateConfigMap` as is and nothing needs to be done.
