### ISSUE TITLE
A new submariner-operator release

### ISSUE THREAD

**Issue by roytman** [submariner-io/submariner-operator#275]
Recently we added the flag to define Submariner cable driver. Unfortunately it is not part of the latest release, but `Submariner` e2e tests use the submariner-operator release binaries. 

Could you please create a new `submariner-operator` release.

BTW, should we update `DefaultSubmarinerOperatorVersion` and `DefaultSubmarinerVersion`, currently they are 0.1.1 ?

**Comment by dfarrell07** [comment]
I think the plan is to do a 0.2.0 release with all of the new globalnet features on Monday. :+1:
