### ISSUE TITLE
Report status in the cable driver

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#281]
This is related to #102.

Cable drivers (IPSec, WireGuard etc.) need to be able to report detailed status, in particular whether the tunnel(s) we need are up. This will involve adding data structures and APIs, as well as implementing the necessary support in the drivers themselves (which should be additional issues).

This depends on https://github.com/submariner-io/submariner/issues/308

**Comment by skitt** [comment]
This depends on https://github.com/submariner-io/submariner/issues/308

**Comment by mangelajo** [comment]
> This depends on [submariner-io/submariner#308](https://github.com/submariner-io/submariner/issues/308)

Or the other way around :-)

**Comment by skitt** [comment]
The status is now reported by the engine and copied by the operator into its status object.
