### ISSUE TITLE
Improve the current auto-allocation mechanism of globalCIDR in subctl

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#299]
Currently, subctl tries to automatically allocate a globalCIDR chunk from the un-allocated globalnet-cidr-range to a cluster during join operation. Inorder to do this, it depends on the submariner clusterCRD on the Broker. However, for the clusterCRD to be populated by the respective cluster on the Broker usually takes sometime. Because of this, we are unable to execute "subctl join ...." commands in parallel. 

This issue is to enhance the current implementation to use an appropriate mechanism like a  ConfigMap that stores the [clusterName: globalCIDR] on the Broker cluster and use this info instead of depending on clusterCRD.

**Comment by sridhargaddam** [comment]
@Jaanki since you will be going on vacation, shall I look into this issue?

**Comment by Jaanki** [comment]
Sure @sridhargaddam. I have half of the logic implemented at PR #475.

**Comment by manosnoam** [comment]
In addition to having auto-generated CIDRs, please also alert the user if trying to use same globalnet-cidr for two clusters. (i.e. subctl join command should fail for such case.)

**Comment by Jaanki** [comment]
@Noam, the current implementation does that.

**Comment by sridhargaddam** [comment]
> Sure @sridhargaddam. I have half of the logic implemented at PR #475.

Done, I pushed a PR which addresses this issue along with some other use-cases.
Added you as co-author.
https://github.com/submariner-io/submariner-operator/pull/501

**Comment by sridhargaddam** [comment]
> In addition to having auto-generated CIDRs, please also alert the user if trying to use same globalnet-cidr for two clusters. (i.e. subctl join command should fail for such case.)

Yes @manosnoam, it's handled. Please let us know if you find any issues.

**Comment by manosnoam** [comment]
@sridhargaddam Now that it is closed, can I remove the static "wait" of 30 seconds - before joining another cluster (when using globalnet) ?

@nyechiel, @mangelajo 
Since this is kind of feature to be tested by QE, I re-open it, and assign to myself.
(as we discussed, it's important to move finished features to test, before closing)

**Comment by sridhargaddam** [comment]
> @sridhargaddam Now that it is closed, can I remove the static "wait" of 30 seconds - before joining another cluster (when using globalnet) ?
> 

Yes @manosnoam . You can remove any sleep as well as remove the globalnet-cidr as part of subctl join command. The CIDRs will be auto-allocated.

> @nyechiel, @mangelajo
> Since this is kind of feature to be tested by QE, I re-open it, and assign to myself.
> (as we discussed, it's important to move finished features to test, before closing)

Ack

**Comment by manosnoam** [comment]
This works well on 0.5.0. 
Thanks @sridhargaddam
