### ISSUE TITLE
Gateway fails to create an instance

### ISSUE THREAD

**Issue by adibrastegarnia** [submariner-io/submariner-operator#2999]
I have one control plane kind cluster to deploy broker and two other kind clusters as members to join broker. Everything gets deployed and I can export services and the dns record is also added but the clusters cannot communicate with each other. The gateway shows an error every few minutes. When I join the clusters I also set natt to false. 

```
 Error creating gateway instance error="error creating local endpoint object: could not determine public IP: Unable to resolve public IP by any of the resolver methods: [\nResolver[\"api:4.icanhazip.com\"]: retrieving public IP from https://4.icanhazip.com: Get \"https://4.icanhazip.com\": context deadline exceeded (Client.Timeout exceeded while awaiting headers), \nResolver[\"api:ifconfig.me\"]: retrieving public IP from https://ifconfig.me: Get \"https://ifconfig.me\": context deadline exceeded (Client.Timeout exceeded while awaiting headers), \nResolver[\"api:4.ident.me\"]: retrieving public IP from https://4.ident.me: Get \"https://4.ident.me\": context deadline exceeded (Client.Timeout exceeded while awaiting headers), \nResolver[\"api:api.ipify.org\"]: retrieving public IP from https://api.ipify.org:
```

Would you please give me some insights why in the kind clusters the gateway should look for public ip address?

**Comment by skitt** [comment]
In order to set up a tunnel between gateways, the gateways have to be able to connect to each other. In the absence of NAT traversal, each gateway needs a public IP address, and we use a number of external APIs to determine that IP address automatically. See https://submariner.io/operations/nat-traversal/ for details.

**Comment by adibrastegarnia** [comment]
Thanks for your response @skitt . Let me look into it in more details and I will ask questions if I run into big issues.

**Comment by dfarrell07** [comment]
Looks like this has resolved, feel free to re-open and ping us if you have more questions.
