### ISSUE TITLE
Operator fail to update coredns configmap in rke2

### ISSUE THREAD

**Issue by adibrastegarnia** [submariner-io/submariner-operator#3005]
**What happened**:
According to this document, https://submariner.io/operations/usage/, coredns configmap in kube-system should be updated automatically to forward requests sent for the clusterset.local domain to the to Lighthouse CoreDNS Server in the cluster. However, I noticed that the name of configmap is hardcoded to "coredns" based on the following code. 

https://github.com/submariner-io/submariner-operator/blob/devel/controllers/servicediscovery/servicediscovery_controller.go#L68

How does that work for rke2 enviroment where the name is prefixed with rke2? (i.e rke2-coredns) 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by adibrastegarnia** [comment]
@skitt  since you are a major contributor to the project, would you please advise on this issue?

**Comment by adibrastegarnia** [comment]
I managed to fix it by overriding the name of the rke2-coredns chart but would be nice to support it by default.

**Comment by vthapar** [comment]
@adibrastegarnia This looks similar to an issue we fixed back for AKS https://github.com/submariner-io/submariner-operator/issues/1046

You can set the `customCoreDNSName` field in ServiceDiscovery CR to `rke2-coredns`. The hardcoded constant is used as default if none specified in `customCoreDNSName` .

If using subctl to join, you can set it using following flag:

```
 --coredns-custom-configmap string           Name of the custom CoreDNS configmap to configure forwarding to lighthouse. It should be in <namespace>/<name> format where <namespace> is optional and defaults to kube-system
```
Let us know if this worked for you.

**Comment by adibrastegarnia** [comment]
@vthapar  for some reasons that flag is not listed in subctl document. I haven't tried it yet to see if it is available that is why I asked the question in the first place.

**Comment by tpantelis** [comment]
> @vthapar for some reasons that flag is not listed in subctl document. I haven't tried it yet to see if it is available that is why I asked the question in the first place.

yeah it's not described on the [doc site](https://submariner.io/operations/deployment/subctl/) - unfortunately that has gotten a bit stale in some parts. `subctl join --help` is the source of truth.
