### ISSUE TITLE
Failed to build subctl with a non-root user 

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#319]
When trying to build subctl on a clean environment without sudo privilege, the "make build-operator" command will fail, if Docker is not pre-installed.

```
$ make build-operator

./.dapper -m bind make build-operator 
time="2020-04-20T15:51:44Z" level=fatal msg="exec: \"docker\": executable file not found in $PATH"
make: *** [build-operator] Error 1
```

A side note:
In order to install Docker, a sudo user is also required, even if using the [rootless docker installer](https://docs.docker.com/engine/security/rootless/), since Docker itself requires `sudo yum install -y shadow-utils46-newxidmap`.

**Comment by manosnoam** [comment]
@skitt, @dfarrell07, @nyechiel 
Is Docker (and Dapper) required for running the Submariner unit-tests, or is it a must for compiling a subctl binary ?

Can't we just support a compilation of subctl - without Dapper ?

**Comment by skitt** [comment]
> Is Docker (and Dapper) required for running the Submariner unit-tests, or is it a must for compiling a subctl binary ?

It’s possible, yes, if you install all the build dependencies with exactly the right versions.

> Can't we just support a compilation of subctl - without Dapper ?

We’ve chosen not to support compilation without Dapper. People who want to, can figure out how to do it (I build without Dapper quite often), but we don’t want to support it or (for now) document it.

**Comment by manosnoam** [comment]
Thanks @skitt 
As you suggested, I've replaced `make bin/subctl` - as it requires pre-installation of Docker (with non-root user) - to:
```
GO111MODULE="on" go mod vendor
go mod vendor
./scripts/generate-embeddedyamls
./scripts/build-subctl
```
