### ISSUE TITLE
Migrate to kubebuilder go/v4 project layout

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#3282]
Operator SDK 1.38 drops support for the go/v3 project layout, which is the layout currently used in the Submariner operator. To upgrade to 1.38, the project needs to migrate to go/v4, either by [creating a new v4 project](https://book.kubebuilder.io/migration/migration_guide_gov3_to_gov4) and copying the APIs and code to the new layout, or by [moving the relevant files to the new layout](https://book.kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4).

See [the v1.38.0 release notes](https://github.com/operator-framework/operator-sdk/releases/tag/v1.38.0) for details.

**Comment by dfarrell07** [comment]
@skitt What prio/timeline do you think this should be done in?

**Comment by skitt** [comment]
I don’t think there’s any rush, but as usual with SDK changes, the longer it gets pushed back, the harder it will likely be to catch up.
