### ISSUE TITLE
Add more cluster information to subctl info

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#359]
Currently `subctl info` only shows cluser network information. It is not enough to know current status of deployment and is missing other useful information too. It should be enhanced to show additional information like:

1. Status of all services/daemonsets, gateways including which node is current leader etc.
2. Connectivity status
3. Cable driver in-use.
4. Anything else that is useful in determining health of deployment and/or helps with initial troubleshooting.

**Comment by mangelajo** [comment]
@maayanf24 if you comment on the issue I can assign it to you, since you're looking at it.

**Comment by maayanf24** [comment]
I'm working on this issue

**Comment by mangelajo** [comment]
@maayanf24 see the comment here: https://groups.google.com/forum/#!topic/submariner-dev/EEyaG5iDg6M now we have submariner-io/enhancements repo where we can add the document explaining the plan.

**Comment by manosnoam** [comment]
Will `subctl info` become deprecated ?
If so, please add it to the docs too, thanks!
