### ISSUE TITLE
subctl: Add an option to collect troubleshooting info

### ISSUE THREAD

**Issue by vthapar** [submariner-io/submariner-operator#360]
Add an option to `subctl` to collect all the info and logs that would be required to troubleshoot issues. This could be, but not limited to:

1. Logs of all submariner pods
2. Output of `subctl info`
3. Contents of submariner CRs like endpoints, clusters, multiclusterservices etc.
4. IP Table rules configured
5. IPSec tunnel information

Aim is that user should be able to run single command to gather all this information without having to collect it all individually. It can also be combined with some diagnostics and only collect logs relevant for failures. e.g. only collect route-agent logs if connectivity not working etc.

**Comment by mangelajo** [comment]
I think this one is closely related, or implements a good subset of this proposal: https://github.com/submariner-io/submariner-operator/issues/359
