### ISSUE TITLE
Adopt shipyard's build image

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#361]
Adopt it to build the operator image

**Comment by skitt** [comment]
We use the operator SDK to build the operator image, so I’m not sure how useful the Shipyard image building tools would be. See also https://github.com/submariner-io/submariner-operator/pull/363.

**Comment by mkolesnik** [comment]
In light of #363 the image would be so slim that it won't matter I guess, so we can close this issue.
