### ISSUE TITLE
Epic: Add OLM deployment CI coverage

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-operator#373]
Add CI for deploying Submariner via submariner-operator via OLM. This would replicate the experience of a user finding Submariner on OperatorHub, or the community-operators CI.

https://dev.operatorhub.io/operator/submariner
https://github.com/operator-framework/community-operators/pull/1677/checks?check_run_id=648885925

**Comment by dfarrell07** [comment]
Maybe this is actually how to get at the idea: https://github.com/operator-framework/community-operators/blob/master/docs/using-scripts.md

**Comment by skitt** [comment]
That’s what I’d based my patch to install OLM on.

**Comment by skitt** [comment]
https://github.com/submariner-io/submariner/pull/134

**Comment by dfarrell07** [comment]
> [submariner-io/submariner#134](https://github.com/submariner-io/submariner/pull/134)

Ah, nice, I had forgotten about that one! You're a few steps ahead of me as always. :wink: So it seems we need to do something like what you have there in Shipyard now?

**Comment by skitt** [comment]
There are two parts to the issue:

* deploying OLM & co in our test K8s clusters (this is what submariner-io/submariner/#134 does, and what needs to be replicated in Shipyard)
* using OLM to deploy Submariner

The latter should IMO be done in `subctl` (because the goal is to use OLM when deploying on OpenShift, in all cases), but whether done directly in CI or in `subctl`, there are some subtleties involved. We can’t use the operator CSV from OperatorHub because we want to deploy the Submariner components that CI needs to test, not those available on Quay and referred to by the current OperatorHub CSV.

**Comment by mangelajo** [comment]
> There are two parts to the issue:
> 
> * deploying OLM & co in our test K8s clusters (this is what submariner-io/submariner/#134 does, and what needs to be replicated in Shipyard)
> * using OLM to deploy Submariner
> 
> The latter should IMO be done in `subctl` (because the goal is to use OLM when deploying on OpenShift, in all cases), but whether done directly in CI or in `subctl`, there are some subtleties involved. We can’t use the operator CSV from OperatorHub because we want to deploy the Submariner components that CI needs to test, not those available on Quay and referred to by the current OperatorHub CSV.

Makes sense, I stumble into this the other day:

https://github.com/che-incubator/chectl#chectl-serverstart

I don't mean we need to take the chectl things as a reference, I have't analyzed them in terms of usability, but .. they do support operator or olm... (even helm). I think we should "auto" by default, and use olm with priority if that's available.

**Comment by dfarrell07** [comment]
@skitt @mangelajo do either of you guys have a suggestion for how to properly depend on the released CRDs/other resources that comprise OLM? I'm messing with a patch to subctl, but I'm a bit stuck trying to figure out the right way to do pull in their artifacts that can be easily maintained/updated in Go.

I'd basically like to do:

```
kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.1/crds.yaml --validate=false
```

using `utils.CreateOrUpdateCRD`

and

```
kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.1/olm.yaml
```

without duplicating all of those definitions in Go, ie *not* paralleling https://github.com/submariner-io/submariner-operator/blob/master/pkg/subctl/operator/submarinerop/serviceaccount/ensure.go.

**Comment by skitt** [comment]
@dfarrell07 why do you want to deploy OLM from `subctl`?

**Comment by dfarrell07** [comment]
@skitt I saw your point about OLM via Shipyard, but it seemed like it should be pretty straightforward from subctl, for a released version at least. Just parallel CRD/resource creations to what we already do. And it seemed like it would make sense from a UX sandpoint, to have the ability to install OLM and then the operator via OLM all via subctl.

But I guess this shows it's not as easy as I imagined and it should just be deployed via Shipyard.

**Comment by skitt** [comment]
@dfarrell07 what I mean is that OLM is a means to an end, not an end to itself. I think `subctl` should be able to use OLM to install the operator, _if OLM is already present_. I don’t think `subctl` should install OLM itself to install the operator.

**Comment by dfarrell07** [comment]
@skitt the first part of this seems to be almost ready via https://github.com/submariner-io/submariner/pull/134. For the second part, does it make sense to you to deploy a custom OLM catalog/registry to enable OLM deploys with non-released Submariner versions? https://github.com/operator-framework/operator-registry#building-an-index-of-operators-using-opm

**Comment by mangelajo** [comment]
> @dfarrell07 what I mean is that OLM is a means to an end, not an end to itself. I think `subctl` should be able to use OLM to install the operator, _if OLM is already present_. I don’t think `subctl` should install OLM itself to install the operator.

Agreed

**Comment by skitt** [comment]
> @skitt the first part of this seems to be almost ready via [submariner-io/shipyard#175](https://github.com/submariner-io/shipyard/pull/175). For the second part, does it make sense to you to deploy a custom OLM catalog/registry to enable OLM deploys with non-released Submariner versions? https://github.com/operator-framework/operator-registry#building-an-index-of-operators-using-opm

There used to be a way to add a local catalog entry without pushing a custom catalog, I don’t know if that’s still possible but it would be much easier than the whole custom catalog thing. I’ll look into it once I’ve finished Libreswan.

**Comment by dfarrell07** [comment]
@skitt @mangelajo If you get a chance, am I on the right track with https://github.com/submariner-io/submariner-operator/pull/432? There are still TODOs stubbed out (and tests failing because of them), but wanted to get feedback before pushing on too far.
