### ISSUE TITLE
Analyze if our SCC settings block openshift updates

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#377]
Cluster network seems to do it this way:

https://github.com/openshift/cluster-network-operator/commit/a7d8f9d8f90c4061599c4dabe5bd3c56506d3ea6

This is what we currently do: https://github.com/submariner-io/submariner-operator/blob/753b7003b4b02905815fd68da660dc0e1908067c/pkg/subctl/operator/submarinerop/scc/ensure.go#L52

**Comment by nyechiel** [comment]
This was tested successfully recently. Closing for now.
