### ISSUE TITLE
./scripts/build-subctl failed since it runs git outside repo directory

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#390]
This issue is related to bug: https://github.com/submariner-io/submariner/issues/576

```
SCRIPTS_DIR=./scripts ./scripts/build-subctl
[submariner-operator]$ source ./scripts/lib/version
[submariner-operator]$ git status --porcelain --untracked-files=no
[submariner-operator]$ export COMMIT=a357c14
[submariner-operator]$ git rev-parse --short HEAD
[submariner-operator]$ export GIT_TAG=
[submariner-operator]$ git tag -l --contains HEAD
[submariner-operator]$ head -n 1
[submariner-operator]$ export VERSION=dev
[submariner-operator]$ cd
[jenkins]$ go env GOOS
[jenkins]$ go env GOARCH
Building subctl version dev for linux/amd64
[jenkins]$ GIT_REF=
[jenkins]$ git describe --tags
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by skitt** [comment]
You need to set `DAPPER_SOURCE`.

**Comment by manosnoam** [comment]
Can we change:
https://github.com/submariner-io/submariner-operator/blob/9f39a35c95a6227162c7a3aaa4250e5f2aaf975a/Dockerfile.dapper#L6

So instead of:
`DAPPER_SOURCE=/go/src/github.com/submariner-io/submariner-operator`

It will be:
`DAPPER_SOURCE=$(git rev-parse --show-toplevel)`

**Comment by skitt** [comment]
Why do you want to change it?

**Comment by manosnoam** [comment]
I could resolve current issue by running before the build, inside the submariner-operator path:
`export DAPPER_SOURCE=$(git rev-parse --show-toplevel)`

On a side note, I think you can change above line in Dockerfile.dapper, so it will have a general path for DAPPER_SOURCE, instead of hardcoded "/go/src/..."

**Comment by skitt** [comment]
I know why you’re suggesting `git rev-parse ...`, but I don’t understand why you want to change the definition in the container construction.

**Comment by mangelajo** [comment]
We don't support building outside of dapper, let's look for other solutions.
