### ISSUE TITLE
scripts/compile.sh: No such file or directory

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#391]
Trying to build recent submariner-operator repo, fails on missing scripts/compile.sh :

```
export DAPPER_SOURCE="$(git rev-parse --show-toplevel)"
# DAPPER_SOURCE=/home/jenkins/go/src/github.com/submariner-io/submariner-operator
SCRIPTS_DIR=./scripts ./scripts/build-subctl

[submariner-operator]$ source ./scripts/lib/version
[submariner-operator]$ git status --porcelain --untracked-files=no
[submariner-operator]$ export COMMIT=a357c14
[submariner-operator]$ git rev-parse --short HEAD
[submariner-operator]$ export GIT_TAG=
[submariner-operator]$ git tag -l --contains HEAD
[submariner-operator]$ head -n 1
[submariner-operator]$ export VERSION=dev
[submariner-operator]$ cd /home/jenkins/go/src/github.com/submariner-io/submariner-operator
[submariner-operator]$ go env GOOS
[submariner-operator]$ go env GOARCH
Building subctl version dev for linux/amd64
[submariner-operator]$ GIT_REF=v0.3.0-17-ga357c14
[submariner-operator]$ git describe --tags
[submariner-operator]$ ldflags=-X github.com/submariner-io/submariner-operator/pkg/version.Version=dev 
[submariner-operator]$ ldflags=-X github.com/submariner-io/submariner-operator/pkg/version.Version=dev  -X github.com/submariner-io/submariner-operator/pkg/version.GitRef=v0.3.0-17-g
[submariner-operator]$ output=bin/subctl-dev-linux-amd64
[submariner-operator]$ ./scripts/compile.sh --ldflags -X github.com/submariner-io/submariner-operator/pkg/version.Version=dev  -X github.com/submariner-io/submariner-operator/pkg/version.GitRef=v0.3.0-17-ga357c14 bin/subctl-dev-linux-amd64 ./pkg/subctl/main.go
./scripts/build-subctl: line 18: ./scripts/compile.sh: No such file or directory
```

**Comment by skitt** [comment]
See https://github.com/submariner-io/submariner/issues/576#issuecomment-630663843 — `SCRIPTS_DIR` must point to _shipyard_’s shared scripts.

**Comment by manosnoam** [comment]
Trying to use shipyard compile.sh, I get:
```
[submariner]$ ./scripts/compile.sh --ldflags -X main.VERSION=dev bin/submariner-engine main.go
./scripts/compile.sh: line 7: syntax error near unexpected token `newline'
./scripts/compile.sh: line 7: `<!DOCTYPE html>'
```

And generally asking, if shipyard is a separate repository, shouldn't we make submariner-operator repository independent from it, at least for the compilation process?

**Comment by skitt** [comment]
Please try to use the commands I’m suggesting. You’ve mis-downloaded `compile.sh`, your file contains HTML, not the shell script.

You need to clone the shipyard repository alongside your submariner repository, and set `SCRIPTS_DIR` to the absolute path of the shared scripts in the shipyard repository.

> And generally asking, if shipyard is a separate repository, shouldn't we make submariner-operator repository independent from it, at least for the compilation process?

That resulted in loads of duplication, and lots of maintenance issues. We’ve chosen to use shipyard as the common foundation for all projects.

**Comment by mangelajo** [comment]
We don't support building outside of dapper, let's look for other solutions.
