### ISSUE TITLE
Update operator  in community-operators

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-operator#393]
https://github.com/operator-framework/community-operators/pull/1761

**Comment by Jaanki** [comment]
https://github.com/operator-framework/community-operators/pull/1761

**Comment by SteveMattar** [comment]
up

**Comment by SteveMattar** [comment]
https://github.com/operator-framework/community-operators/pull/2132 was merged

**Comment by nyechiel** [comment]
Closing this one. @SteveMattar will report a new one for v0.5.
