### ISSUE TITLE
Lighthouse Operator status

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner-operator#396]
Add support track the status of the various resources created by Lighthouse operator.

These are some of the PR for the operator in submariner.
1)https://github.com/submariner-io/submariner-operator/pull/328/
2)https://github.com/submariner-io/submariner-operator/pull/292
3)https://github.com/submariner-io/submariner-operator/pull/310

**Comment by dfarrell07** [comment]
@aswinsuryan Can you help me understand what Lighthouse-related things would be most helpful to report the status of?

**Comment by aswinsuryan** [comment]
Enhancements that can be considered are

Lighthouse Agent
1)Agent pod status needs to be monitored 
2)The deployment needs to be checked to see if the actual and expected state is the same.

Lighthouse DNS Server
1)DNS pod status needs to be monitored
2)The LighthouseDNS service needs to be monitored and we need to ensure the cluster IP configured in kube-dns config map is correct. The status of the service needs to be monitored as well.
3)The Lightouse core-DNS configmap needs to be checked to see if expected and actual is same.
4)The deployment needs to be checked to see if the actual and expected state is the same.
