### ISSUE TITLE
Subctl's verify doesn't return error on fail

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#424]
It seems that, at least for some cases, the command will return code 0 even though no tests were run due to a failure.

E.G.
```
Ran 18 of 18 Specs in 0.553 seconds
FAIL! -- 0 Passed | 18 Failed | 0 Pending | 0 Skipped
[root@120da1d6e363 submariner-operator]# echo $?
0
```

You can see it in this CI log where the verify failed, but the whole job succeeded (since subctl returned 0): [log.txt](https://github.com/submariner-io/submariner-operator/files/4710428/log.txt)

**Comment by vthapar** [comment]
Fixed by https://github.com/submariner-io/submariner-operator/pull/423
