### ISSUE TITLE
Github "pre-release" link is missing from releases

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#425]
Github releases has a link "latest release":
![image](https://user-images.githubusercontent.com/9913945/83397668-ad271480-a406-11ea-8da5-207328ec02e1.png)
Pointing to: https://github.com/submariner-io/submariner-operator/releases/latest

But it should also have a link "pre-release" under releases, like this one:
![image](https://user-images.githubusercontent.com/9913945/83398075-58d06480-a407-11ea-965e-a0736f72646f.png)

Which should redirect to here:
https://github.com/submariner-io/submariner-operator/releases/tag/pre-release
(instead of https://github.com/submariner-io/submariner-operator/releases/tag/latest )

**Comment by manosnoam** [comment]
The "Pre-release" orange tag is not a clickable link

**Comment by mkolesnik** [comment]
> The "Pre-release" (orange label) is not a clickable link, like the Latest-release (green label)
> 
> ![image](https://user-images.githubusercontent.com/9913945/83604007-15e4cd00-a57e-11ea-841d-8831a81b9d7e.png)

You seem to misunderstand ho GH works, please read their guide to managing releases
https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository
