### ISSUE TITLE
subctl fails if the API broker certificate is signed by an unknown authority

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#451]
On a working OCP setup, `subctl join` connects successfully to the cluster, but fails when retrieving the global network details with

    Get "https://.../apis/submariner.io/v1/namespaces/submariner-k8s-broker/clusters": x509: certificate signed by unknown authority

**Comment by skitt** [comment]
This might be submariner-io/submariner-operator#244 again.

**Comment by mangelajo** [comment]
Could it be related to subctl reusing a subctl broker config file?. Was it possible to capture get reproducer steps?

**Comment by skitt** [comment]
The certificate chain is rooted in a self-signed certificate:

* Issuer: OU = openshift, CN = kube-apiserver-lb-signer
* Issuer: OU = openshift, CN = kube-apiserver-localhost-signer
* Issuer: OU = openshift, CN = kube-apiserver-service-network-signer
* Issuer: CN = openshift-kube-apiserver-operator_localhost-recovery-serving-signer@1591774743

The service CA doesn’t help:

* Issuer: OU = openshift, CN = kube-apiserver-lb-signer
* Issuer: OU = openshift, CN = kube-apiserver-localhost-signer
* Issuer: OU = openshift, CN = kube-apiserver-service-network-signer
* Issuer: CN = openshift-kube-apiserver-operator_localhost-recovery-serving-signer@1591774743
* Issuer: CN = openshift-service-serving-signer@1591774746

**Comment by skitt** [comment]
But all that’s irrelevant, what matters is the endpoint’s certificate chain... In this particular instance, that certificate chain uses the Let’s Encrypt CA, so it should be OK.

**Comment by mangelajo** [comment]
May be something we can do is try both.... we attempt using the CA, if that doesn't work, we try without the CA (assuming public CA signature...) ... if that woks, we make sure that any later request happens without the CA.

**Comment by mangelajo** [comment]
I guess we would have the same issue later with submariner, so we may want to avoid setting up the CA in that case too.

**Comment by skitt** [comment]
Exactly, we need to try without the explicit trust chain, then with it, from any client trying to access the broker externally.

**Comment by mikekuzak** [comment]
Hi, I'm getting the same error with an in-house deployment on Rancher. Rancher is using a self generated CA. Is there a way in the join command to omit the CA checking ? 

```
* broker-info.subm says broker is at: https://uk1-rancher/k8s/clusters/c-64h5m
* There are 1 labeled nodes in the cluster:
  - uk1-k8swkr01
⢎⡰ Discovering network details         Network plugin:  canal-flannel
        Service CIDRs:   [10.43.0.0/16]
        Cluster CIDRs:   [10.42.0.0/16]
 ✓ Discovering network details
Error retrieving broker admin config: Get "https://uk1-rancher/k8s/clusters/c-64h5m/apis/submariner.io/v1/namespaces/submariner-k8s-broker/clusters": x509: certificate signed by unknown authority

subctl version: v0.11.2
```

**Comment by skitt** [comment]
@mikekuzak not yet, but we do have this in the backlog: submariner-io/subctl#52
