### ISSUE TITLE
Flaky test failures

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-operator#461]
Used for tracking flaky test failures.

**Comment by sridhargaddam** [comment]
> /cc @sridhargaddam

thanks a lot @dfarrell07 for reporting this issue and capturing the logs. I'll take a look and update the observations.

**Comment by dfarrell07** [comment]
Np @sridhargaddam, thanks for digging into them.

One more, from https://github.com/submariner-io/submariner/pull/621. 

```
[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod with HostNetworking connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139

[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139
```
Job: e2e (globalnet, operator, wireguard)
Logs: https://pastebin.com/u5q1Y1YY

**Comment by dfarrell07** [comment]
Repo: Admiral
Job: make e2e using="globalnet helm"
Error: E2E connectivity test failure
Logs: https://pastebin.com/1UFGuQyj

This one was noted by @mangelajo. There have been quite a few others, as I'm sure folks have seen.

**Comment by dfarrell07** [comment]
A few more I had noticed recently:

https://pastebin.com/RMDcnBQz
https://pastebin.com/hQRRqVUg
https://pastebin.com/8EDbQ7UZ

**Comment by sridhargaddam** [comment]
Some of the failures captured in this issue will be addressed via - https://github.com/submariner-io/shipyard/pull/229

**Comment by dfarrell07** [comment]
Thanks for the ongoing outstanding work in this regard @sridhargaddam!

One more I observed today:

make e2e using="globalnet helm "
https://pastebin.com/9wJWdMyi

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/701
Job: `make e2e using="globalnet operator libreswan"`
Logs: https://pastebin.com/ukRtTafG
Summary: `[Fail] [redundancy] Gateway fail-over tests when one gateway node is configured and the submariner engine pod fails [It] should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/tcp/connectivity.go:48`

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/706
Job: `make e2e using="globalnet operator libreswan"`
Logs: https://pastebin.com/UWvCY6Rg
Summary: `[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355`

**Comment by sridhargaddam** [comment]
> PR: [submariner-io/submariner#706](https://github.com/submariner-io/submariner/pull/706)
> Job: `make e2e using="globalnet operator libreswan"`
> Logs: https://pastebin.com/UWvCY6Rg
> Summary: `[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster /go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355`

Thank you @dfarrell07 
This seems to be some intermittent failure with libreswan cable driver and is not related to Globalnet.

**Failed to await Gateway on "cluster2-worker2" with status active and connections UP. Gateway "cluster2-worker2" exist but connection to cluster "cluster1" is not up yet**

**Comment by dfarrell07** [comment]
Okay, thanks @sridhargaddam! I changed the title to remove "globalnet", since I'm not really trying to tease out the different failures here. I'm just collecting them as I see them until we have better sources of metrics.

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/712
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/VmeJ4aFX
Summary: `test timed out after 15m0s`

**Comment by sridhargaddam** [comment]
> [redundancy]

This issue will be resolved by the following PRs
https://github.com/submariner-io/submariner-operator/pull/514
https://github.com/submariner-io/submariner-charts/pull/50

**Comment by sridhargaddam** [comment]
> PR: [submariner-io/submariner#712](https://github.com/submariner-io/submariner/pull/712)
> Job: `make e2e using=" operator wireguard"`
> Logs: https://pastebin.com/VmeJ4aFX
> Summary: `test timed out after 15m0s`

This is vanilla Submariner job and as @dfarrell07 pointed out, the test timed out after 15 mins.
@mangelajo @skitt @tpantelis : Does the following PR fix this issue?
https://github.com/submariner-io/shipyard/pull/250

**Comment by dfarrell07** [comment]
This one is showing up A LOT the last week or so:

```
[submariner]$ cache_flag+= --cache-from registry.fedoraproject.org/fedora-minimal:32
[submariner]$ docker pull registry.fedoraproject.org/fedora-minimal:32
32: Pulling from fedora-minimal
manifest for registry.fedoraproject.org/fedora-minimal:32 not found: manifest unknown: manifest unknown
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/713
Job: `make e2e using=" operator libreswan"`
Logs: https://pastebin.com/CyH4kGYp
Summary:
```
[Fail] [redundancy] Gateway fail-over tests when any gateway node is configured [It] should be reported to the Gateway API 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/710
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/WPPeYX9U
Summary:
```
Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139

[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:108
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner-operator/pull/587
Job: `make e2e using="globalnet lighthouse"`
Logs: https://pastebin.com/mwgVaxkZ
Summary:
```
[Fail] [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service in a remote cluster [It] should be able to discover the remote service successfully 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355

[Fail] [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service which is present locally and in a remote cluster [It] should resolve the local service 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner-operator/pull/585/
Job: `make e2e using=" lighthouse"`
Logs: https://pastebin.com/Xigh4xaz
Summary:
```
[Fail] [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service in a remote cluster [It] should be able to discover the remote service successfully 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:58

[Fail] [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service which is present locally and in a remote cluster [It] should resolve the local service 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:99
```

**Comment by dfarrell07** [comment]
I haven't observed any flaky failures since the last update two weeks ago. Great job @sridhargaddam and team! :1st_place_medal:

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/771
Job: `make e2e using="globalnet operator wireguard"`
Logs: https://pastebin.com/AzC4wyEr
Summary: `Failed to await Gateway on "cluster2-worker" with status active and connections UP. Gateway "cluster2-worker" exist but connection to cluster "cluster3" is not up yet`

**Comment by sridhargaddam** [comment]
> PR: [submariner-io/submariner#771](https://github.com/submariner-io/submariner/pull/771)
> Job: `make e2e using="globalnet operator wireguard"`
> Logs: https://pastebin.com/AzC4wyEr
> Summary: `Failed to await Gateway on "cluster2-worker" with status active and connections UP. Gateway "cluster2-worker" exist but connection to cluster "cluster3" is not up yet`

From the logs, it appears like there is an issue in setting up tunnels with **wireguard.** Would be great if someone familiar with Wireguard driver takes a close look and share their comments.

2020-08-24T16:17:16.7433087Z [cluster2]     uid: 9da8d574-d051-4934-a2ab-1629767b8a5b
2020-08-24T16:17:16.7433222Z [cluster2]   status:
2020-08-24T16:17:16.7433347Z [cluster2]     connections:
2020-08-24T16:17:16.7433608Z [cluster2]     - endpoint:
2020-08-24T16:17:16.7433734Z [cluster2]         backend: wireguard
2020-08-24T16:17:16.7433864Z [cluster2]         backend_config:
2020-08-24T16:17:16.7433993Z [cluster2]           LastChecked: "1598284924766"
2020-08-24T16:17:16.7434116Z [cluster2]           ReceiveBytes: "0"
2020-08-24T16:17:16.7434246Z [cluster2]           TransmitBytes: "444"
2020-08-24T16:17:16.7434383Z [cluster2]           publicKey: GOhN7FRSr485A8qThvY1I4MOcmt5aTcb7tH5uFQt7zw=
2020-08-24T16:17:16.7434721Z [cluster2]         cable_name: submariner-cable-cluster3-172-17-0-10
2020-08-24T16:17:16.7434861Z [cluster2]         cluster_id: cluster3
2020-08-24T16:17:16.7435151Z [cluster2]         hostname: cluster3-worker
2020-08-24T16:17:16.7435433Z [cluster2]         nat_enabled: false
2020-08-24T16:17:16.7435567Z [cluster2]         private_ip: 172.17.0.10
2020-08-24T16:17:16.7435681Z [cluster2]         public_ip: ""
2020-08-24T16:17:16.7435805Z [cluster2]         subnets:
2020-08-24T16:17:16.7436091Z [cluster2]         - 169.254.3.0/24
2020-08-24T16:17:16.7436220Z [cluster2]       **status: error**
2020-08-24T16:17:16.7436356Z [cluster2]       statusMessage: **no initial handshake for 908.8 seconds**
2020-08-24T16:17:16.7522346Z [cluster2]     haStatus: active
2020-08-24T16:17:16.7522469Z [cluster2]     localEndpoint:
2020-08-24T16:17:16.7522580Z [cluster2]       backend: wireguard
2020-08-24T16:17:16.7522706Z [cluster2]       backend_config:
2020-08-24T16:17:16.7522846Z [cluster2]         publicKey: V+QSgFWPqpR88rF2HGOHoUgZwi9zrg4QIUXzqRmaJj8=
2020-08-24T16:17:16.7523624Z [cluster2]       cable_name: submariner-cable-cluster2-172-17-0-6
2020-08-24T16:17:16.7523769Z [cluster2]       cluster_id: cluster2
2020-08-24T16:17:16.7524057Z [cluster2]       hostname: cluster2-worker
2020-08-24T16:17:16.7524187Z [cluster2]       nat_enabled: false
2020-08-24T16:17:16.7524313Z [cluster2]       private_ip: 172.17.0.6
2020-08-24T16:17:16.7524424Z [cluster2]       public_ip: ""
2020-08-24T16:17:16.7524545Z [cluster2]       subnets:
2020-08-24T16:17:16.7524821Z [cluster2]       - 169.254.2.0/24
2020-08-24T16:17:16.7524953Z [cluster2]     statusFailure: ""
2020-08-24T16:17:16.7525452Z [cluster2]     version: ""
2020-08-24T16:17:16.7525596Z [cluster2] kind: List
2020-08-24T16:17:16.7525769Z [cluster2] metadata:
2020-08-24T16:17:16.7525878Z [cluster2]   resourceVersion: ""
2020-08-24T16:17:16.7526064Z [cluster2]   selfLink: ""

`2020-08-24T16:17:27.2468249Z [cluster3] E0824 16:02:02.521694       1 tunnel.go:114] Tunnel controller failed to process submariner Endpoint with key "submariner-operator/cluster2-submariner-cable-cluster2-172-17-0-6": error installing cable for Endpoint types.SubmarinerEndpoint{Spec:v1.EndpointSpec{ClusterID:"cluster2", CableName:"submariner-cable-cluster2-172-17-0-6", Hostname:"cluster2-worker", Subnets:[]string{"169.254.2.0/24"}, PrivateIP:"172.17.0.6", PublicIP:"", NATEnabled:false, Backend:"wireguard", BackendConfig:map[string]string(nil)}}, failed to parse peer public key: endpoint is missing public key
`

**Comment by mangelajo** [comment]
About the wireguard failures, I remember that wireguard eventually updates the Endpoint on the broker with a public key, and then the other clusters get this endpoint with the new public key... may be this is failing at some point?

**Comment by roytman** [comment]
Ok, let us check it

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/267
Job: `make e2e using=" operator"`
Logs: https://pastebin.com/5wvqb5Nq
Summary: `Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service in a remote cluster [It] should resolve the backing pod IPs from the remote cluster`

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/270
Job: `make e2e using=" helm"`
Logs: https://pastebin.com/cauFeLCU
Summary: `error: error validating "/tmp/coremap-cluster2.yaml": error validating data: kind not set`

PR: https://github.com/submariner-io/lighthouse/pull/270
Job: `make e2e using="globalnet helm"`
Logs: https://pastebin.com/hiMsUAFn
Summary: `error: error validating "/tmp/coremap-cluster1.yaml": error validating data: kind not set`

**Comment by dfarrell07** [comment]
> PR: [submariner-io/lighthouse#270](https://github.com/submariner-io/lighthouse/pull/270)
> Job: `make e2e using=" helm"`
> Logs: https://pastebin.com/cauFeLCU
> Summary: `error: error validating "/tmp/coremap-cluster2.yaml": error validating data: kind not set`
> 
> PR: [submariner-io/lighthouse#270](https://github.com/submariner-io/lighthouse/pull/270)
> Job: `make e2e using="globalnet helm"`
> Logs: https://pastebin.com/hiMsUAFn
> Summary: `error: error validating "/tmp/coremap-cluster1.yaml": error validating data: kind not set`

These actually seem to be consistent. /cc @vthapar

**Comment by mangelajo** [comment]
Job: make e2e using="globalnet"
Logs: https://pastebin.com/3egQa5EC
Summary: 
```
[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod
9107
```

(on 0.6.0/0.6.1)

**Comment by sridhargaddam** [comment]
> Job: make e2e using="globalnet"
> Logs: https://pastebin.com/3egQa5EC

Looks like the logs were truncated, not able to find the failure/globalnet logs.

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/773
Job: `make e2e using=" operator libreswan"`
Logs: https://pastebin.com/njxsaACN
Summary:
```
[Fail] [redundancy] Gateway fail-over tests when any gateway node is configured [It] should be reported to the Gateway API 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355

[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:355
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/827
Job: `make e2e using=" helm "`
Logs: https://pastebin.com/s4gP1UP7
Summary: 
```
[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:139
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/314
Job: `make e2e using=" helm"`
Logs: https://pastebin.com/hHmCmr1L
Summary: `[cluster2] Error: unexpected EOF`

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner-operator/pull/728
Job: `make e2e using=" lighthouse"`
Logs: https://pastebin.com/VqkdsQDe
Summary: `Max attempts reached, failed to run 'test_connection netshoot-789f6cf54f-c2rbp 100.91.164.213'!`

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/327
Job: `make e2e using=" helm"`
Logs: https://pastebin.com/7aJdrCew
Summary: 
```
[Fail] [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service which is exported locally and in a remote cluster [It] should resolve the backing pod IPs from both clusters 
/go/src/github.com/submariner-io/lighthouse/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:371
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/865
Job: `make e2e using=" helm "`
Logs: https://pastebin.com/yDcZafEk
Summary:
```
[cluster1] Error: failed to download "submariner-latest/submariner"
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/896
Job: `make e2e using="globalnet helm "`
Logs: https://pastebin.com/fMAC36DM
Summary:
```
[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [redundancy] Gateway fail-over tests when any gateway node is configured [It] should be reported to the Gateway API 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [redundancy] Gateway fail-over tests when one gateway node is configured and the submariner engine pod fails [It] should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/897
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/1Wyq8WwY
Summary:
```
[Fail] [redundancy] Gateway fail-over tests [AfterEach] when one gateway node is configured and the submariner engine pod fails should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/899
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/mfdDb4pX
Summary: 
```
Failure [195.399 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
/go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:9
  when a pod connects via TCP to a remote service
  /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:55
    when the pod is on a gateway and the remote service is on a gateway
    /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:73
      should have sent the expected data from the pod to the other pod [It]
      /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:15

      Expected
          <int32>: 1
      to equal
          <int32>: 0

      /go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/899
Job: `make e2e using=" operator libreswan"`
Logs: https://pa stebin.com/qRm4YJd8
Summary:
```
Failure [196.146 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
/go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:9
  when a pod connects via TCP to a remote pod
  /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:32
    when the pod is on a gateway and the remote pod is not on a gateway
    /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:46
      should have sent the expected data from the pod to the other pod [It]
      /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:15

      Expected
          <int32>: 1
      to equal
          <int32>: 0
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/899
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/hXy6qDhY
Summary:
```
STEP: Cleaning up any non-active gateways: [cluster2-worker2]
Failure [0.000 seconds]
[AfterSuite] AfterSuite 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/e2e.go:38

  Failed to await Gateway on "cluster2-worker2" removed
  Unexpected error:
      <*errors.errorString | 0xc0002e4390>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred

  /go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/900
Job: make e2e using=" operator libreswan"
Logs: https://pastebin.com/XnQqzcSA
Summary:
```
Failure [0.000 seconds]
[AfterSuite] AfterSuite 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/e2e.go:38

  Failed to await Gateway on "cluster2-worker2" removed
  Unexpected error:
      <*errors.errorString | 0xc000274390>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred

  /go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/894
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/pGVkBVeR
Summary:
```
[Fail] [redundancy] Gateway fail-over tests [AfterEach] when one gateway node is configured and the submariner engine pod fails should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/891
Job: `make e2e using=" operator wireguard"`
Logs: https://pastebin.com/2mQsWA4d
Summary: 
```
Failure [195.288 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery
/go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:9
  when a pod connects via TCP to a remote pod
  /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:32
    when the pod is on a gateway and the remote pod is on a gateway
    /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:50
      should have sent the expected data from the pod to the other pod [It]
      /go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:15

      Expected
          <int32>: 1
      to equal
          <int32>: 0

      /go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/891
Job: `make e2e using=" operator libreswan"`
Logs: https://pastebin.com/mCqxQ5y8
Summary: 
```
[Fail] [redundancy] Gateway fail-over tests [AfterEach] when one gateway node is configured and the submariner engine pod fails should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159

[Fail] [redundancy] Gateway fail-over tests when a new node is labeled as a gateway node and the label on the existing gateway node is removed [It] should start a submariner engine on the new gateway node and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/test/e2e/redundancy/gateway_failover.go:115
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/884
Job: `make e2e using=" operator libreswan"`
Logs: https://pastebin.com/WLTWys3M
Summary:
```
[Fail] [redundancy] Gateway fail-over tests [AfterEach] when one gateway node is configured and the submariner engine pod fails should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by roytman** [comment]
Hi I checked all the wireguard failures and some of libreswan, all of thems have the following error:
```
[91mFailed to await Gateway on "cluster2-worker2" removed
2020-10-26T16:10:07.6838002Z     Unexpected error:
2020-10-26T16:10:07.6838556Z         <*errors.errorString | 0xc000278390>: {
2020-10-26T16:10:07.6839654Z             s: "timed out waiting for the condition",
2020-10-26T16:10:07.6840131Z         }
2020-10-26T16:10:07.6840602Z         timed out waiting for the condition
2020-10-26T16:10:07.6841251Z     occurred[0m
```
This include comments:
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716696988
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716738830
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716761890
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716764104  libreswan
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716768263
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716772683  
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716773485  libreswan
https://github.com/submariner-io/submariner-operator/issues/461#issuecomment-716774729  libreswam

It is something driver independend

**Comment by dfarrell07** [comment]
This recent set of failures seems to have been fixed by https://github.com/submariner-io/submariner/pull/906. Thanks all!

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner/pull/915
Job: `make e2e using=" operator libreswan"`
Logs: https://pastebin.com/rJ5vkz0G
Summary:
```
[Fail] [redundancy] Gateway fail-over tests when one gateway node is configured and the submariner engine pod fails [It] should start a new submariner engine pod and be able to connect from another cluster 
/go/src/github.com/submariner-io/submariner/vendor/github.com/submariner-io/shipyard/test/e2e/framework/network_pods.go:159
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/releases/pull/41
Job: `make e2e using="globalnet"`
Logs: https://pastebin.com/Hf7Ky0BT
Summary:
```
[Fail] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
/releases/projects/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/tcp/connectivity.go:58
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/360
Job: `make e2e using=" operator"`
Logs: https://pastebin.com/1uUfuv3r
Summary: 
```
[Fail] [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service in a remote cluster [It] should resolve the backing pod IPs from the remote cluster 
/go/src/github.com/submariner-io/lighthouse/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/360
Job: `make e2e using=" operator"`
Logs: https://pastebin.com/tee7Wiqs
Summary:
```
[Fail] [discovery] Test Service Discovery Across Clusters when service export is created before the service [It] should resolve the service 
/go/src/github.com/submariner-io/lighthouse/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/lighthouse/pull/360
Job: `make e2e using=" helm"`
Logs: https://pastebin.com/eHxd3GbK
Summary:
```
[Fail] [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service in a remote cluster [It] should resolve the backing pod IPs from the remote cluster 
/go/src/github.com/submariner-io/lighthouse/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner-operator/pull/724
Job: `make e2e using=" lighthouse"`
Logs: https://pastebin.com/Sta8DeXw
Summary: 
```
[Fail] [discovery] Test Service Discovery Across Clusters when there are active pods for a service in only one cluster [It] should not resolve the service on the cluster without active pods 
/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by dfarrell07** [comment]
PR: https://github.com/submariner-io/submariner-operator/pull/786
Job: `make upgrade-e2e`
Logs: https://pastebin.com/0TnweZ3Q
Summary: 
```
Max attempts reached, failed to run 'test_connection netshoot-789f6cf54f-4whn5 100.1.105.96'!
```
