### ISSUE TITLE
Subctl: change subctl info cmd to subctl show networks

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#467]
This is sub-issue of  https://github.com/submariner-io/submariner-operator/issues/359

See enhancement: https://github.com/submariner-io/enhancements/blob/master/submariner-operator/issue-359-subctl-info-status.md

**Comment by mangelajo** [comment]
@manosnoam this part is merged now, I added you as QE and added the QE label

**Comment by manosnoam** [comment]
Thanks @maayanf24 and @mangelajo 
Will it work when KUBECONFIG points to more than one cluster (i.e. merged KUBECONFIG) ?

**Comment by manosnoam** [comment]
On subctl version: dev - built from git ref: devel-1-g6dc3413
I get 
```
subctl show networks
Error: unknown command "show" for "subctl"
```

**Comment by skitt** [comment]
> On subctl version: dev - built from git ref: devel-1-g6dc3413
> I get
> 
> ```
> subctl show networks
> Error: unknown command "show" for "subctl"
> ```

... which is perfectly normal, you built v0.4.0 (6dc2413 is the tagged commit). You need at least 0eb4ab8a.

**Comment by manosnoam** [comment]
I've downloaded and extracted that version this morning (after #493 was already merged) from:
https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-dev-linux-amd64.tar.xz

I'll try again...

**Comment by skitt** [comment]
The dev tarball publication is messed up, you need https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-v0.4.0-12-g0eb4ab8-linux-amd64.tar.xz
