### ISSUE TITLE
subctl show cmd: add subctl show all

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#472]
This is sub-issue of #359

See enhancement: https://github.com/submariner-io/enhancements/blob/master/submariner-operator/issue-359-subctl-info-status.md

**Comment by tpantelis** [comment]
Should we move to 0.6.0?

**Comment by maayanf24** [comment]
> Should we move to 0.6.0?

If it's too late to get in 0.5.0 then yes.
The PR is ready now
