### ISSUE TITLE
getsubctl.sh can get an unexpected argument 

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#473]
```
13:08:10 (conda-test) curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh | VERSION=devel bash

13:08:11 Installing subctl version devel
13:08:11   OS detected:           linux
13:08:11   Architecture detected: amd64
13:08:11   Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-dev-linux-amd64.tar.xz
13:08:11 
13:08:11 Downloading...
13:08:15 Got an unexpected argument: -D
```

Side note:
This happens on GO conda environment, on a rootless container.

**Comment by skitt** [comment]
This means that the version of `install` in the container doesn’t support `-D`. What version do you have? (`install --version`)

**Comment by manosnoam** [comment]
```
(conda-test) bash-4.2$ which install
/usr/bin/install
(conda-test) bash-4.2$ install --version
install (GNU coreutils) 8.22
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
(conda-test) bash-4.2$ install --help
Usage: install [OPTION]... [-T] SOURCE DEST
  or:  install [OPTION]... SOURCE... DIRECTORY
  or:  install [OPTION]... -t DIRECTORY SOURCE...
  or:  install [OPTION]... -d DIRECTORY...

This install program copies files (often just compiled) into destination
locations you choose.  If you want to download and install a ready-to-use
package on a GNU/Linux system, you should instead be using a package manager
like yum(1) or apt-get(1).

In the first three forms, copy SOURCE to DEST or multiple SOURCE(s) to
the existing DIRECTORY, while setting permission modes and owner/group.
In the 4th form, create all components of the given DIRECTORY(ies).

Mandatory arguments to long options are mandatory for short options too.
      --backup[=CONTROL]  make a backup of each existing destination file
  -b                  like --backup but does not accept an argument
  -c                  (ignored)
  -C, --compare       compare each pair of source and destination files, and
                        in some cases, do not modify the destination at all
  -d, --directory     treat all arguments as directory names; create all
                        components of the specified directories
  -D                  create all leading components of DEST except the last,
                        then copy SOURCE to DEST
  -g, --group=GROUP   set group ownership, instead of process' current group
  -m, --mode=MODE     set permission mode (as in chmod), instead of rwxr-xr-x
  -o, --owner=OWNER   set ownership (super-user only)
  -p, --preserve-timestamps   apply access/modification times of SOURCE files
                        to corresponding destination files
  -s, --strip         strip symbol tables
      --strip-program=PROGRAM  program used to strip binaries
  -S, --suffix=SUFFIX  override the usual backup suffix
  -t, --target-directory=DIRECTORY  copy all SOURCE arguments into DIRECTORY
  -T, --no-target-directory  treat DEST as a normal file
  -v, --verbose       print the name of each directory as it is created
  -P, --preserve-context  preserve SELinux security context (-P deprecated)
  -Z                      set SELinux security context of destination
                            file to default type
      --context[=CTX]     like -Z, or if CTX is specified then set the
                            SELinux or SMACK security context to CTX
      --help     display this help and exit
      --version  output version information and exit

The backup suffix is '~', unless set with --suffix or SIMPLE_BACKUP_SUFFIX.
The version control method may be selected via the --backup option or through
the VERSION_CONTROL environment variable.  Here are the values:

  none, off       never make backups (even if --backup is given)
  numbered, t     make numbered backups
  existing, nil   numbered if numbered backups exist, simple otherwise
  simple, never   always make simple backups

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Report install translation bugs to <http://translationproject.org/team/>
For complete documentation, run: info coreutils 'install invocation'

```

**Comment by skitt** [comment]
That’s strange, `-D` should work... Can you change the invocation to

    curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh | VERSION=devel bash -x

to see what happens in detail?

**Comment by manosnoam** [comment]
```
11:47:24 (conda-test) curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh
11:47:25 (conda-test) VERSION=devel bash -x
11:47:25 + set -e
11:47:25 ++ download_command
11:47:25 ++ command_exists curl
11:47:25 ++ command -v curl
11:47:25 ++ echo 'curl -fsSL'
11:47:25 + get='curl -fsSL'
11:47:25 + VERSION=devel
11:47:25 ++ get_operating_system
11:47:25 ++ case $(uname -s) in
11:47:25 +++ uname -s
11:47:25 ++ echo linux
11:47:25 + os=linux
11:47:25 ++ get_architecture
11:47:25 ++ case $(uname -m) in
11:47:25 +++ uname -m
11:47:25 ++ echo amd64
11:47:25 + architecture=amd64
11:47:25 ++ get_subctl_release_url
11:47:25 ++ local draft_filter=cat
11:47:25 ++ local url
11:47:25 ++ case ${VERSION} in
11:47:25 ++ url=https://api.github.com/repos/submariner-io/submariner-operator/releases/tags/devel
11:47:25 ++ curl -fsSL https://api.github.com/repos/submariner-io/submariner-operator/releases/tags/devel
11:47:25 ++ grep 'browser_download_url.*-linux-amd64'
11:47:25 ++ cat
11:47:25 ++ head -n 1
11:47:25 ++ cut '-d"' -f 4
11:47:25 + url=https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-dev-linux-amd64.tar.xz
11:47:25 + echo 'Installing subctl version devel'
11:47:25 Installing subctl version devel
11:47:25 + echo '  OS detected:           linux'
11:47:25   OS detected:           linux
11:47:25 + echo '  Architecture detected: amd64'
11:47:25   Architecture detected: amd64
11:47:25 + echo '  Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-dev-linux-amd64.tar.xz'
11:47:25   Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-dev-linux-amd64.tar.xz
11:47:25 + echo ''
11:47:25 
11:47:25 + echo Downloading...
11:47:25 Downloading...
11:47:25 + trap finish_cleanup EXIT
11:47:25 + get_subctl
11:47:25 ++ mktemp -d
11:47:25 + tmpdir=/tmp/tmp.FL0lf1tbuI
11:47:25 + cd /tmp/tmp.FL0lf1tbuI
11:47:25 + case ${url} in
11:47:25 + curl -fsSL https://github.com/submariner-io/submariner-operator/releases/download/devel/subctl-dev-linux-amd64.tar.xz
11:47:25 + tar xfJ -
11:47:28 + install_subctl subctl-dev/subctl-dev-linux-amd64
11:47:28 + local bin=subctl-dev/subctl-dev-linux-amd64
11:47:28 + local bin_file
11:47:28 + local destdir=/home/jenkins/.local/bin
11:47:28 + local dest=/home/jenkins/.local/bin/subctl
11:47:28 + install -D subctl-dev/subctl-dev-linux-amd64 /home/jenkins/.local/bin/subctl
11:47:28 Got an unexpected argument: -D
11:47:28 + finish_cleanup
11:47:28 + '[' -z /tmp/tmp.FL0lf1tbuI ']'
11:47:28 + rm -rf /tmp/tmp.FL0lf1tbuI
```

**Comment by manosnoam** [comment]
Today it failed on:

curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh
<https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh%1B[0m>*17:39:48*
(conda-test) VERSION=devel bash -x

*17:39:48* + set -e*17:39:48* ++ download_command*17:39:48* ++
command_exists curl*17:39:48* ++ command -v curl*17:39:48* ++ echo
'curl -fsSL'*17:39:48* + get='curl -fsSL'*17:39:48* +
VERSION=devel*17:39:48* ++ get_operating_system*17:39:48* ++ case
$(uname -s) in*17:39:48* +++ uname -s*17:39:48* ++ echo
linux*17:39:48* + os=linux*17:39:48* ++ get_architecture*17:39:48* ++
case $(uname -m) in*17:39:48* +++ uname -m*17:39:48* ++ echo
amd64*17:39:48* + architecture=amd64*17:39:48* ++
get_subctl_release_url*17:39:48* ++ local draft_filter=cat*17:39:48*
++ local url*17:39:48* ++ case ${VERSION} in*17:39:48* ++
url=https://api.github.com/repos/submariner-io/submariner-operator/releases/tags/devel*17:39:48*
++ curl -fsSL https://api.github.com/repos/submariner-io/submariner-operator/releases/tags/devel*17:39:48*
++ grep 'browser_download_url.*-linux-amd64'*17:39:48* ++
cat*17:39:48* ++ head -n 1*17:39:48* ++ cut '-d"' -f 4*17:39:49* curl:
(22) The requested URL returned error: 403 rate limit
exceeded*17:39:49* + url=*17:39:49* + echo 'Installing subctl version
devel'*17:39:49* Installing subctl version devel*17:39:49* + echo '
OS detected:           linux'*17:39:49*   OS detected:
linux*17:39:49* + echo '  Architecture detected: amd64'*17:39:49*
Architecture detected: amd64*17:39:49* + echo '  Download URL:
 '*17:39:49*   Download URL:          *17:39:49* + echo ''*17:39:49*
*17:39:49* + echo Downloading...*17:39:49* Downloading...*17:39:49* +
trap finish_cleanup EXIT*17:39:49* + get_subctl*17:39:49* ++ mktemp
-d*17:39:49* + tmpdir=/tmp/tmp.MjwnpWJJAP*17:39:49* + cd
/tmp/tmp.MjwnpWJJAP*17:39:49* + case ${url} in*17:39:49* ++ basename
''*17:39:49* + filename=*17:39:49* + curl -fsSL ''*17:39:49* bash:
line 78: : No such file or directory*17:39:49* +
finish_cleanup*17:39:49* + '[' -z /tmp/tmp.MjwnpWJJAP ']'*17:39:49* +
rm -rf /tmp/tmp.MjwnpWJJAP

**Comment by skitt** [comment]
@manosnoam could you format that correctly?

**Comment by manosnoam** [comment]
Updated (sorry it was sent from email previously)

**Comment by skitt** [comment]
The failure is caused by GitHub rate-limiting:

> curl: (22) The requested URL returned error: 403 rate limit exceeded

**Comment by mangelajo** [comment]
as per meeting let's print 

`install --version` and `install --help` to see what it prints.

**Comment by manosnoam** [comment]
This is what's going on - it uses GO install command from gobin path:

```
which install
/mnt/skynet-data/ocp-install/GOBIN/install

install --version
Got an unexpected argument: --version
```

Can you change `install` to `/usr/bin/install` ?

-------------------------------

BTW, the **_curl error 403 rate limit exceeded_**, is a diffrent error, which happens, but rarely, so it's a different story.

**Comment by skitt** [comment]
> This is what's going on - it uses GO install command from gobin path:
> 
> ```
> which install
> /mnt/skynet-data/ocp-install/GOBIN/install
> 
> install --version
> Got an unexpected argument: --version
> ```
> 
> Can you change `install` to `/usr/bin/install` ?

Why is `/mnt/skynet-data/ocp-install/GOBIN` on the path? Are there any other commands in there which would cause problems?

> BTW, the **_curl error 403 rate limit exceeded_**, is a diffrent error, which happens, but rarely, so it's a different story.

I know...

**Comment by manosnoam** [comment]
My env has it's GO installed locally for current non-root user (with conda), and I've added GOBIN to path, since it includes other binaries, such as AWS-CLI and OC client (maybe I should rename "GOBIN" to "LOCAL-BIN"). 

Is there's an option to specify install path, before running the script:

`install=/usr/bin/install curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh | VERSION=devel bash -x`

?

**Comment by manosnoam** [comment]
Actually, this GOBIN/install is from AWS-CLI:

```
/mnt/skynet-data/ocp-install/GOBIN/install --help 
Installs the AWS CLI v2

USAGE:
    install [FLAGS] [OPTIONS]

FLAGS:
    -u, --update              Updates the AWS CLI v2 if a different version
                              is previously installed. By default, this script
                              will not update the AWS CLI if a previous
                              installation is detected.

    -h, --help                Prints help information

OPTIONS:
    -i, --install-dir <path>  The directory to install the AWS CLI v2. By
                              default, this directory is: /usr/local/aws-cli

    -b, --bin-dir <path>      The directory to store symlinks to executables
                              for the AWS CLI v2. By default, the directory
                              used is: /usr/local/bin
```

**Comment by skitt** [comment]
How about adding `GOBIN` to the _end_ of your `PATH`? That way the system `install` would be picked ahead of the AWS CLI `install`.

**Comment by manosnoam** [comment]
> How about adding `GOBIN` to the _end_ of your `PATH`? That way the system `install` would be picked ahead of the AWS CLI `install`.

I did that in purpose, so in case there is an old binary in the system path (e.g. oc client 4.1), a new binary installed in local GOBIN, will be the one being executed.

**Comment by manosnoam** [comment]
> `curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh | VERSION=devel PATH="/usr/bin:$PATH" bash -x`

This seems to work well, perhaps we can add it to the Docs.

**Comment by skitt** [comment]
> > `curl -Ls https://raw.githubusercontent.com/submariner-io/submariner-operator/master/scripts/subctl/getsubctl.sh | VERSION=devel PATH="/usr/bin:$PATH" bash -x`
> 
> This seems to work well, perhaps we can add it to the Docs.

No, the docs shouldn’t address your specific environment (with your non-standard `PATH`), otherwise they’d also have to address every other user’s specific environment.

What the docs _could_ usefully do is document the tools used by `getsubctl.sh`.
