### ISSUE TITLE
subctl benchmark

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#494]
This is an enhancement request to add benchmarking capabilities to `subctl`, _e.g._ as a `benchmark` subcommand. This would use `iperf` in the netshoot images to test bandwidth between clusters, with options to control the deployment node (gateway v. non-gateway) and the `iperf` options (initial window size, TCP v. UDP, number of parallel streams...).

**Comment by pinikomarov** [comment]
hey @skitt any thoughts about adding induced latency into the testing matrix of this PR ?
like here : 
https://bencane.com/2012/07/16/tc-adding-simulated-network-latency-to-your-linux-server/
This just simulates remote data-centres connectivity..

**Comment by skitt** [comment]
@pinikomarov this is just a basic enhancement request for now, I haven’t thought of the test matrix yet ;-). But your point is definitely one to bear in mind, it would be useful to make sure that the benchmark actually varies, so a test with traffic shaping would be worthwhile.

**Comment by nyechiel** [comment]
Hi @skitt - with @maayanf24 working on https://github.com/submariner-io/enhancements/pull/6, should we close this one?

**Comment by skitt** [comment]
> Hi @skitt - with @maayanf24 working on [submariner-io/enhancements#6](https://github.com/submariner-io/enhancements/pull/6), should we close this one?

I think this should be closed once the implementation of submariner-io/enhancements#6 is merged ;-).

**Comment by nyechiel** [comment]
> > Hi @skitt - with @maayanf24 working on [submariner-io/enhancements#6](https://github.com/submariner-io/enhancements/pull/6), should we close this one?
> 
> I think this should be closed once the implementation of [submariner-io/enhancements#6](https://github.com/submariner-io/enhancements/pull/6) is merged ;-).

Then what is the difference between this Issue and https://github.com/submariner-io/submariner-website/issues/40? ;)

**Comment by nyechiel** [comment]
> > > Hi @skitt - with @maayanf24 working on [submariner-io/enhancements#6](https://github.com/submariner-io/enhancements/pull/6), should we close this one?
> > 
> > 
> > I think this should be closed once the implementation of [submariner-io/enhancements#6](https://github.com/submariner-io/enhancements/pull/6) is merged ;-).
> 
> Then what is the difference between this Issue and [submariner-io/submariner-website#40](https://github.com/submariner-io/submariner-website/issues/40)? ;)

(which interestingly enough, was reported against submariner-website repo, as I see now)

**Comment by skitt** [comment]
> > Then what is the difference between this Issue and [submariner-io/submariner-website#40](https://github.com/submariner-io/submariner-website/issues/40)? ;)
> 
> (which interestingly enough, was reported against submariner-website repo, as I see now)

Exactly that, I think the appropriate place for this is the operator, not the website.

**Comment by manosnoam** [comment]
Thanks @maayanf24 
I will follow the documentation: https://github.com/submariner-io/submariner-website/pull/274/files

And will verify this feature.

**Comment by manosnoam** [comment]
Opened https://github.com/submariner-io/shipyard/issues/336 to run benchmark on our OSP-AWS env.
