### ISSUE TITLE
Handle upgrades for globalnet config moved to configMap

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#504]
As part of issue#[299](https://github.com/submariner-io/submariner-operator/issues/299), globalnet config params shown below are moved to configMap (submariner-globalnet-info) on the Broker cluster.
So far this information was stored as part of broker-info.subm file and was referred to during 'subctl join' operation.
Once issue#299 is addressed, subctl will refer to configMap instead of broker-info.subm file.
This could create issues when users try to execute the latest subctl on existing clusters.
This PR is to support seamless upgrade from subctl-0.4 to subctl-0.5

**Params:**
GlobalnetStatus
globalnet-cidr-range
globalnet-cluster-size
globalCIDR allocations of connected clusters

**Comment by nyechiel** [comment]
@sridhargaddam @vthapar as discussed in the team call, please document this as part of the v0.5 release notes: https://github.com/submariner-io/submariner-website/issues/193
