### ISSUE TITLE
Subctl "--ginkgo.option" flag to pass Ginkgo test params

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#509]
Currently subctl test connectivity does not create Junit output file.
This is related to: https://github.com/submariner-io/shipyard/issues/48#issuecomment-651639505_

Can we add an option to pass `-ginkgo.reportFile` to subctl command ?

For example, this is how I run E2E with Ginkgo directly:
`go test -v ./test/e2e -args --dp-context nmanos-cluster-a --dp-context nmanos-cluster-b --submariner-namespace submariner-operator --connection-timeout 30 -connection-attempts 3 -ginkgo.v -ginkgo.randomizeAllSpecs -ginkgo.reportPassed -ginkgo.reportFile /mnt/skynet-data/ocp-install/e2e_junit_result.xml`

In general, it would be useful if we can pass **any** ginkgo param (not only "reportFile").
This will allow to run subctl with custom Ginkgo options.

Note: If passing Ginkgo `-focus` flag then it might interrupt later with `subctl --only` flag, as both make filter on which packages to run, I believe.

**Comment by pinikomarov** [comment]
@mangelajo hey , about this issue, where in the submariner-operator, should we introduce a change to fix this ? 
Thanks

**Comment by pinikomarov** [comment]
the change should be in : 
shipyard: scripts/shared/e2e.sh

**Comment by pinikomarov** [comment]
@manosnoam I talked with Miguel and he said we have to be very specific with the flags we add
so what flags do we want here  ?

**Comment by mangelajo** [comment]
@manosnoam @pinikomarov you can start with `--report-file` being added, please don't use `--ginkgo.XXXX` this is an end user tool, and the end user should not care about what's the internal library we use to drive the tests.
