### ISSUE TITLE
Handle upgrades 0.4->0.5 in ServiceDiscovery for globalnet flag

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#510]
See: https://github.com/submariner-io/submariner-operator/pull/488 

During upgrades we don't have a mechanism to re-calculate the globalnet flag of ServiceDiscovery that we auto-generate from submariner.

If we don't have time to finish this before release we may include a note about editing ServiceDiscovery and setting the flag.

**Comment by vthapar** [comment]
We currently do not support upgrades. Upgrading from 0.4.0 to 0.5.0 is addition of a new flag `GlobalnetEnabled` in Lighthouse CR. Without this flag ServiceDiscovery will not work across clusters with overlapping CIDRs. Fresh 0.5.0 installations won't have this issue.

WORKAROUND:
Add `GlobalnetEnabled=true` to ServiceDiscovery step.

TODO: Add exact command to set the flag.

**Comment by mangelajo** [comment]
Oh, wait, we auto-create the ServiceDiscovery for submariner, the submariner controller loop will reconcile this ServiceDiscovery on first run
