### ISSUE TITLE
Test subctl service-export

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#524]
This is the test task for feature: #465
subctl: add create service-export 

General note:
@vthapar , @aswinsuryan , @mangelajo 
Whenever you add a new feature, that should be verified by QE (as #465 feature) -
Please feel free to create such "Test task" with **QE** label, and assign it to me. Thanks!

**Comment by tpantelis** [comment]
This is labeled as part of the 0.5.0 project. Has it been completed or should it be moved to 0.6.0?

**Comment by nyechiel** [comment]
@manosnoam @pinikomarov can this be considered done at this point, or is there anything left to do here?

**Comment by manosnoam** [comment]
Yes, works great on 0.6
