### ISSUE TITLE
Generate a cluster id if one is not provided

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#539]
Currently we expect users to modify their kubeconfig context, before running subctl join with their chosen clusterId, otherwise the default openshift cluster context will stay "admin" on all clusters' kubeconfigs.

@mangelajo, @skitt
Can you set clusterId with a constant identifier of current cluster context, with some API call (instead of generating a random UUID that beeing hard to trace later) ?

This is related to:
https://github.com/submariner-io/submariner-operator/pull/8

**Comment by manosnoam** [comment]
@skitt thanks for adding a fix.
I will close this issue after verifying the fix.

**Comment by skitt** [comment]
Re-opening, Noam needs to verify this.

**Comment by manosnoam** [comment]
This is working great now on latest devel. 
No need to specify `--clusterid` for the join command:
'oc describe Submariner' shows for example: `Cluster ID:                 default-cl1`

**Comment by skitt** [comment]
This was implemented in 0.6.0, please don’t change the milestone. I’m not sure what to do about the project though ;-).
