### ISSUE TITLE
Rename --subm-debug flag for clarity

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#545]
Please rename the `subctl join` flag `--subm-debug` to something that better reflects the intent, eg `-enable-pod-debugging`.

This issue is related to:
https://github.com/submariner-io/submariner-operator/issues/474

And to:
https://github.com/submariner-io/submariner-operator/issues/544

**Comment by tpantelis** [comment]
As mentioned in #544, this flag is for enabling debug on resulting submariner pods so renaming to merely `debug` would make that less clear. I suggest `-enable-pod-debugging`.

**Comment by manosnoam** [comment]
@skitt thanks for adding PR to rename  `--subm-debug` to `--enable-pod-debugging`.
I will close this issue after I verify your change.

**Comment by skitt** [comment]
Re-opening so @manosnoam can check this.

**Comment by manosnoam** [comment]
@skitt Thanks for making sure UX bugs (such as this one) are not closed before QE verifies it.
I've verified the fix now.

**Comment by mangelajo** [comment]
Documentation for this issue is handled here, re-opening until doc is merged: https://github.com/submariner-io/submariner-website/pull/248

**Comment by mangelajo** [comment]
Well, clossing, I will make it's own card as I can't link the cross-repo PR to this issue.
