### ISSUE TITLE
submariner-operator does not configure CIDRs in openshift

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#557]
The root cause is that we need a ClusterRole assigned to the submariner-operator. This ClusterRole shoud permit
list/get access to ClusterNetwork openshift objects. We also need permissions to list/get pods and ConfigMaps (for flannel/weave config detection).

The submariner-route-agent is in crash loop (because it can't find the IP addresses).

**submariner-operator logs:**

{"level":"error","ts":1594291790.7272599,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"submariner-controller","request":"submariner-operator/submariner","error":"Submariner.submariner.io \"submariner\" is invalid: [status.clusterCIDR: Required value, status.serviceCIDR: Required value]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tsubmariner-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1594291792.9526892,"logger":"controller_submariner","msg":"Reconciling Submariner","Request.Namespace":"submariner-operator","Request.Name":"submariner"}
**I0709 10:49:52.961578       1 openshift4.go:47] Attempted network discovery for OpenShift4, no clusternetworks CRD
{"level":"info","ts":1594291795.7163284,"logger":"controller_submariner","msg":"No cluster network discovered"}
{"level":"info","ts":1594291795.7163618,"logger":"controller_submariner","msg":"No detected CIDR","type":"Cluster"}
{"level":"info","ts":1594291795.7163732,"logger":"controller_submariner","msg":"No detected CIDR","type":"Service"}**

**Comment by sridhargaddam** [comment]
@manosnoam this issue is now fixed. Can you please confirm that its working at your end, so that we can close this issue. Thanks.

**Comment by manosnoam** [comment]
Indeed, thank you!
