### ISSUE TITLE
subctl will offer you a master node when labeling nodes...

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#58]
We need to filter out non-worker nodes.

**Comment by skitt** [comment]
What should the criteria be? Specifically “worker” in the roles, or excluding roles we don’t care about (“master”)?

**Comment by mangelajo** [comment]
I'm not sure, could you investigate?, I'm not sure if they use "taints" for that, or if it's just the node role, because on some systems you can schedule pods to a "master" too, but not sure if there are extra roles.

**Comment by skitt** [comment]
> I'm not sure, could you investigate?, I'm not sure if they use "taints" for that, or if it's just the node role, because on some systems you can schedule pods to a "master" too, but not sure if there are extra roles.

Yes, there’s a master role, which leads to taints (but looking for the role is sufficient). Since our docs suggest labeling workers, perhaps we could look for workers, and if we find any, only suggest those, and if not, suggest any non-master node.

**Comment by tpantelis** [comment]
> > I'm not sure, could you investigate?, I'm not sure if they use "taints" for that, or if it's just the node role, because on some systems you can schedule pods to a "master" too, but not sure if there are extra roles.
> 
> Yes, there’s a master role, which leads to taints (but looking for the role is sufficient). Since our docs suggest labeling workers, perhaps we could look for workers, and if we find any, only suggest those, and if not, suggest any non-master node.

I used a label selector "!node-role.kubernetes.io/master" to weed out the master node for the E2E tests.

**Comment by manosnoam** [comment]
I'm using in my scripts:
`gw_node=$(kubconf_b oc get nodes -l node-role.kubernetes.io/worker | awk 'FNR == 2 {print $1}')`
