### ISSUE TITLE
Subctl / lighthouse code modifies existing ClusterRoles

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#583]
https://github.com/submariner-io/submariner-operator/blob/master/pkg/subctl/lighthouse/dns/ensure.go#L54
This will be problematic if later in runtime an operator update via OLM overwrites the existing ClusterRole with a new one.

This code should create a parallel one that we manage (either from OLM, subctl, or helm), instead of modifying existing ones that we don't own.

I see this in helm: https://github.com/submariner-io/submariner-charts/blob/master/submariner/templates/rbac.yaml#L115 but where is the equivalent for helm?

**Comment by aswinsuryan** [comment]
This seems to be missed during the cleanup , with the forward plugin we don't require to modify these cluster roles as kube-dns does not access mcs anymore.

For helm, we were not modifying in charts as helm does not support modification, we use to do it in LH deploy scripts and it was removed with  https://github.com/submariner-io/lighthouse/pull/160

**Comment by skitt** [comment]
This was fixed by https://github.com/submariner-io/submariner-operator/pull/584.
