### ISSUE TITLE
EPIC: High-availability Active/Passive issues

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#586]
This is an EPIC that captures some of the current issues we have in our HA Active/Passive solution.

1. **Fixed:** Shutdown path to be Optimized in Submariner Engine and route-agent
https://github.com/submariner-io/submariner/issues/694

2. **Fixed:** Modify updateStrategy for Route-agent Pods
https://github.com/submariner-io/submariner/issues/734

3. **Fixed:** Libreswan: Ensure IPSEC tunnel is not terminated when the Gateway POD is going down
https://github.com/submariner-io/submariner/issues/386

4.  **Fixed:** Operator restarting the Gateway Pods
https://github.com/submariner-io/submariner-operator/issues/516

5. **In Progress:** Datapath goes down when globalnet controller pod is restarted
https://github.com/submariner-io/submariner/issues/721

6. **Fixed:** Don't return IPs of services in disconnected clusters
https://github.com/submariner-io/lighthouse/issues/113

7. **Fixed:** Run tests and capture fail-over statistics in active/passive HA
https://github.com/submariner-io/submariner/issues/722

8. **Fixed:** Globalnet: Capture fail-over statistics in active/passive HA
https://github.com/submariner-io/submariner/issues/723

9. **Fixed:** Document HA failover times as a section on website?
https://github.com/submariner-io/submariner-website/issues/196

10. **Fixed:** Add round robin selection to IPs returned by lighthouse plugin
https://github.com/submariner-io/lighthouse/issues/114

11. **Fixed:** Support toleration/taint model for deployment too
https://github.com/submariner-io/submariner-operator/issues/147

12. **Fixed:** HA Status is "active" before Strongswan associations came up
https://github.com/submariner-io/submariner/issues/624

13. **Fixed:** subctl benchmark
https://github.com/submariner-io/submariner-operator/issues/494

**Comment by manosnoam** [comment]
CC @pinikomarov. This should have a test plan.

**Comment by sridhargaddam** [comment]
**For issue-1:** https://github.com/submariner-io/submariner/issues/694
Fix in Gateway Pod: https://github.com/submariner-io/submariner/pull/727
Fix in Route-agent Pod: https://github.com/submariner-io/submariner/pull/728

**Comment by sridhargaddam** [comment]
For issue-2: https://github.com/submariner-io/submariner/issues/734
Fix in submariner-operator: https://github.com/submariner-io/submariner-operator/pull/596

**Comment by sridhargaddam** [comment]
For issue-6: https://github.com/submariner-io/lighthouse/issues/113
Fix in lighthouse: https://github.com/submariner-io/lighthouse/pull/210

**Comment by sridhargaddam** [comment]
For issue-3: submariner-io/submariner#386

With **Libreswan**, we see that even after the EnginePod goes down (as part of restart), the tunnels are preserved on the node so datapath is not affected while the EnginePod is down until the current IKE SAs timeout (default of 1 hour). However, when the EnginePod is coming up, there is a brief disruption to the datapath (roughly 1 to 2 secs) when Libreswan is trying to re-establish new tunnels and negotiate new SAs to the remote peers. The effect of this is that TCP connections will retransmit whereas UDP will have a small datapath loss.

With **Strongswan**, as soon as enginePod is down, datapath is effected and is restored only after the EnginePod comes up.

There is a plan to change the default CableEngine to Libreswan once there is feature parity with strongswan. Considering that datapath is not affected with Libreswan (which is a plus point), I'm not sure if it's worth spending time debugging Strongswan datapath issue.

**Comment by sridhargaddam** [comment]
**For issue-4:** https://github.com/submariner-io/submariner-operator/issues/516
Fix in Submariner-operator: https://github.com/submariner-io/submariner-operator/pull/626

**Comment by sridhargaddam** [comment]
**For issue-5:** Datapath goes down when globalnet controller pod is restarted
Fix in Submariner repo: https://github.com/submariner-io/submariner/pull/762

**Comment by sridhargaddam** [comment]
**For issue-10:** Add round robin selection to IPs returned by lighthouse plugin
Fix in Lighthouse: https://github.com/submariner-io/lighthouse/pull/231

**Comment by sridhargaddam** [comment]
**For issue-7:** Run tests and capture fail-over statistics in active/passive HA
https://docs.google.com/spreadsheets/d/1JsXsyRDDXkp6t55Gm-NP5EggWTyYi2yo27pyuDYwlpc/edit

**Comment by sridhargaddam** [comment]
**For issue-8:** Globalnet: Capture fail-over statistics in active/passive HA
https://docs.google.com/spreadsheets/d/1JsXsyRDDXkp6t55Gm-NP5EggWTyYi2yo27pyuDYwlpc/edit

**Comment by sridhargaddam** [comment]
Closing this as most of the issues are resolved.
