### ISSUE TITLE
CoreDNS configmap is not updated when Submariner is reinstalled.

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#620]
Steps to reproduce the issue:
---------------------------------------
1. In Submariner repo, run "make clusters" - this will setup the necessary KIND clusters.
2. Lets deploy Submariner. 
3. subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --service-discovery
4. subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 --clusterid cluster2 --disable-nat ./broker-info.subm
5. Verify that in ConfigMap of CoreDNS the ServiceIP for supercluster.local:53 is properly set to submariner-lighthouse-coredns.

Now lets uninstall Submariner:
kubectl --context cluster2 delete namespace submariner-operator
kubectl --context cluster1 delete namespace submariner-k8s-broker

6. Reinstall Submariner in the clusters once again.
7. subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --service-discovery
8. subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 --clusterid cluster2 --disable-nat ./broker-info.subm

The ConfigMap of CoreDNS should ideally be updated with the new ServiceIP of submariner-lighthouse-coredns, but it still points to the old one.

**Comment by sridhargaddam** [comment]
@aswinsuryan @vthapar @nyechiel : Do we want to target this for 0.6?

**Comment by sridhargaddam** [comment]
@manosnoam JFYI, you might be hitting this issue in your testing.

**Comment by nyechiel** [comment]
> @aswinsuryan @vthapar @nyechiel : Do we want to target this for 0.6?

Yes, I think we should target this to v0.6. Thanks for reporting the issue @sridhargaddam

**Comment by manosnoam** [comment]
I think it is related to https://github.com/submariner-io/submariner/issues/641

On my env I run this cleanup in order to reinstall:

```
oc apply -f - <<EOF

  apiVersion: operator.openshift.io/v1
  kind: DNS
  metadata:
    finalizers:
    - dns.operator.openshift.io/dns-controller
    name: default
  spec:
    servers: []
EOF
```

**Comment by sridhargaddam** [comment]
> I think it is related to [submariner-io/submariner#641](https://github.com/submariner-io/submariner/issues/641)
> 
> On my env I run this cleanup in order to reinstall:
> 
> ```
> oc apply -f - <<EOF
> 
>   apiVersion: operator.openshift.io/v1
>   kind: DNS
>   metadata:
>     finalizers:
>     - dns.operator.openshift.io/dns-controller
>     name: default
>   spec:
>     servers: []
> EOF
> ```

AFAIU, it may not be the same issue. @aswinsuryan mentioned that this issue will not be seen with OCP.

**Comment by aswinsuryan** [comment]
> > I think it is related to [submariner-io/submariner#641](https://github.com/submariner-io/submariner/issues/641)
> > On my env I run this cleanup in order to reinstall:
> > ```
> > oc apply -f - <<EOF
> > 
> >   apiVersion: operator.openshift.io/v1
> >   kind: DNS
> >   metadata:
> >     finalizers:
> >     - dns.operator.openshift.io/dns-controller
> >     name: default
> >   spec:
> >     servers: []
> > EOF
> > ```
> 
> AFAIU, it may not be the same issue. @aswinsuryan mentioned that this issue will not be seen with OCP.

This issue was fixed with https://github.com/submariner-io/submariner-operator/pull/449, you could remove the script and try it should work.
