### ISSUE TITLE
[Epic] Unit tests for subctl command options

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#624]
This is an epic around the missing unit tests for all `subsctl` command options.
it consist, If possible, by a mocked environment for testing subctl (not within E2E in a live K8s clusters).

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by tpantelis** [comment]
bump
