### ISSUE TITLE
Please add subctl deploy --timezone option

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#634]
When deploying submariner on multi-zones clusters (e.g. Europe and US), and testing it from another zone (e.g. Asia),
the user might prefer to have all Submariner pods with same timezone as User time zone (Asia).

In addition, K8s pods timezone comes from the original pod image (e.g. UTC+0), and not from the underlying host, so it doesn't even show the current local timezone.

Can we add an optional flag to `subctl deploy` that will change the deployment of all submariner pods to use a specified timezone ?
For example: `--timezone=Asia/Jerusalem`

**Comment by mangelajo** [comment]
Let me try to understand the use case and let me know if the following are correct in my understanding:

1) Currently all pods use UTC+0 regardless of the host and timezone of the host.

2) You see this beneficial for logging purposes

**Comment by skitt** [comment]
The timezone is an attribute of the user viewing the logs, and should be dealt with by log viewing tools, not by changing the pod configuration. See [the cluster logging documentation](https://docs.openshift.com/container-platform/4.5/logging/cluster-logging.html).

**Comment by mangelajo** [comment]
> The timezone is an attribute of the user viewing the logs, and should be dealt with by log viewing tools, not by changing the pod configuration. See [the cluster logging documentation](https://docs.openshift.com/container-platform/4.5/logging/cluster-logging.html).

That was my gut feeling. Good that it's documented somewhere, thanks @skitt.

**Comment by manosnoam** [comment]
Now that we're adding [Prometheus operator ](https://github.com/submariner-io/submariner-website/pull/243),
we can consider adding this time-zone feature.

See this also:
https://github.com/prometheus-operator/prometheus-operator/pull/1865

**Comment by skitt** [comment]
> Now that we're adding [Prometheus operator ](https://github.com/submariner-io/submariner-website/pull/243),
> we can consider adding this time-zone feature.

Could you explain this in a bit more detail? `subctl` isn’t adding the Prometheus operator. The Submariner operator itself exports metrics now, but it doesn’t determine the timezone used anywhere in Prometheus.

**Comment by manosnoam** [comment]
Thanks for the info @skitt , @mangelajo , @nyechiel 

I will try to use the recommended method to configure timezone for each cluster:
`oc set env dc/dcname TZ=Asia/Jerusalem`

https://access.redhat.com/solutions/2567961
