### ISSUE TITLE
Subctl join should complete, only when Gateway is up and ready

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#635]
**What would you like to be added**:
See scenario in submariner-io/submariner#759 
subctl join command for cluster B finished at 08:25:07

However, on 08:25:49 the Gateway status was "Error", since Strongswan cable driver was not ready:
    Status Message:  No IKE SA found for cable submariner-cable-nmanos-cluster-a-10-166-15-143

**Why is this needed**:
To prevent dependent applications/services that rely on Submariner, to start sync between multi-clusters, while Submariner Gateway is not yet ready.

**Comment by sridhargaddam** [comment]
We can think of adding an argument like "**--wait**" for "subctl join ...." which will wait until the connections are established. The default behavior can be as what we have today.

**Comment by manosnoam** [comment]
@sridhargaddam 
As you suggested,  we can consider adding "--wait" option to subctl join to mitigate this issue.

**Comment by skitt** [comment]
This would still be nice to have.

**Comment by sridhargaddam** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by sridhargaddam** [comment]
Its still relevant

**Comment by sridhargaddam** [comment]
bump

**Comment by nyechiel** [comment]
Closing old issues. Please re-open if this is still relevant.
