### ISSUE TITLE
Subctl join cluster: Error retrieving broker admin config

### ISSUE THREAD

**Issue by ryzam** [submariner-io/submariner-operator#646]
Hi guys 
I need advice regarding this issue, already explore and google about this issue but still not find any working solution.

![image](https://user-images.githubusercontent.com/597759/91027914-4bee9600-e62f-11ea-93af-bab3d8135ad6.png)

**Comment by skitt** [comment]
How is your cluster deployed? Would it be at all possible for you to share the `broker-info.subm` file (privately — we wouldn’t try to access your clusters)?

**Comment by ryzam** [comment]
I have 3 clusters deployed across multiple datacenters using rancher

![image](https://user-images.githubusercontent.com/597759/91034247-46954980-e637-11ea-9605-506e6c9e3f5d.png).

googlecloud-cluster (Google Cloud) will be my submariner broker and other two clusters will join

- digitalocean-cluster (running in Digital Ocean DC)
- posvpc-cluster (running in private cloud)

[broker-info.zip](https://github.com/submariner-io/submariner-operator/files/5117242/broker-info.zip)

**Comment by ryzam** [comment]
After delete all the cluster and redeploy again, I able to setup submariner broker and join from 2 datacenters
