### ISSUE TITLE
libreswan.git tagged image in quay.io cannot be used with lighthouse "clusterset"

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#651]
When using latest subctl with `join --version libreswan-git' it, the operator image deployed seems to be an old one: quay.io/submariner/submariner-operator:libreswan-git

This breaks the recent support for using Lighthouse dns resolution for "clusterse.local":

`ping: nginx-cl-b.test-submariner-new.svc.clusterset.local: Name does not resolve`

See test report:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/debug_job/274/Test-Report/

_Originally posted by @manosnoam in https://github.com/submariner-io/submariner/issues/683#issuecomment-671288753_

**Comment by skitt** [comment]
This won’t fix the issue permanently, but I’ve updated all the `libreswan-git` images on Quay.
