### ISSUE TITLE
Missing WireGuard public key 

### ISSUE THREAD

**Issue by roytman** [submariner-io/submariner-operator#653]
From time to time a WireGuard EndPoint doesn't have peer public key. As result,  an error originally described in the https://github.com/submariner-io/submariner-operator/issues/461 is thrown. 

> 2020-08-24T16:17:27.2468249Z [cluster3] E0824 16:02:02.521694 1 tunnel.go:114] Tunnel controller failed to process submariner Endpoint with key "submariner-operator/cluster2-submariner-cable-cluster2-172-17-0-6": error installing cable for Endpoint types.SubmarinerEndpoint{Spec:v1.EndpointSpec{ClusterID:"cluster2", CableName:"submariner-cable-cluster2-172-17-0-6", Hostname:"cluster2-worker", Subnets:[]string{"169.254.2.0/24"}, PrivateIP:"172.17.0.6", PublicIP:"", NATEnabled:false, Backend:"wireguard", BackendConfig:map[string]string(nil)}}, failed to parse peer public key: endpoint is missing public key 

I have run a bunch of e2e tests (locally and at the Travis CI), but could not reproduce the error. 

My suspicion is that in the original main.go implementation the driver initiation is done simultaneously with  running datastoresyncer, which propagates the localEndpoint object to Kubernetes. In contrast to strongSwan and libreSwan, WireGuard driver should be initiated, and during this initiation the public key is generated and stored into the localEndpoint. 
Probably the datastoresyncer publishes  the localEndpoint before it was updated with WG public key.

I suggest to initialize cableEngine **before** starting the datastoresyncer. See https://github.com/submariner-io/submariner/pull/773.

is something missing? Would be happy to get your opinions.

**Comment by mangelajo** [comment]
@roytman I think that could work... we need to look at when that happens, if when it becomes master, or before... etc but sounds like a plan, good investigation

**Comment by roytman** [comment]
After the fix, I did not hear about missing WireGuard public key, so I assume that the issue is resolved.
