### ISSUE TITLE
subctl tickers must be stopped when starting a prompt

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#660]
For example during network discovery, if it can't find the cluster CIDR or service CIDR you end up with:

**⠊⠁ Discovering network details** CIDR for your cluster?

Instead of:
```
X Discovering network details
? What's the ClusterIP service CIDR for your cluster?
```

**Comment by nyechiel** [comment]
@maayanf24 would you be interested in looking at this?
