### ISSUE TITLE
subctl user option to set/unset update policy of submariner images

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#667]
This issue came to my mind after encountering bug https://github.com/submariner-io/submariner/issues/781

That bug happened since subctl-devel did not pull the correct tagged images of that specific submariner version from quay.
I would've expected it to pull the relevant images, according to subctl version. 
For example, in  # 781 case - it should have update Submariner images on the current cluster, to "v0.6.0-1-gcb7275d", when running subctl join command.

Setting "imagePullPolicy = Always" for devel releases: https://github.com/submariner-io/submariner-operator/pull/666
should fix bug # 781. 

However adding a new subctl user option to change imagePullPolicy of submariner, e.g.:
`--image-pull-policy always`
might be useful for users who wish keep Submariner with latest images.

**Comment by skitt** [comment]
Other than development releases, do you have specific scenarios in mind where this would help?

I don’t think setting the image pull policy to “always” would have any practical effect on non-development images: once tagged, images don’t change (or rather, aren’t supposed to change). So if you install using, say, `subctl --version 0.6.1`, you’ll only get 0.6.1, regardless of the image pull policy. If you then run `subctl --version 0.6.2`, the images won’t be present, so 0.6.2 will be pulled, again without having to set the image pull policy to “always”.

**Comment by manosnoam** [comment]
I think users may consider this, if wishing to keep their Submariner up-to-date, without reinstalling a new version manually each period.

**Comment by skitt** [comment]
> I think users may consider this, if wishing to keep their Submariner up-to-date, without reinstalling a new version manually each period.

But how would that work?

**Comment by skitt** [comment]
Hmm, I suppose this could work with `--version latest`, but we don’t support upgrades like that yet.
