### ISSUE TITLE
Add some way to disable reconciliation temporarily

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#670]
In some cases it’s useful to be able to tweak a `DaemonSet` that’s managed by the operator. Currently this requires stopping the operator, which causes other issues — in particular, `subctl` then gets stale information from the `Submariner` status.

We could check for a label, for example `submariner.io/operator-ignore`, on DaemonSets, and if set, ignore them in reconciliation.

**Comment by mangelajo** [comment]
I wonder if there's any standard (even de-facto) around this
