### ISSUE TITLE
Migrate to Operator SDK 1.0

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#678]
We need to migrate the operator to use version 1.0 of the SDK. This will bring a number of benefits, not least of which is using a “supported” stable SDK: better kubebuilder integration (so we can generate RBAC from code, in particular), flat bundle generation (for the CSVs)...

**Comment by SteveMattar** [comment]
+1

**Comment by nyechiel** [comment]
Instructions for migrating a legacy Go-based project to use the new Kubebuilder-style: layout.https://master.sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/

**Comment by skitt** [comment]
Oops, sorry @SteveMattar, I didn’t think removing your comment would also unassign you from the issue!

**Comment by SteveMattar** [comment]
we should open an issue on that :)

**Comment by nyechiel** [comment]
bump
