### ISSUE TITLE
Rationalise service accounts

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#679]
We have a number of service accounts with different configurations, but probably not enough (and the permissions requested aren’t well-documented).

My thoughts on this are that the operator should have a single service account with all the appropriate privileges, and then our applications should have their own service accounts. If privileges vary depending on the deployment (*e.g.* with or without Lighthouse or Globalnet), we should modify the service account accordingly instead of adding a `:`-prefixed variant (or is that idiomatic K8s?).

**Comment by nyechiel** [comment]
Thanks for looking into this, @SteveMattar. Pushing out from v0.8.0 as I think that it's too risky to merge at this point. Moving to the next sprint
