### ISSUE TITLE
The subctl deploy-broker syntax is confusing to the user

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#69]
Right now you could do:

```
export KUBECONFIG=clusterA
subctl deploy-broker  --clusterID=clusterA

export KUBECONFIG=clusterB
subctl join broker-info.subm
```

And that would be enough to connect the dataplane of both clusters, but people seems to be confused by the fact that "deploy-broker" will also deploy the dataplane (unless you say --no-dataplane).

For the shake of simplicity I believe we may want to change to:
```
export KUBECONFIG=clusterA
subctl deploy-broker
subctl join broker-info.subm  --clusterID=clusterA

export KUBECONFIG=clusterB
subctl join broker-info.subm  --clusterID=cluster B
```

**Comment by manosnoam** [comment]
Yes, that will be clearer, since "deploy-broker" command is not "deploy-broker-and-join".

**Comment by skitt** [comment]
I agree, I always use `--no-dataplane`. If we want we can always provide an explicit all-in-one command (see #62).
