### ISSUE TITLE
Intra-cluster throughput benchmark

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-operator#707]
Add ability to test intra-cluster throughput benchmark:
ClusterA worker node to ClusterA gateway

Update subctl command:
`subctl benchmark throughput <kubeconfig1> [<kubeconfig2] [flags]`

**Comment by nyechiel** [comment]
@maayanf24 can you please add this to the docs under https://submariner.io/deployment/subctl/#benchmark
