### ISSUE TITLE
Please add subctl --version

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#72]
At the moment this is the output:

[nmanos@nmanos submariner-operator]$ subctl --version
Error: unknown flag: --version
Usage:
  subctl [command]

Available Commands:
  deploy-broker set the broker up
  help          Help about any command
  info          Get information on your cluster related to submariner
  join          connect a cluster to an existing broker

Flags:
  -h, --help                help for subctl
      --kubeconfig string   absolute path(s) to the kubeconfig file(s) (default "/home/nmanos/.kube/config")

Use "subctl [command] --help" for more information about a command.

panic: unknown flag: --version

goroutine 1 [running]:
main.main()
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:8 +0x84

**Comment by mangelajo** [comment]
Makes sense! :)

**Comment by mangelajo** [comment]
Added:

```subctl version```

as openshift-install version, ...
