### ISSUE TITLE
[OperatorHub] Update submariner-operator to v0.7.0

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner-operator#741]

**Comment by skitt** [comment]
Note that there’s a slight change of plan regarding the CRDs: for v0.7.0 we’ll need both `Submariner` and `ServiceDiscovery` in the CSV.

**Comment by SteveMattar** [comment]
@skitt is it only for 0.7?

**Comment by skitt** [comment]
> @skitt is it only for 0.7?

Actually, change of plan again, we only need `Submariner` for 0.7!

**Comment by SteveMattar** [comment]
operator-framework/community-operators#2523
operator-framework/community-operators#2524
