### ISSUE TITLE
subctl join command to print more params info

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#76]
Subctl prints the following output on join command:

kubconf_b subctl join --clusterid subm-cluster-b ./broker-info.subm --ikeport 501 --nattport 4501

  * ./broker-info.subm says broker is at: https://api.nmanos-cluster-a.devcluster.openshift.com:6443
...
      Discovered network details:
          Network plugin:  OpenShift
          ClusterIP CIDRs: [100.96.0.0/16]
          Pod CIDRs:       [10.252.0.0/14]

While this is also good to know:
    repository: quay.io/submariner
    ceIPSecIKEPort: 501
    ceIPSecNATTPort: 4501

(Generated with "kubectl get Submariner -n submariner-operator -o yaml")

In addition, "Pod CIDRs" is pointing to "clusterCIDR", and "ClusterIP CIDRs" is pointing to "serviceCIDR", which is confusing, can you rename accordingly ?

**Comment by sridhargaddam** [comment]
> In addition, "Pod CIDRs" is pointing to "clusterCIDR", and "ClusterIP CIDRs" is pointing to "serviceCIDR", which is confusing, can you rename accordingly ?

In K8s terminology, there is no Pod CIDRs, its referred to as "Cluster CIDRs". Hence we did this change to be aligned with k8s naming convention.
