### ISSUE TITLE
Update Readme: ike and natt ports should be accisble on the public cluster

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#77]
When running:
`subctl join --clusterid subm-cluster-a ./broker-info.subm --ikeport 501 --nattport 4501`

This does not open the required ports on the cloud infra, so we need to acknowledge the Admin, if not run it with subctl.

Should we add a command option to subctl, for openning ike and natt ports on the cluster with the broker, or should we only add this required steps to the Readme for admins to do manually ?

**Comment by mangelajo** [comment]
It's out of scope for subctl, but we can increase the verbosity on does details in #76 as you requested, reminding the admin that it must take care of opening such ports.

**Comment by manosnoam** [comment]
The verbosity requested on #76 is a different matter.

This current issue is about the infrastructure requirements:
Those ports must initially be accessible on the public cluster with the broker, if one of the other clusters is behind NAT.

I will modify the ticket title, to add the following requirment to the SubM Readme:
Direct the administrator to:
- Use the `prep_for_subm.sh`, 
- Or manually open these ports in Cluster security groups.

**Comment by sridhargaddam** [comment]
@manosnoam The readme is updated with the necessary info here - https://submariner-io.github.io/quickstart/#prerequisites
Let us know if you think anything additional needs to be captured.

**Comment by manosnoam** [comment]
> @manosnoam The readme is updated with the necessary info here - https://submariner-io.github.io/quickstart/#prerequisites
> Let us know if you think anything additional needs to be captured.

Thanks @sridhargaddam 
I did not see instruction on using `prep_for_subm.sh` to open those ports, etc.

**Comment by sridhargaddam** [comment]
> > @manosnoam The readme is updated with the necessary info here - https://submariner-io.github.io/quickstart/#prerequisites
> > Let us know if you think anything additional needs to be captured.
> 
> Thanks @sridhargaddam
> I did not see instruction on using `prep_for_subm.sh` to open those ports, etc.

prep_for_subm.sh is AWS Specific and does not work on other public clouds. So, its captured as part of AWS Quickstart guides here - https://submariner-io.github.io/quickstart/openshift/service_discovery/#make-your-clusters-ready-for-submariner

**Comment by manosnoam** [comment]
Thanks @sridhargaddam
