### ISSUE TITLE
Support 'Image' in submariners API spec

### ISSUE THREAD

**Issue by SteveMattar** [submariner-io/submariner-operator#781]
In `submariners` API spec we allow currently to set a custom repository and custom image tag but the containers image **names** are not supported.
In some cases the components image names could be different than the default ones but currently those names are hard coded in the operator.
It would be a good idea to let the user decide which image names to use.
These options should be available in both the CRD and `subctl`

**Comment by manosnoam** [comment]
This is something I need as well - Passing registry url to subctl would be great.
+ @maxbab

**Comment by SteveMattar** [comment]
#726

**Comment by mangelajo** [comment]
This, or .... the D/S versions of the operator could have those images baked instead?

is it a suffix?, is it a preffix? we can add support for that too instead

I think that single image-per-image modification is probably a little bit cumbersome to the user, ... let's do prefix/suffix, or simply lets make sure that the downstream operator image has the right image names baked in.

**Comment by mangelajo** [comment]
@SteveMattar can you add some examples of how the image names would be?

**Comment by skitt** [comment]
> I think that single image-per-image modification is probably a little bit cumbersome to the user, ... let's do prefix/suffix, or simply lets make sure that the downstream operator image has the right image names baked in.

Perhaps, instead of specifying all the components separately, we could allow the user to override the full container reference (repo + image + tag). That’s a fairly common pattern in the K8s world AFAICT, and would result in fewer parameters for these use-cases.

**Comment by SteveMattar** [comment]
@mangelajo this is how it looks like today

* submariner-submariner-operator-rhel8
* submariner-submariner-engine-rhel8
* submariner-submariner-route-agent-rhel8
* submariner-submariner-globalnet-rhel8
* submariner-lighthouse-agent-rhel8
* submariner-lighthouse-coredns-rhel8

**Comment by mangelajo** [comment]
> > I think that single image-per-image modification is probably a little bit cumbersome to the user, ... let's do prefix/suffix, or simply lets make sure that the downstream operator image has the right image names baked in.
> 
> Perhaps, instead of specifying all the components separately, we could allow the user to override the full container reference (repo + image + tag). That’s a fairly common pattern in the K8s world AFAICT, and would result in fewer parameters for these use-cases.

But isn't that what Steve was proposing?,

I think that submariner-submariner-operator-rhel8 should know that it has to deploy submariner-$XX-rhel8 images by default.

I think it's good if we can also (optionally) allow for single-image overrides. That will come handy when we need to provide support or hotfixes for specific images.

**Comment by mangelajo** [comment]
> @mangelajo this is how it looks like today
> 
> * submariner-submariner-operator-rhel8
> * submariner-submariner-engine-rhel8
> * submariner-submariner-route-agent-rhel8
> * submariner-submariner-globalnet-rhel8
> * submariner-lighthouse-agent-rhel8
> * submariner-lighthouse-coredns-rhel8

So I see multiple options here:

1.a) no CR parameters for prefix/sufix of images, the operator for rhel8 will know what to use.
     this is not very flexible and support later down the read will be a PITA.
1.b) no CR parameters for prefix/sufix of images, the operator for rhel8 will know what to use.
     single image overrides (as an optional thing, to let us test , fix & hotfix cases)
2.a) CR paramters for prefix/suffix, in rhel8 the go by default with submariner-  &  -rhel8, empty for community
2.b) CR paramters for prefix/suffix, in rhel8 the go by default with submariner-  &  -rhel8, empty for community
        single image overrides (as an optional thing, to let us test , fix & hotfix cases)


Probably there are more options I'm not seeing, but I believe 2.b probably would give us the most flexibility in terms of what we can do... we could even develop/debug with the community operator, and still specify downstream images, or install the community operator downstream (for testing purposes) as long as we provide prefix/suffix.

**Comment by SteveMattar** [comment]
@mangelajo I think we have to make a separation between the users and the developers. In my opinion the users should not mess with any of these parameters and all submariner components should act as a single product. We should have default values for both u/s and d/s.
Finally, to let the developers test/debug easily we can have an optional single image overrides just like you said.

**Comment by mangelajo** [comment]
> @mangelajo I think we have to make a separation between the users and the developers. In my opinion the users should not mess with any of these parameters and all submariner components should act as a single product. We should have default values for both u/s and d/s.
> Finally, to let the developers test/debug easily we can have an optional single image overrides just like you said.

Ok, so we agree it's what I was trying to say: that we should leave that flexibility hidden, but the defaults should be the right ones for your platform. Let's model them.

**Comment by mangelajo** [comment]
Ok we sync'd and we believe something like this could work:

```yaml
apiVersion: submariner.io/v1alpha1
kind: Submariner
metadata:
  name: example-submariner
spec:
  broker: k8s
  .....
  serviceDiscoveryEnabled: true
  #repository: quay.io/submariner
  #version: 0.7.0
  # for downstream the default would be different repository "registry.redhat.com/..." and we need to control this with a variable that we can modify at compile time , we need to convert this to variables: https://github.com/submariner-io/submariner-operator/blob/b149f6225217581ebdc2f9692b15916636a73d60/pkg/versions/versions.go#L3

    # and the images would have a prefix/postfix handled here: https://github.com/submariner-io/submariner-operator/blob/b149f6225217581ebdc2f9692b15916636a73d60/pkg/images/images.go

# then, for CI, development, testing or hotfixes we could add this as a string map, which would be used be GetImagePath to override the images by component.
  imageOverrides: 
    - submariner-route-agent: "registry-proxy.engineering.redhat.com/rh-osbs/submariner-submariner-route-agent-rhel8:rh-submariner-0.4-rhel-8-containers-candidate-63034-20201105000103"



apiVersion: submariner.io/v1alpha1
kind: ServiceDiscovery
metadata:
  name: service-discovery
spec:
  broker: k8s
  ...
  imageOverrides:
    - ....
    - ....
