### ISSUE TITLE
Script at https://get.submariner.io fails on Mac OSX due to its "install" not supporting the "-D" flag

### ISSUE THREAD

**Issue by mgoddard** [submariner-io/submariner-operator#790]
**What happened**:
subctl installation failed with the following:
```
$ curl -Ls https://get.submariner.io | VERSION=0.7.0 bash
subctl deploy-broker --kubecontext ${control_cluster} --service-discovery
mv broker-info.subm /tmp/broker-info.subm
for context in ${cluster1} ${cluster2} ${cluster3}; do
  subctl join --kubecontext ${context} /tmp/broker-info.subm --no-label --clusterid $(echo ${context} | cut -d "/" -f2 | cut -d "-" -f2) --version devel --cable-driver libreswan
done
Installing subctl version v0.7.0
  OS detected:           darwin
  Architecture detected: amd64
  Download URL:          https://github.com/submariner-io/submariner-operator/releases/download/v0.7.0/subctl-v0.7.0-darwin-amd64.tar.xz

Downloading...
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

**What you expected to happen**:
To be able to run `subctl` from the command line

**How to reproduce it (as minimally and precisely as possible)**:
If you are running Mac OSX, this should trigger it: `curl -Ls https://get.submariner.io | VERSION=0.7.0 bash`

**Anything else we need to know?**:
The following change get us past this issue:
```
 #install -D "${bin}" "${dest}"
  mkdir -p "$destdir"
  cp -f "${bin}" "${dest}"
```

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): `Darwin hodad 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mangelajo** [comment]
@mgoddard thanks for the report, let's fix this.

**Comment by mangelajo** [comment]
@skitt I'll change this to get compatibility back to OSX.
