### ISSUE TITLE
subctl benchmark to support Globalnet deployments

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/submariner-operator#797]
**What would you like to be added**:
Currently, "subctl benchmark" supports throughput and latency tests for Vanilla Submariner.
We need support in "subctl benchmark" to support even Globalnet deployments.

**Why is this needed**:
This is necessary so that we can use "subctl benchmark" for Globalnet deployments.

**Comment by sridhargaddam** [comment]
In order to validate latency between the clusters, subctl internally uses netperf tool.
Netperf is a tool that is designed as a client-server model. When a netperf client connects to a server, the first thing will be an establishment of the control connection. This control connection happens on TCP/12865 port.
Once the control connection is setup and configuration information is passed to the server, a separate connection is opened for validating the actual latency tests. The port numbers used for the new connection are not fixed and are exchanged dynamically during the initial control connection phase. Because of this, we cannot use netperf/netserver with K8s ClusterIP services where the port numbers have to be explicitly specified during service creation.

Currently, Globalnet supports only pod to remoteService communication. So, until we support Headless-Services/Stateful-Sets/Pod-to-Pod communication in Globalnet, we cannot benchmark latency using netperf.

**Comment by skitt** [comment]
@sridhargaddam `netperf` can be used without a control connection, using the `-N` option. When this is invoked, the tests use well-known ports by default (echo, chargen, discard), and those ports can also be specified to different values on the command line. So I think it should be possible to fix the set of ports to use ahead of time.

**Comment by sridhargaddam** [comment]
> @sridhargaddam `netperf` can be used without a control connection, using the `-N` option. When this is invoked, the tests use well-known ports by default (echo, chargen, discard), and those ports can also be specified to different values on the command line. So I think it should be possible to fix the set of ports to use ahead of time.

Thanks @skitt, but it does not seem to work.

Running the netperf client, normally:
```
bash-5.0# netperf -H 10.3.128.3 -t TCP_RR -p 12865 -- -o min_latency,mean_latency,max_latency,stddev_latency,transaction_rate
MIGRATED TCP REQUEST/RESPONSE TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.3.128.3 (10.3.12) port 0 AF_INET : first burst 0
Minimum Latency Microseconds,Mean Latency Microseconds,Maximum Latency Microseconds,Stddev Latency Microseconds,Transaction Rate Tran/s
86,118.91,2874,53.18,8390.342
```

With -N option
```
bash-5.0# netperf -N -H 10.3.128.3 -t TCP_RR -p 12865 -- -o min_latency,mean_latency,max_latency,stddev_latency,transaction_rate
MIGRATED TCP REQUEST/RESPONSE TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.3.128.3 (10.3.12) port 7 AF_INET : no control : first burst 0
netperf: send_omni: connect_data_socket failed: Connection refused
```

**Comment by skitt** [comment]
Ah that’s a shame :-(.

**Comment by nyechiel** [comment]
@maayanf24 as discussed over Slack, let's implement only the `throughput` part for now.

**Comment by nyechiel** [comment]
@maayanf24 this needs a small docs change here: https://submariner.io/operations/known-issues/#globalnet

**Comment by skitt** [comment]
Assigning to @manosnoam for verification.

**Comment by pinikomarov** [comment]
Starting work on this...

**Comment by pinikomarov** [comment]
Hi guys @skitt @sridhargaddam @maayanf24 
I'm creating a CI test for this , 

Performing latency tests from Gateway pod to Gateway pod:

Minimum Latency Microseconds,Mean Latency Microseconds,Maximum Latency 
Microseconds,Stddev Latency Microseconds,Transaction Rate Tran/s
33,58.81,2115,41.68,16938.140

Performing latency tests from Non-Gateway pod to Non-Gateway pod

Minimum Latency Microseconds,Mean Latency Microseconds,Maximum Latency Microseconds,Stddev Latency Microseconds,Transaction Rate Tran/s
59,97.96,3732,71.19,10186.169

How would you define a pass / fail criteria for this test ? ..say given the stats above ^^^
thanks

**Comment by tpantelis** [comment]
> How would you define a pass / fail criteria for this test ? ..say given the stats above ^^^
> thanks

I assume this is to test the `subctl benchmark ` command? If so,  I guess we'd just ensure that it successfully reports data - that's what I did for the gateway metrics e2e test in submariner. I don't think it's really feasible to define absolute pass / fail threshold criteria w/o risking intermittent failures, unless the thresholds are really high to give a safe cushion but that doesn't seem that useful.

**Comment by pinikomarov** [comment]
> I assume this is to test the subctl benchmark command? If so, I guess we'd just ensure that it successfully reports data 

Thanks , I'll go with that

**Comment by pinikomarov** [comment]
@manosnoam  Can you take a look ? ->> This pull request test should close this issue:
Adding a: add_test_subctl_benchmark CI test PR:
https://github.com/manosnoam/ocp-multi-cluster-tester/pull/37

**Comment by pinikomarov** [comment]
@manosnoam please review : an updated pull request with the changes you requested , 
the function defined in the right place with the catch code :
https://github.com/manosnoam/ocp-multi-cluster-tester/pull/43/files

**Comment by manosnoam** [comment]
Closing this issue. 
We're adding CI test in https://github.com/manosnoam/ocp-multi-cluster-tester/pull/37
