### ISSUE TITLE
Option to pass images registry url to subctl

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner-operator#830]
Once https://github.com/submariner-io/submariner-operator/pull/829 is merged,
please add a new flag to subctl join command - to use specific registry url.

_Originally posted by @manosnoam in https://github.com/submariner-io/submariner-operator/issues/781#issuecomment-722381418_

**Comment by nyechiel** [comment]
@manosnoam the PR is merged - moving this Issue back to "Verify" so that you can test it

**Comment by manosnoam** [comment]
@nyechiel @SteveMattar  can you specify ALL required images urls from Quay ?
Are those images up to date, or should I constantly check for the recent images ?

**Comment by SteveMattar** [comment]
@manosnoam this flag is optional you dont need to specify all images
But only the ones you wish to override

**Comment by nyechiel** [comment]
@manosnoam have you managed to try this?
