### ISSUE TITLE
make a release to fix: panic: CustomResourceDefinition.apiextensions.k8s.io "submariners.submariner.io" is invalid

### ISSUE THREAD

**Issue by uwekolsch** [submariner-io/submariner-operator#95]
i'm trying to install submariner using subctl on a set of clusters in rancher 2.3.3. Installing the broker seem to work fine but when i try to join a cluster i end put with this:

bash-5.0# subctl join --kubeconfig /root/.kube/config broker-info.subm
* broker-info.subm says broker is at: https://\<domain\>/k8s/clusters/c-tk9l7
? What is your cluster ID? paris
* There are 1 labeled nodes in the cluster:
  - master1
* Deploying the submariner operator
panic: CustomResourceDefinition.apiextensions.k8s.io "submariners.submariner.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc010355d28), Subresources:(*apiextensions.CustomResourceSubresources)(0xc009604270), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc010355d28), Subresources:(*apiextensions.CustomResourceSubresources)(0xc009604270), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]

goroutine 1 [running]:
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.panicOnError(...)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:70
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.joinSubmarinerCluster(0xc0004a4a80)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:116 +0x919
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.glob..func2(0x2096560, 0xc00041fa70, 0x1, 0x3)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/join.go:60 +0x14a
github.com/spf13/cobra.(*Command).execute(0x2096560, 0xc00041fa10, 0x3, 0x3, 0x2096560, 0xc00041fa10)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x20967e0, 0x1118aba, 0xc00033bf88, 0xc00009a058)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/submariner-io/submariner-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/submariner-io/submariner-operator/pkg/subctl/cmd.Execute(...)
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/cmd/root.go:35
main.main()
	/go/src/github.com/submariner-io/submariner-operator/pkg/subctl/main.go:6 +0x2f

**Comment by skitt** [comment]
Thanks for your interest! The symptoms appear to be identical to those of #66, so I’m guessing this is because Rancher 2.3.3 is using a newer version of Kubernetes than we currently support. That will be fixed _very_ soon...

**Comment by mangelajo** [comment]
Oh, this is fixed here I believe, but we need a new build: 

https://github.com/submariner-io/submariner-operator/pull/80

**Comment by mangelajo** [comment]
I will create a new release of the binaries

**Comment by mangelajo** [comment]
@uwekolsch can you try https://github.com/submariner-io/submariner-operator/releases/tag/v0.0.3 and tell me if it fixes the issue for you?

Thanks a lot

**Comment by uwekolsch** [comment]
Ok, will do, but has to wait till the weekend, it's kind of my "hobby".

**Comment by uwekolsch** [comment]
@mangelajo - sorry for delayed response but installation worked now without a problem. Thanks.

**Comment by mangelajo** [comment]
Nice! Thanks for the report :-)

Enviado desde mi iPhone

**Comment by uwekolsch** [comment]
@mangelajo - as i stated above installation works now without any errors but i don't get a connection between pods in different clusters. I run the clusters in AWS, with each cluster being in a different region. In the instructions for installing using kubectl it is said that natEnabled should be set to true if 1:1 NAT is used, with AWS PVC given as an example where this is the case. Is it somehow possible to to set this to true for an installation via subctl?

**Comment by skitt** [comment]
`subctl` enables NAT by default, it can be disabled if necessary with the `--disable-nat` option on `subctl join`.

**Comment by Jaanki** [comment]
Using --disable-nat works for me. I can now install subm and have connectivity between k8s1.14 and k8s 1.117 clusters.
