### ISSUE TITLE
Move "E2E" verification tests to system tests

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner-operator#967]
This was raised in #962 initially but deserves it's own issue.

Currently we have a lot of verifications for subctl and operator happening in https://github.com/submariner-io/submariner-operator/blob/master/scripts/kind-e2e/lib_operator_verify_subm.sh
this is being executed as part of the E2E tests but unlike the E2E tests which are "black box", these tests are very "white box" and check that the deployment happened as expected (e.g. the cable driver was set and all that).

It would be better to move these tests into a kind of "system test" style of testing, probably in Go, where the tests could run subctl and verify that the expected outcome has happened (e.g. submariner CR was created with correct fields) and furthermore test that the operator deploys correctly.

An added benefit of using a proper testing framework would be that we'd have a test report summarizing which tests failed and which passed, as opposed to the current situation in which verification would halt at the first failure.

For this purpose we could utilize an "all in one" kind environment of just 1 cluster with 1 node, since we don't really care to see that submariner is functional but rather that the expected state has been reached (i.e. deployments, daemonsets, and all expected resources have been properly created).

**Comment by tpantelis** [comment]
bump

**Comment by mkolesnik** [comment]
bump

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
I think the main thing that would be helpful here is to extract these tests to not run in every job, as they shouldn't be impacted by matrix dimensions like the cable driver.

**Comment by mkolesnik** [comment]
@mkolesnik will collect data how much time these take and update the issue

**Comment by dfarrell07** [comment]
There's probably also a way to speed them up dramatically by batching test calls into containers. I think currently they are slow because each validation is its own call into a container, which takes about a second. If we could do all the checks for that container in the same call, that would speed things up. That might require more refactoring than it's worth however, IDK.

**Comment by nyechiel** [comment]
@mkolesnik are you working on this for 0.13?
